### ISSUE TITLE
Loading Chunk Error - 1.15.2 > 1.12 Conversion

### ISSUE THREAD

**Issue by Buzzbugs** [Amulet-Team/Amulet-Map-Editor#10]
fp.truncate(file_size)
io.UnsupportedOperation: File not open for writing
2020-03-10 13:58:21,841 - amulet_core - INFO - Error loading chunk -1 -480
Traceback (most recent call last):
  File "lib\site-packages\amulet\world_interface\formats\__init__.py", line 175, in load_chunk
  File "lib\site-packages\amulet\world_interface\formats\__init__.py", line 202, in _load_chunk
  File "C:\Users\drako\Desktop\Amulet-Converter\amulet\world_interface\formats\anvil\anvil_format.py", line 448, in _get_raw_chunk_data
    return self._get_level(dimension).get_chunk_data(cx, cz)
  File "C:\Users\drako\Desktop\Amulet-Converter\amulet\world_interface\formats\anvil\anvil_format.py", line 250, in get_chunk_data
    return self._get_region(cx, cz).get_chunk_data(cx & 0x1F, cz & 0x1F)
  File "C:\Users\drako\Desktop\Amulet-Converter\amulet\world_interface\formats\anvil\anvil_format.py", line 176, in get_chunk_data
    self._load()
  File "C:\Users\drako\Desktop\Amulet-Converter\amulet\world_interface\formats\anvil\anvil_format.py", line 76, in _load
    fp.truncate(file_size)
io.UnsupportedOperation: File not open for writing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\amulet\api\world.py", line 121, in save
  File "lib\site-packages\amulet\world_interface\formats\__init__.py", line 180, in load_chunk
amulet.api.errors.ChunkLoadError
2020-03-10 13:58:21,841 - amulet_core - INFO - Converting chunk overworld -1, -479
2020-03-10 13:58:21,841 - amulet_core - ERROR - Error loading chunk -1 -479
Traceback (most recent call last):
  File "lib\site-packages\amulet\world_interface\formats\__init__.py", line 175, in load_chunk
  File "lib\site-packages\amulet\world_interface\formats\__init__.py", line 202, in _load_chunk
  File "C:\Users\drako\Desktop\Amulet-Converter\amulet\world_interface\formats\anvil\anvil_format.py", line 448, in _get_raw_chunk_data
    return self._get_level(dimension).get_chunk_data(cx, cz)
  File "C:\Users\drako\Desktop\Amulet-Converter\amulet\world_interface\formats\anvil\anvil_format.py", line 250, in get_chunk_data
    return self._get_region(cx, cz).get_chunk_data(cx & 0x1F, cz & 0x1F)
  File "C:\Users\drako\Desktop\Amulet-Converter\amulet\world_interface\formats\anvil\anvil_format.py", line 176, in get_chunk_data
    self._load()
  File "C:\Users\drako\Desktop\Amulet-Converter\amulet\world_interface\formats\anvil\anvil_format.py", line 76, in _load
    fp.truncate(file_size)
io.UnsupportedOperation: File not open for writing
2020-03-10 13:58:21,842 - amulet_core - INFO - Error loading chunk -1 -479
Traceback (most recent call last):
  File "lib\site-packages\amulet\world_interface\formats\__init__.py", line 175, in load_chunk
  File "lib\site-packages\amulet\world_interface\formats\__init__.py", line 202, in _load_chunk
  File "C:\Users\drako\Desktop\Amulet-Converter\amulet\world_interface\formats\anvil\anvil_format.py", line 448, in _get_raw_chunk_data
    return self._get_level(dimension).get_chunk_data(cx, cz)
  File "C:\Users\drako\Desktop\Amulet-Converter\amulet\world_interface\formats\anvil\anvil_format.py", line 250, in get_chunk_data
    return self._get_region(cx, cz).get_chunk_data(cx & 0x1F, cz & 0x1F)
  File "C:\Users\drako\Desktop\Amulet-Converter\amulet\world_interface\formats\anvil\anvil_format.py", line 176, in get_chunk_data
    self._load()
  File "C:\Users\drako\Desktop\Amulet-Converter\amulet\world_interface\formats\anvil\anvil_format.py", line 76, in _load
    fp.truncate(file_size)

**Comment by gentlegiantJGC** [comment]
This should be fixed in the next build. The file was only being opened in read mode so it couldn't modify the file.
How was the source world created? The fact that the code was used at all implies there is an issue with the files in the source world.

**Comment by Buzzbugs** [comment]
I think it was made in worldpainter some time ago, it's not a new world by any means. It might need some repairs.
