### ISSUE TITLE
[Bug Report] 3D editor doesn't render

### ISSUE THREAD

**Issue by SprainedSpark89** [Amulet-Team/Amulet-Map-Editor#1002]
### Current Behaviour:

it doesn't render the world/the lined plain
### Expected behavior:

to render everything correctly
### Steps To Reproduce:

load a world in the 3d editor
### Environment:

- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.13-1.14 (the world versions i tried)
- Amulet Version: v0.10.23

### Screenshots

![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/87820585/13cbf03b-295b-476a-a986-973c4f8627fb)

**Comment by gentlegiantJGC** [comment]
Are there any errors in the console?

**Comment by SprainedSpark89** [comment]
yes 
Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\plugins\tools\select.py", line 329, in _on_draw
  File "amulet_map_editor\programs\edit\api\renderer.py", line 224, in draw_sky_box
  File "amulet_map_editor\api\opengl\mesh\sky_box.py", line 63, in draw
  File "amulet_map_editor\api\opengl\mesh\tri_mesh.py", line 161, in draw
  File "amulet_map_editor\api\opengl\mesh\tri_mesh.py", line 89, in _setup
  File "amulet_map_editor\api\opengl\resource_pack\resource_pack.py", line 69, in get_atlas_id
  File "amulet_map_editor\api\opengl\resource_pack\resource_pack.py", line 156, in _setup_texture
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1280,
        description = b'invalid enumerant',
        baseOperation = glTexParameteri,
        cArguments = (
                GL_TEXTURE_2D,
                GL_TEXTURE_WRAP_S,
                GL_CLAMP_TO_EDGE,
        )
)

**Comment by gentlegiantJGC** [comment]
There should be a line in the console saying which OpenGL version your computer supports. What does that say?

**Comment by SprainedSpark89** [comment]
it says it's using opengl v1.1.0 for some reason but my pc can use later versions

**Comment by Ampersand20** [comment]
Getting similar issue (my name is in the file tree so i replaced it with asterisks)

```
INFO - Could not find loader for C:\Users\*****\Downloads\abf67dfc-8c31-4d97-90a6-0871285f37bd.tar Could not find a matching format for C:\Users\*****\Downloads\abf67dfc-8c31-4d97-90a6-0871285f37bd.tar
INFO - Loading level C:\Users\*****\Downloads\abf67dfc-8c31-4d97-90a6-0871285f37bd.tar
ERROR - Could not find a loader for this world.
Could not find a matching format for C:\Users\*****\Downloads\abf67dfc-8c31-4d97-90a6-0871285f37bd.tar
```

**Comment by gentlegiantJGC** [comment]
That looks like a very different issue. I don't even know what that format is.

**Comment by Avantir-Chaosfire** [comment]
I also have this problem, with yet a different error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 329, in _on_draw
    self.canvas.renderer.draw_sky_box()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/renderer.py", line 224, in draw_sky_box
    self.sky_box.draw(self.canvas.camera.transformation_matrix)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/sky_box.py", line 63, in draw
    super().draw(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/tri_mesh.py", line 161, in draw
    self._setup()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/tri_mesh.py", line 90, in _setup
    self._shader = get_shader(self.context_identifier, self.shader_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/shaders/__init__.py", line 60, in get_shader
    shader = compile_shader()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/shaders/__init__.py", line 49, in compile_shader
    _load_shader(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/shaders/__init__.py", line 75, in _load_shader
    return OpenGL.GL.shaders.compileShader(shader, shader_type)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/OpenGL/GL/shaders.py", line 235, in compileShader
    raise ShaderCompilationError(
OpenGL.GL.shaders.ShaderCompilationError: ('Shader compile failure (0): b"WARNING: 0:2: extension \'GL_ARB_explicit_attrib_location\' is not supported\\nERROR: 0:4: \'layout\' : syntax error: syntax error\\n"', [b'#version 120\r\n#extension GL_ARB_explicit_attrib_location : enable\r\n\r\nlayout(location = 0) in vec3 positions;\r\nlayout(location = 1) in vec2 vTexCoord;\r\nlayout(location = 2) in vec4 vTexOffset;\r\nlayout(location = 3) in vec3 vTint;\r\n\r\nvarying vec2 fTexCoord;\r\nvarying vec4 fTexOffset;\r\nvarying vec3 fTint;\r\n\r\nuniform mat4 transformation_matrix;\r\n\r\nvoid main(){\r\n    gl_Position = transformation_matrix * vec4(positions, 1.0);\r\n    fTexCoord = vTexCoord;\r\n    fTexOffset = vTexOffset;\r\n    fTint = vTint;\r\n}'], GL_VERTEX_SHADER)
```

**Comment by Ezekielman** [comment]
I think I have a similar issue. No world is rendered, only 2 red checkerboards above and below where the chunks should be. I am getting errors in the console too.

OS: MacOS Sequoia
Hardware: Mac Mini M1 16GB
