### ISSUE TITLE
[Bug Report] World becomes corrupted after importing `.construction` file

### ISSUE THREAD

**Issue by D3V1L0M3N** [Amulet-Team/Amulet-Map-Editor#1003]
**Describe the bug**
Importing a `.construction` file into a 1.18.2 world causes the game to hang/crash and generate errors in game log

**Expected behavior**
The game should not crash after importing `.construction` file into the world

**To Reproduce**
1. Open Minecraft 1.18.2 and load sample world _Hogwarts_ then Save and Quit to Title
2. Open Amulet and load sample world _Hogwarts_
2. Create selection using 3D Editor and export as _Hogwarts.construction_ using Platform 'java' & Version '1, 18, 0'
3. In Amulet, open sample world _Creative_
4. Import file _Hogwarts.construction_ and save/close world
5. Re-open world _Creative_ in Amulet to confirm the import was successful
6. Launch Minecraft, load world _Creative_
7. Fly around the imported area. At first, things load in fine but as you continue to fly around the game will eventually cease to render new chunks. Attempting to Save and Quit to Title will freeze the game. The game log will also output multiple errors.

**Screenshots**
Sample world _Hogwarts_ in Minecraft
![Untitled1](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/60878177/b073b70f-e543-432c-9fd7-419ae4c8bf30)

3D Selection being exported
![Untitled2](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/60878177/6870b76d-bff5-4d42-b270-3460ce39ea1b)

`.construction` file being imported
![Untitled3](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/60878177/7e8706e6-68eb-460b-9210-46e751e7bee6)

Reopen world to confirm import succeeded
![Untitled4](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/60878177/a32b7867-f311-45b4-b6fa-966d217868a9)

**Environment**
OS: Windows 10, Update 22H2
Minecraft Platform: Java
Minecraft Version: 1.18.2
Amulet Version: 0.10.25

**Additional context**
My client log can be found [here](https://github.com/Amulet-Team/Amulet-Map-Editor/files/13514095/latest.log)
The relevant portion is the following stacktrace:

```
[00:53:05] [Worker-Main-45/ERROR]: Caught exception in thread Thread[Worker-Main-45,10,main]
java.lang.NullPointerException: Cannot invoke "cqu.a(int, int, int)" because "$$2" is null
	at din.i(SourceFile:96) ~[din.class:?]
	at dil.c(SourceFile:143) ~[dil.class:?]
	at dik.a(DynamicGraphMinFixedPoint.java:170) ~[dik.class:?]
	at dih.a(SourceFile:129) ~[dih.class:?]
	at dio.a(SourceFile:45) ~[dio.class:?]
	at adz.a(SourceFile:135) ~[adz.class:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at adz.a(SourceFile:135) ~[adz.class:?]
	at adz.e(SourceFile:171) ~[adz.class:?]
	at adz.a(SourceFile:107) ~[adz.class:?]
	at adl.b(SourceFile:62) ~[adl.class:?]
	at avc.h(SourceFile:91) ~[avc.class:?]
	at avc.a(SourceFile:146) ~[avc.class:?]
	at avc.run(SourceFile:102) ~[avc.class:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

**World Files**
[Hogwarts.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/13514120/Hogwarts.zip)
[Creative.zip](https://drive.google.com/file/d/1TkVso_yO0wqP0ilWWYrIauRmmfWLr4bE/view)

**Comment by D3V1L0M3N** [comment]
Please note:

In the screenshots I provided. It is shown I'm importing the `.construction` file into a world called "Test". That was a fresh, blank 1.18.2 world. The import worked fine with zero issues in that world and did not cause the game to crash.

The issue was re-produced when attempting to import the `.construction` file into world "Creative". I just didn't take screenshots during that import and can't really be bothered wasting another 45 minutes running through it all over again for one picture.

However, as it may be relevant, here's a screenshot I did happen to take _after_ which shows the exact placing of the import into "Creative":
![Untitled5](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/60878177/0ef566f8-d0fa-46c0-9fb2-40d6e59a7354)

**Comment by D3V1L0M3N** [comment]
This issue seems to be related to:
https://github.com/Amulet-Team/Amulet-Map-Editor/issues/736

**Comment by gentlegiantJGC** [comment]
Looks like an issue with the lighting data.
`din.i` is `net.minecraft.world.level.lighting.LayerLightSectionStorage` `int getStoredLevel(long)`
`cqu.a` is `net.minecraft.world.level.chunk.DataLayer` `int get(int,int,int)`

**Comment by D3V1L0M3N** [comment]
Is there any way to resolve this issue myself? Through mods or similar? Or is this an issue that would require a fix be implemented by Amulet? I've seen there are mods/server plugins that can 'clean' up broken lighting, so curious if that's relevant.

**Comment by gentlegiantJGC** [comment]
Clearing the world cache data may solve the issue. I will need to look into what is actually causing it

**Comment by D3V1L0M3N** [comment]
I've just ran through the steps again after optimizing both worlds in Minecraft 1.18.2 and erasing cache. I'm afraid to report that it did not make any difference and the issue was reproduced exactly the same.

One thing I have forgotten to mention, though, is that the sample world "Creative" has been used in a Spigot 1.18.2 Server. The plugins used were mostly all functionality and not content-adding. Thought I should mention this as it could be relevant. If desired I can provide the list of plugins (total 17).
