### ISSUE TITLE
[Bug Report] can't find or open the save in bedrock

### ISSUE THREAD

**Issue by qwsaxsadad** [Amulet-Team/Amulet-Map-Editor#1018]
### Steps To Reproduce:
1.click on "open world"
2.click on the "bedrock"version in the left of the interface of "world select",and can't found my save in bedrock
3.click "open other world"
4.access the Archive Root Directory of bedrock Minecraft
5.click on the folder of the save and choose it
6.an error report:

-->

### Environment:

- OS: Windows11
- Minecraft bedrock
- Minecraft Version:1.20.51
- Amulet Version:v0.10.0b2

## Attachments
error report
Unsupported level.dat version 10
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\amulet_ui.py", line 183, in open_level
  File "amulet_map_editor\api\framework\pages\world_page.py", line 71, in __init__
  File "amulet\level\load.py", line 30, in load_level
  File "amulet\level\load.py", line 59, in load_format
  File "amulet\level\formats\leveldb_world\format.py", line 172, in __init__
  File "amulet\level\formats\leveldb_world\format.py", line 86, in from_file
  File "amulet\level\formats\leveldb_world\format.py", line 110, in _read_from
amulet.api.errors.ObjectReadError: Unsupported level.dat version 10

**Comment by qwsaxsadad** [comment]
other world in bedrock also cant open

**Comment by gentlegiantJGC** [comment]
You are using an outdated version of Amulet. Please update.
