### ISSUE TITLE
amulet_app can't be started under linux

### ISSUE THREAD

**Issue by flux242** [Amulet-Team/Amulet-Map-Editor#105]
> First of all you can use the program and tell us what you think.

I think that there's something wrong with the lib deps you put into the released zip file I got here https://github.com/Amulet-Team/Amulet-Map-Editor/releases/download/v0.7.0.1/Amulet-v0.7.0.1-linux.zip

first problem was the libz version mismatch.
```
$ ./amulet_app
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/wx/__init__.py", line 17, in <module>
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/wx/core.py", line 12, in <module>
ImportError: /home/alex/Downloads/Amulet/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
[3172028] Failed to execute script main
```
As I replaced that llib with the 1.2.11 version from my system [Ubuntu 20.04 64bit] I got this
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/wx/__init__.py", line 17, in <module>
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/wx/core.py", line 12, in <module>
ImportError: /home/alex/Downloads/Amulet/libwx_gtk3u_core-3.1.so.4: undefined symbol: gtk_widget_path_iter_set_object_name
[3180190] Failed to execute script main
```
Bwt there's AppImage format for things like that

**Comment by CrankySupertoon** [comment]
Its a bug with the version that ZLIB is linking with. It is linked for an LTS Version of ubuntu but doesnt work on anything newer or any arch based distros. I have to rewrite the full aur pacakge because of it.

**Comment by andrewathalye** [comment]
I'm not sure if it would make sense, but I think it might be better to have Linux users use the source package since that would be more likely to work with different system library versions. As long as pip is installed it should also be possible to install Amulet from that as well, I think.

**Comment by gentlegiantJGC** [comment]
We stopped releasing builds for linux instead pointing linux users to install from source.
Is this still an issue when installing from source?

**Comment by sausagemountain** [comment]
Trying to install, still getting the same errors. Unfortunately still an issue, no idea how to get around it though

**Comment by gentlegiantJGC** [comment]
The same issues as this report?

**Comment by sausagemountain** [comment]
Sorry, it was user error. I had an out of date version from Arch User Repositories. Latest version installed from pip launches fine
