### ISSUE TITLE
Chunks fail to load (any world)

### ISSUE THREAD

**Issue by kayawva** [Amulet-Team/Amulet-Map-Editor#1068]
**Current behaviour:**
When I load in any world in 3d view all chunks fail to load. Everything is empty besides building limits.

**Expected behaviour:**
Chunks would load in as usual.

**Steps to reproduce:**
Open any world

**Environment:**
- Windows 11, Version 10.0.22635 Build 22635
- Java
- Minecraft Version: 1.21
- Amulet Version: 0.10.32

**Additional context:**
This is what appears in powershell:
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('java', 3953)
ERROR - Error loading chunk -5 1 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 443, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 251, in _get_interface_and_translator
  File "amulet\level\formats\anvil_world\format.py", line 342, in _get_interface
  File "amulet\level\loader.py", line 62, in get
  File "amulet\level\loader.py", line 72, in identify
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('java', 3953)
ERROR - Error loading chunk -5 0 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 443, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 251, in _get_interface_and_translator
  File "amulet\level\formats\anvil_world\format.py", line 342, in _get_interface
  File "amulet\level\loader.py", line 62, in get
  File "amulet\level\loader.py", line 72, in identify
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('java', 3953)
ERROR - Error loading chunk -5 -1 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 443, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 251, in _get_interface_and_translator
  File "amulet\level\formats\anvil_world\format.py", line 342, in _get_interface
  File "amulet\level\loader.py", line 62, in get
  File "amulet\level\loader.py", line 72, in identify
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('java', 3953)
... etc

**Screenshots:**
![2024-06-21 15 15 45](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/173500361/c4929150-8056-4b20-899d-bd27ee606e76)

**Worlds:**
[Build Test.zip](https://github.com/user-attachments/files/15932426/Build.Test.zip)
(For me all of them do not work, but just as an example)

**Comment by gearus754** [comment]
The same problem.
Windows 10
Minecraft Java: 1.21 (Forge 51.0.8)
Amulet version: 0.10.32 also tested on older versions
--------------------- EDIT --------------------
Amulet Beta 0.10.33b0 seems to work.  :-)

**Comment by gentlegiantJGC** [comment]
Only the beta version currently supports 1.21.
