### ISSUE TITLE
[Bug Report] Can't open my world

### ISSUE THREAD

**Issue by ytggobs** [Amulet-Team/Amulet-Map-Editor#1072]
## Bug Report
I can't open my Java worlds
### Current Behaviour:
Gives an error

### Expected behavior:
It should have opened the world

### Environment:

- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.20.4
- Amulet Version: v0.10.33

## Attachments
module 'OpenGL_accelerate' has no attribute '__version_tuple__'
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\amulet_ui.py", line 157, in open_level
  File "amulet_map_editor\api\framework\pages\world_page.py", line 76, in __init__
  File "amulet_map_editor\api\framework\pages\world_page.py", line 101, in _load_extensions
  File "amulet_map_editor\api\framework\pages\world_page.py", line 37, in load_extensions
  File "amulet_map_editor\api\framework\pages\world_page.py", line 49, in load_extension
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "amulet_map_editor\programs\edit\__init__.py", line 4, in <module>
  File "amulet_map_editor\api\opengl\__init__.py", line 8, in check_opengl
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "OpenGL\GL\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "OpenGL\error.py", line 164, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "OpenGL\acceleratesupport.py", line 11, in <module>
AttributeError: module 'OpenGL_accelerate' has no attribute '__version_tuple__'

### Worlds
https://drive.google.com/file/d/1UY58syg9I5SaAcZNLFSLPRg_LiAdo6Pg/view?usp=drive_link

**Comment by gentlegiantJGC** [comment]
This happens when you extract the new version to the same directory as the old version without deleting the old version first.
Delete the whole folder and extract it again.

**Comment by ytggobs** [comment]
You mean to delete level_old.dat?

**Comment by gentlegiantJGC** [comment]
no. The Amulet directory.

**Comment by FeedTheChunk** [comment]
Delete Amulet and re-extract Amulet into a clean directory.

**Comment by ytggobs** [comment]
thanks
