### ISSUE TITLE
Numpy DLL could not be found

### ISSUE THREAD

**Issue by Hamza-nagori** [Amulet-Team/Amulet-Map-Editor#1076]
iam getting the error shown below 
Traceback (most recent call last):
  File "numpy\core\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "numpy\core\multiarray.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "numpy\core\overrides.py", line 8, in <module>
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "numpy\__init__.py", line 159, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "numpy\__config__.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "numpy\core\__init__.py", line 50, in <module>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\Administrator\Downloads\Amulet\amulet_app.exe"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Lib\site-packages\amulet_map_editor\__main__.py", line 98, in main
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "amulet_map_editor\__init__.py", line 27, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "amulet_map_editor\api\framework\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "amulet_map_editor\api\framework\app.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "amulet_map_editor\api\framework\amulet_ui.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "amulet\__init__.py", line 23, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "amulet\api\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "amulet\api\block.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "amulet_nbt\__init__.py", line 100, in <module>
  File "amulet_nbt\\_array.pyx", line 1, in init amulet_nbt._array
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "numpy\__init__.py", line 164, in <module>
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

Failed to import requirements. Check that you extracted correctly.
Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
Press ENTER to continue.

**Comment by gentlegiantJGC** [comment]
is this 0.10.35b0?
There is an issue in our build system that I need to fix.

**Comment by Hamza-nagori** [comment]
> is this 0.10.35b0? There is an issue in our build system that I need to fix.

i did'nt understood

**Comment by tajemniktv** [comment]
I have the same issue while trying to use Beta (0.10.35b0) for windows
Cheers

**Comment by CreeperAWA** [comment]
> is this 0.10.35b0? There is an issue in our build system that I need to fix.

I also have the same problem when using 0.10.35b0, it seems to be a packaging issue

**Comment by gund** [comment]
> is this 0.10.35b0? There is an issue in our build system that I need to fix.

Does this mean that previous builds work fine?

**Comment by gentlegiantJGC** [comment]
0.10.35b0 is broken. Do not use it.
0.10.33 works fine.

**Comment by gentlegiantJGC** [comment]
This should be fixed now.
