### ISSUE TITLE
[Bug Report] Amulet not loading textures

### ISSUE THREAD

**Issue by first63doc** [Amulet-Team/Amulet-Map-Editor#1091]
### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version:  1.21.2
- Amulet Version:  V0.10.35

### Additional context
 Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 152, in thread_setup
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 101, in get_java_vanilla_latest_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 65, in get_latest_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 58, in get_latest_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 24, in get_launcher_manifest
  File "urllib\request.py", line 214, in urlopen
  File "urllib\request.py", line 523, in open
  File "urllib\request.py", line 632, in http_response
  File "urllib\request.py", line 561, in error
  File "urllib\request.py", line 494, in _call_chain
  File "urllib\request.py", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

### Screenshots

![image](https://github.com/user-attachments/assets/682de46d-1bf6-444a-8808-4b1dc273da5a)

![image](https://github.com/user-attachments/assets/23eb2a07-9260-4cc9-bd9f-1a123148c869)

**Comment by JustSimplyDnaie** [comment]
I have had this issue too, the Java vanilla resource pack does not download on a new install of Amulet 0.10.35 for Windows. Here's my error tree:

Check your internet connection and restart Amulet.
Failed to download
Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 152, in thread_setup
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 101, in get_java_vanilla_latest_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 74, in get_latest_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 119, in _remove_and_download_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 211, in download_resources_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 176, in download_resources_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 149, in download_with_retry
RuntimeError: Failed to download

**Comment by gentlegiantJGC** [comment]
Amulet needs to access the mojang servers to download the resource pack. For some reason it was unable to do that.

**Comment by EvilSupahFly** [comment]
> Amulet needs to access the mojang servers to download the resource pack. For some reason it was unable to do that.

Does it do this on the fly each time at launch? I'm experiencing the same issue on Linux both with the Flatpak version and with the "normal" version. Output from my last run is in [my PasteBin](https://pastebin.com/sVYTc9wp) (it's a lot...).

**Comment by gentlegiantJGC** [comment]
It downloads it the first time and every time you open it it checks if there is a newer version. If there is it downloads it otherwise it does nothing.
Your log doesn't have any downloading issues.
It is having issues with water and lava which are not defined in the vanilla pack but should be in our vanilla fix pack.
Please can you open a new issue for this.

**Comment by Nodakmkz** [comment]
this problem happens here too

![Image](https://github.com/user-attachments/assets/b9b680c5-607d-4c86-8de3-3fd9decad234)

**Comment by gentlegiantJGC** [comment]
I think this issue was resolved recently by switching to HTTP
