### ISSUE TITLE
[Bug Report] Chunks not loading in version 10.36 after Minecraft update 1.21.2

### ISSUE THREAD

**Issue by PlasticBaller** [Amulet-Team/Amulet-Map-Editor#1109]
## Bug Report

Red chunk loading when updating to MC version 1.21.2

### Current Behavior:

Opening Amulet: after this update makes certain parts of my world not render showing red, however, the original spawn point shows the chunks as it should. But however, I go to a new area I been building in since 2017 or so is doing this red area. 

### Expected behavior:

Loads chunks rather than a big red area.

### Steps To Reproduce:

1. Install update to Minecraft to 1.21.2
2. Run Amulet latest 10.36
3. Move to certain areas ad they have some chunks not rendering
4. See Error (From Amulet's terminal)

amulet .api.errorsLoaderNoneMatched: Could not find a matching interface for ('java' , 4080)
Error - Error loading chuck ~419 ~89 Minecraft : overworld
Traceback 

### Environment:
- OS: Windows 10 64 Bit
- Minecraft Platform: Java 
- Minecraft Version: 1.21.2
- Amulet Version: 10.36

### Screenshots

<img width="1920" alt="2024-10-23 21_35_41-Greenshot" src="https://github.com/user-attachments/assets/019e9688-4ca6-48f0-9ea8-e8eac87b42f8">
<img width="1920" alt="2024-10-23 21_35_59-Greenshot" src="https://github.com/user-attachments/assets/f8def8cb-5250-4454-ad69-e41ccb14ab61">
<img width="1920" alt="2024-10-23 21_46_42-Greenshot" src="https://github.com/user-attachments/assets/87b512d0-18f2-4951-b3b5-7f6f2f88c8ad">

 It's mainly all red when I go from like 100, 100,100 for example, but like -6600, 100, -1234 does this red thing

### Worlds
It is a server I am editing that has worked fine like this until this recent update of MC. I use Fork it is not loaded.

**Comment by PlasticBaller** [comment]
Apparently they released a new version so soon!? 1.21.3 is now out checking into....

**Comment by PlasticBaller** [comment]
Update still the same as above in op.

**Comment by Cassidyhiro** [comment]
in Minecraft Bedrock is also having the same problem version 1.21.40/1.21.41

**Comment by Cassidyhiro** [comment]
in Minecraft Bedrock is also having the same problem version 1.21.41 / 1.21.40

**Comment by Cassidyhiro** [comment]
I have two hypotheses:
1) the amulet is defective
2) Mojang did this on purpose

**Comment by Podshot** [comment]
Amulet needs to be updated to support the 1.21.2/1.21.41 updates for Java and Bedrock edition, any worlds that have been opened in the new Minecraft version(s) will have chunks saved in a newer chunk format than Amulet supports so a new update supporting the format as well as new block definitions will need to be released.

@Cassidyhiro 
Amulet is neither defective nor was this issue made by Mojang on purpose, it is just what happens when a new Minecraft version is released. External tools (Amulet among many others) need to update to the new blocks and any changes in the world format that regularly accompany new Minecraft versions

**Comment by PlasticBaller** [comment]
@Podshot Yeah that's what I had figured as the update was a hot fix that was just badly timed lol. It happened so fast too! No conspiracy here aye

**Comment by Podshot** [comment]
Yeah, we don't support snapshots/beta versions so only when a new release/patch comes out do we update our format loaders and block definitions (mostly since changes are frequent and not finalized until the actual release). 

In this case no version of Amulet supported 1.21 yet so when the release (and subsequent patches) came out Amulet throws errors/red chunks. The speed of hotfixes didn't cause anything out of the ordinary for our update process, it just takes time for us to do an update and additional patches/hotfixes just means we have to check for any additional/new changes that might've been made which just causes a bit more of a delay

**Comment by PlasticBaller** [comment]
Thanks for the reply @Podshot, yeah I kind of let a little time between but I noticed it had suddenly changed and updated and didn't notice! I already had copied the new server over a few days ago.  lol

**Comment by Cassidyhiro** [comment]
@Podshot wow, that makes perfect sense, thank you very much for your explanation. I really didn't know about these characteristics of the amulet, as it had never occurred to me before. Thanks again for clearing my doubts :)

**Comment by DeepCoreII** [comment]
I am new to Amulet, but I have heard nothing but great things about it so far.  I tried it for the first time yesterday on Bedrock 1.21.41 and the entire world is grey and red blocks in Amulet.

I know you are working on the problem, but I thought more info may be helpful.

Side Question - Whether in 2D or 3D mode, my world is displayed at an angle.  Is there a way to view it from directly above like a map?

Many thanks and good luck!  :D

![image](https://github.com/user-attachments/assets/64704719-1713-4c96-a19f-4eaa94bee2e6)

Here is text from the Console.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 174, in create_geometry
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 91, in chunk
  File "amulet\api\level\base_level\base_level.py", line 582, in get_chunk
  File "amulet\api\level\base_level\chunk_manager.py", line 192, in get_chunk
  File "amulet\api\history\history_manager\database.py", line 157, in _get_entry
  File "amulet\api\history\history_manager\database.py", line 166, in _get_register_original_entry
  File "amulet\api\level\base_level\chunk_manager.py", line 196, in _raw_get_entry
  File "amulet\api\wrapper\format_wrapper.py", line 462, in load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 448, in _safe_load
amulet.api.errors.ChunkLoadError: Could not find a leveldb interface for chunk version 41
ERROR - Error loading chunk -29 -8 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 443, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 251, in _get_interface_and_translator
  File "amulet\level\formats\leveldb_world\format.py", line 300, in _get_interface
  File "amulet\level\formats\leveldb_world\interface\chunk\__init__.py", line 32, in get_interface
amulet.api.errors.LoaderNoneMatched: Could not find a leveldb interface for chunk version 41
INFO - Error loading chunk (-29, -8)
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 443, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 251, in _get_interface_and_translator
  File "amulet\level\formats\leveldb_world\format.py", line 300, in _get_interface
  File "amulet\level\formats\leveldb_world\interface\chunk\__init__.py", line 32, in get_interface
amulet.api.errors.LoaderNoneMatched: Could not find a leveldb interface for chunk version 41

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 174, in create_geometry
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 91, in chunk
  File "amulet\api\level\base_level\base_level.py", line 582, in get_chunk
  File "amulet\api\level\base_level\chunk_manager.py", line 192, in get_chunk
  File "amulet\api\history\history_manager\database.py", line 157, in _get_entry
  File "amulet\api\history\history_manager\database.py", line 166, in _get_register_original_entry
  File "amulet\api\level\base_level\chunk_manager.py", line 196, in _raw_get_entry
  File "amulet\api\wrapper\format_wrapper.py", line 462, in load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 448, in _safe_load
amulet.api.errors.ChunkLoadError: Could not find a leveldb interface for chunk version 41

**Comment by gentlegiantJGC** [comment]
0.10.37 is being built which should fix these issues.
