### ISSUE TITLE
When I run the latest Amulet 0.10.38 I get "module 'OpenGL_accelerate' has no attribute '__version_tuple__'"

### ISSUE THREAD

**Issue by SquaresWalkersGIT** [Amulet-Team/Amulet-Map-Editor#1121]
When I load any Minecraft Bedrock world, 1.21.4x or 1.21.50 world I get this during the loading process.

module 'OpenGL_accelerate' has no attribute '__version_tuple__'
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\amulet_ui.py", line 157, in open_level
  File "amulet_map_editor\api\framework\pages\world_page.py", line 76, in __init__
  File "amulet_map_editor\api\framework\pages\world_page.py", line 101, in _load_extensions
  File "amulet_map_editor\api\framework\pages\world_page.py", line 37, in load_extensions
  File "amulet_map_editor\api\framework\pages\world_page.py", line 49, in load_extension
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "amulet_map_editor\programs\edit\__init__.py", line 4, in <module>
  File "amulet_map_editor\api\opengl\__init__.py", line 8, in check_opengl
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "OpenGL\GL\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "OpenGL\error.py", line 164, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "OpenGL\acceleratesupport.py", line 11, in <module>
AttributeError: module 'OpenGL_accelerate' has no attribute '__version_tuple__'

### Expected behavior:
to load the world

### Steps To Reproduce:
1. Open Amulet
2. Select any world
3. error is shown above

### Environment:
- OS: Windows 11 Home 23H2 build 22631.4541
- Minecraft Bedrock | Minecraft Bedrock Dedicated Server File
- Minecraft Version: 1.21.4x (last run in 1.21.4x) or new run in 1.21.50 | MBDS again backup from 1.21.4x and updated current running, 1.21.50
- Amulet Version: 0.10.38 but also 0.10.37

### Additional context
Trying to remove chunks for 1.21.50 world gen

It happens on multiple worlds, smallest one too big to upload

**Comment by gentlegiantJGC** [comment]
This happens when you don't delete the old version before extracting the new version.

**Comment by SquaresWalkersGIT** [comment]
thanks will do that

**Comment by SquaresWalkersGIT** [comment]
Issue resolved thanks
