### ISSUE TITLE
macOS Big Sur (11.x): Unable to load OpenGL library

### ISSUE THREAD

**Issue by Avakining** [Amulet-Team/Amulet-Map-Editor#226]
**Describe the bug**

Steps to reproduce the behaviour:
1. Install Amulet on Mac (virtual environment or not)
2. Run Amulet
3. Open any world (vanilla, fabric, forge, any supported version)
4. Only "Convert" and "About" tabs appear

**Expected behavior**
A tab with the 3D editor also appears

**Screenshots**
<img width="1094" alt="Screen Shot 2021-03-23 at 14 49 30 EDT" src="https://user-images.githubusercontent.com/25210618/112201801-00ad5d80-8be7-11eb-8365-bb5dfc27f50f.png">
<img width="107" alt="Screen Shot 2021-03-23 at 14 49 26 EDT" src="https://user-images.githubusercontent.com/25210618/112201805-030fb780-8be7-11eb-87c5-df878dd0ba4f.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Version 8.1.b1

**Additional context**
<details>
  <summary>There are these error messages in Terminal:</summary>

```
Traceback (most recent call last):
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/platform/darwin.py", line 35, in GL
    return ctypesloader.loadLibrary(
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/platform/ctypesloader.py", line 36, in loadLibrary
    return _loadLibraryWindows(dllType, name, mode)
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/platform/ctypesloader.py", line 89, in _loadLibraryWindows
    return dllType( name, mode )
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ('dlopen(OpenGL, 10): image not found', 'OpenGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cdp/amulet/lib/python3.9/site-packages/amulet_map_editor/api/framework/pages/world_page.py", line 44, in load_extension
    module = importlib.import_module(module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/cdp/amulet/lib/python3.9/site-packages/amulet_map_editor/programs/edit/__init__.py", line 1, in <module>
    from amulet_map_editor.programs.edit.edit import EditExtension
  File "/Users/cdp/amulet/lib/python3.9/site-packages/amulet_map_editor/programs/edit/edit.py", line 12, in <module>
    from amulet_map_editor.programs.edit.api.canvas.edit_canvas import EditCanvas
  File "/Users/cdp/amulet/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/__init__.py", line 2, in <module>
    from .canvas import EditCanvas
  File "/Users/cdp/amulet/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/canvas/__init__.py", line 1, in <module>
    from .edit_canvas import EditCanvas
  File "/Users/cdp/amulet/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/canvas/edit_canvas.py", line 5, in <module>
    from .base_edit_canvas import BaseEditCanvas
  File "/Users/cdp/amulet/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py", line 3, in <module>
    from OpenGL.GL import (
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/platform/__init__.py", line 36, in <module>
    _load()
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/platform/__init__.py", line 33, in _load
    plugin.install(globals())
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 97, in install
    namespace[ name ] = getattr(self,name,None)
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/platform/darwin.py", line 62, in GetCurrentContext
    return self.CGL.CGLGetCurrentContext
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/platform/darwin.py", line 45, in CGL
    def CGL(self): return self.GL
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/cdp/amulet/lib/python3.9/site-packages/OpenGL/platform/darwin.py", line 41, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', 'dlopen(OpenGL, 10): image not found', 'OpenGL', None)
```
  
</details>

**Comment by gentlegiantJGC** [comment]
Have a read through of this and see if it fixes your issue.
https://github.com/PixarAnimationStudios/USD/issues/1372

**Comment by Avakining** [comment]
Yes, that fixes it.

**Comment by gentlegiantJGC** [comment]
I am going to reopen this so that people can find the solution and it doesn't get reported again.
Once it gets fixed in PyOpenGL I will close this.

**Comment by gentlegiantJGC** [comment]
The next build should fix this issue.
If it is still an issue in the next build please reopen this issue and let me know.
