### ISSUE TITLE
DragAcceptFiles(): cannot use DragAcceptFiles() and SetDropTarget() together

### ISSUE THREAD

**Issue by jimbt** [Amulet-Team/Amulet-Map-Editor#239]
**Describe the bug**
After starting amulet-map-editor, selecting a map (bedrock 1.16), and selecting the 3D Editor tab the world doesn't render.

**To Reproduce**
1. Select a world (bedrock 1.16 in my case)
2. Click the 3D Editor tab
3. The world doesn't render, but the text "Setting up renderer" and ui controls are visible.
4. See error on the console
2021-03-29 17:53:58,678 - amulet_map_editor - INFO - Finished setting up texture atlas in OpenGL
Traceback (most recent call last):
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/api/framework/pages/world_page.py", line 117, in _page_change
    self._extensions[self.GetSelection()].enable()
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/programs/edit/edit.py", line 84, in enable
    self._canvas.enable()
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/programs/edit/api/canvas/edit_canvas.py", line 124, in enable
    self._tool_sizer.enable()
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/programs/edit/api/ui/tool_manager.py", line 83, in enable
    self.canvas.reset_bound_events()
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/api/opengl/canvas/event_canvas.py", line 19, in reset_bound_events
    self.bind_events()
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/programs/edit/api/canvas/edit_canvas.py", line 116, in bind_events
    self._tool_sizer.bind_events()
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/programs/edit/api/ui/tool_manager.py", line 60, in bind_events
    self._active_tool.bind_events()
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 257, in bind_events
    super().bind_events()
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/programs/edit/api/ui/tool/default_base_tool_ui.py", line 44, in bind_events
    self.canvas.DragAcceptFiles(True)
wx._core.wxAssertionError: C++ assertion "!GetDropTarget()" failed at /home/wxpy/wxPython-4.1.1/ext/wxWidgets/src/common/wincmn.cpp(3647) in DragAcceptFiles(): cannot use DragAcceptFiles() and SetDropTarget() together

**Expected behavior**
The world renders.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux - Debian 10
 - Amulet Version: 0.8.2+

**Additional context**
This problem exists since amulet-map-editor version 0.8.2 including the latest dev build: 0.8.3b0.dev202103290706.  Version 0.8.1 does not have this issue, but it is unable to use wxPython 4.1.1 (stuck on 4.1.0).

**Comment by jimbt** [comment]
Version 0.8.2a7 is the first version (available from PyPI) where the problem occurs.

**Comment by gentlegiantJGC** [comment]
Adding this line may fix the issue
`self.canvas.SetDropTarget(None)`

**Comment by jimbt** [comment]
This did resolve the error on version 0.8.3a4.

Specifically, I edited 'amulet_map_editor/programs/edit/api/ui/tool/default_base_tool_ui.py' and inserted 'self.canvas.SetDropTarget(None)' as line 44.

**Comment by gsbowlin** [comment]
I'm also running this from master on Linux (Ubuntu 20.04), and after setting the Drop Target, It looks like I'm getting an Open GL issue.

I'm also running from master


The traceback starts in 

"Amulet-Map-Editor/amulet_map_editor/programs/edit/plugins/tools/select.py", line 345, in _on_draw
    self.canvas.renderer.draw_sky_box()

And ends with an OpenGL error
OpenGL.error.Error: Attempt to retrieve context when no valid context

The error then repeats for what looks like the rest of the drawing sections. 

Amulet-Map-Editor/amulet_map_editor/programs/edit/plugins/tools/select.py", line 348, in _on_draw
    self._selection.draw()

Amulet-Map-Editor/amulet_map_editor/programs/edit/plugins/tools/select.py", line 347, in _on_draw
    self.canvas.renderer.draw_level()

..etc for several screens.

**Comment by gentlegiantJGC** [comment]
@gsbowlin please create a new issue

**Comment by jimbt** [comment]
This is fixed in version 0.8.3b2.
