### ISSUE TITLE
3D Editor Doesn't Work on macOS

### ISSUE THREAD

**Issue by kyleplo** [Amulet-Team/Amulet-Map-Editor#246]
**Describe the bug**

**To Reproduce**
Open any world, and the 3D editor tab doesn't even show up

**Expected behavior**
I would like to be able to use the 3D editor

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur (Intel)
 - Amulet Version: Latest Stable

**Additional context**
There was some stuff in the console:
```
2021-04-05 18:44:35,024 - amulet_core - INFO - Loading level /Users/<Username>/Library/Application Support/minecraft/saves/<worldName>
2021-04-05 18:44:35,111 - amulet_map_editor - WARNING - Failed to import amulet_map_editor.programs.edit.
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/OpenGL/platform/darwin.py", line 38, in GL
    mode=ctypes.RTLD_GLOBAL
  File "/Library/Python/3.7/site-packages/OpenGL/platform/ctypesloader.py", line 36, in loadLibrary
    return _loadLibraryWindows(dllType, name, mode)
  File "/Library/Python/3.7/site-packages/OpenGL/platform/ctypesloader.py", line 89, in _loadLibraryWindows
    return dllType( name, mode )
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ('dlopen(OpenGL, 10): image not found', 'OpenGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<Username>/Library/Python/3.7/lib/python/site-packages/amulet_map_editor/api/framework/pages/world_page.py", line 44, in load_extension
    module = importlib.import_module(module_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/<Username>/Library/Python/3.7/lib/python/site-packages/amulet_map_editor/programs/edit/__init__.py", line 1, in <module>
    from amulet_map_editor.programs.edit.edit import EditExtension
  File "/Users/<Username>/Library/Python/3.7/lib/python/site-packages/amulet_map_editor/programs/edit/edit.py", line 12, in <module>
    from amulet_map_editor.programs.edit.api.canvas.edit_canvas import EditCanvas
  File "/Users/<Username>/Library/Python/3.7/lib/python/site-packages/amulet_map_editor/programs/edit/api/__init__.py", line 2, in <module>
    from .canvas import EditCanvas
  File "/Users/<Username>/Library/Python/3.7/lib/python/site-packages/amulet_map_editor/programs/edit/api/canvas/__init__.py", line 1, in <module>
    from .edit_canvas import EditCanvas
  File "/Users/<Username>/Library/Python/3.7/lib/python/site-packages/amulet_map_editor/programs/edit/api/canvas/edit_canvas.py", line 5, in <module>
    from .base_edit_canvas import BaseEditCanvas
  File "/Users/<Username>/Library/Python/3.7/lib/python/site-packages/amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py", line 3, in <module>
    from OpenGL.GL import (
  File "/Library/Python/3.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Library/Python/3.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Library/Python/3.7/site-packages/OpenGL/platform/__init__.py", line 36, in <module>
    _load()
  File "/Library/Python/3.7/site-packages/OpenGL/platform/__init__.py", line 33, in _load
    plugin.install(globals())
  File "/Library/Python/3.7/site-packages/OpenGL/platform/baseplatform.py", line 97, in install
    namespace[ name ] = getattr(self,name,None)
  File "/Library/Python/3.7/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Library/Python/3.7/site-packages/OpenGL/platform/darwin.py", line 62, in GetCurrentContext
    return self.CGL.CGLGetCurrentContext
  File "/Library/Python/3.7/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Library/Python/3.7/site-packages/OpenGL/platform/darwin.py", line 45, in CGL
    def CGL(self): return self.GL
  File "/Library/Python/3.7/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Library/Python/3.7/site-packages/OpenGL/platform/darwin.py", line 41, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', 'dlopen(OpenGL, 10): image not found', 'OpenGL', None)
```

**Comment by gentlegiantJGC** [comment]
Please see #226
