### ISSUE TITLE
OpenGL - Attempt to retrieve context when no valid context

### ISSUE THREAD

**Issue by jimbt** [Amulet-Team/Amulet-Map-Editor#247]
**Describe the bug**
The 3D world view is unable to render with wxPython 4.1.1.  wxPython 4.1.0 is fine.

**To Reproduce**
1. Open world
2. Go to 3D Editor
3. World does not render.  World view is just blue.
4. See repeating console errors
5. Close world

**Expected behavior**
World renders as with wxPython 4.1.0.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux - Debian 10
 - Versions -
   - Amulet: 0.8.3a5
   - Python: 3.7.3
   - wxPython package: 4.1.1

**Additional context**
Including as far back as the Amulet 0.8.0 betas, I don't know of a version that has worked with wxPython 4.1.1.

> 2021-04-10 15:52:19,128 - amulet_map_editor - INFO - ('en_US', 'UTF-8')
2021-04-10 15:52:19,128 - amulet_map_editor - INFO - ('en_US', 'UTF-8')
2021-04-10 15:52:28,509 - amulet_core - INFO - Loading level /opt/share/Minecraft/BedrockUniverse/Backup/202101090324/worlds/test
15:52:30: Debug: Adding duplicate image handler for 'Windows bitmap file'
15:52:30: Debug: Adding duplicate animation handler for '1' type
15:52:30: Debug: Adding duplicate animation handler for '2' type
2021-04-10 15:52:50,351 - minecraft_model_reader - INFO - Downloading java launcher manifest file.
2021-04-10 15:52:50,628 - minecraft_model_reader - INFO - Finished downloading java launcher manifest file.
2021-04-10 15:52:52,795 - amulet_map_editor - INFO - Finished setting up texture atlas in OpenGL
Traceback (most recent call last):
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 345, in _on_draw
    self.canvas.renderer.draw_sky_box()
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/programs/edit/api/renderer.py", line 240, in draw_sky_box
    self.sky_box.draw(self.canvas.camera.transformation_matrix)
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/api/opengl/mesh/sky_box.py", line 66, in draw
    transformation_matrix, displacement_matrix(*self._camera_location)
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/api/opengl/mesh/tri_mesh.py", line 153, in draw
    self._setup()
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/api/opengl/mesh/tri_mesh.py", line 92, in _setup
    self._setup_opengl_attrs()
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/amulet_map_editor/api/opengl/mesh/tri_mesh.py", line 108, in _setup_opengl_attrs
    ctypes.c_void_p(attr_start * 4),
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/OpenGL/latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 469, in glVertexAttribPointer
    contextdata.setValue( key, array )
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
  File "/opt/pythonEnv/amuletMapEditor/lib/python3.7/site-packages/OpenGL/contextdata.py", line 41, in getContext
    """Attempt to retrieve context when no valid context"""
OpenGL.error.Error: Attempt to retrieve context when no valid context
**... (Above error repeats - 45 in just a few seconds)**
2021-04-10 15:53:25,778 - amulet_core - INFO - Removing cache.`

**Comment by jimbt** [comment]
The current full release generates the same error with wxPython 4.1.1.

With wxPython 4.1.0, the world renders as expected for Amulet versions 0.8.2 and 0.8.3a5.  The workaround/fix from #239 is also required since it occurs first.

**Comment by Cebtenzzre** [comment]
Since wxPython 4.1.1, the bundled wxWidgets includes commit wxWidgets/wxWidgets@7cd12a2bd6566b36be5579a370b52ac18f986863 (PR wxWidgets/wxWidgets#2038). As a result, wxWidgets is built for EGL instead of GLX at compile time. This breaks Amulet because PyOpenGL defaults to GLX on Linux. The solution is to set `PYOPENGL_PLATFORM=egl`, either via the command line (`PYOPENGL_PLATFORM=egl python -m amulet_map_editor`) or somewhere in the code (`os.environ['PYOPENGL_PLATFORM'] = 'egl'`).

 See wxWidgets/Phoenix#1923 for related discussion.

**Comment by jimbt** [comment]
The 'PYOPENGL_PLATFORM=egl' environment variable does resolve the issue with wxPython 4.1.1 on Amulet 8.4.

Also, the 'GDK_BACKEND=x11' environment variable is now technically not required, but the mouse becomes so erratic and sensitive for view control that it isn't usable.  I'll keep this setting for now to use the XWayland emulation layer.

**Comment by uiytt** [comment]
```PYOPENGL_PLATFORM=egl python -m amulet_map_editor``` solved the problem for me with wxPython 4.1.1 and Amulet 8.5 
The world load without problems.
Unfortunately the GUI is flickering (cords, cut, etc..) 
There is no error nowhere (not in the console nor the logs)

**Comment by gentlegiantJGC** [comment]
Has anyone tried setting the environment variable from within python? Does this work for everyone?
If so I will look into adding it.

**Comment by uiytt** [comment]
I can confirm that when I added 
`os.environ['PYOPENGL_PLATFORM'] = 'egl'` in the __init__.py of amulet, the problem doesn't happen anymore :tada:
