### ISSUE TITLE
Error loading mca files with size < 4096 bytes

### ISSUE THREAD

**Issue by MinecraftPlaye** [Amulet-Team/Amulet-Map-Editor#25]
I cannot open a world (world size: 4.19GB, Minecraft Version: 1.15.2 [Vanilla]). Another 18.9gb world does not work, too. Other 1.15.2 worlds work fine, thought they are smaller (MB instead of GB) which is why I assume it might be a problem with the world size. 

I've tested Amulet v0.5.1 and v0.6.2 on Windows 10 x64 1903 (and Linux via Wine).

Console output:
```
2020-04-12 01:02:58,105 - amulet_core - INFO - Loading world C:\Users\XYZ\AppData\Roaming\.minecraft\saves\world
Traceback (most recent call last):
  File "amulet_map_editor\amulet_wx\world_select.py", line 106, in _call_callback
    self.open_world_callback(self.path)
  File "amulet_map_editor\amulet_wx\world_select.py", line 277, in _update_recent
    self._open_world_callback(path)
  File "amulet_map_editor\amulet_wx\world_select.py", line 307, in _run_callback
    self._open_world_callback(path)
  File "amulet_map_editor\amulet_ui.py", line 128, in _open_world
    world = WorldManagerUI(self.world_tab_holder, path)
  File "amulet_map_editor\plugins\programs\__init__.py", line 68, in __init__
    self.world = world_interface.load_world(path)
  File "amulet\world_interface\__init__.py", line 20, in load_world
    return World(directory, load_format(directory, _format, forced))
  File "amulet\api\world.py", line 93, in __init__
    self._world_wrapper.open()
  File "C:\Users\XYZ\Downloads\Amulet-v0.6.2-windows\Amulet\amulet\world_interface\formats\anvil\anvil_format.py", line 441, in open
    self._reload_world()
  File "C:\Users\XYZ\Downloads\Amulet-v0.6.2-windows\Amulet\amulet\world_interface\formats\anvil\anvil_format.py", line 428, in _reload_world
    0: AnvilLevelManager(self._world_path, mcc=mcc)
  File "C:\Users\XYZ\Downloads\Amulet-v0.6.2-windows\Amulet\amulet\world_interface\formats\anvil\anvil_format.py", line 273, in __init__
    mcc=self._mcc,
  File "C:\Users\XYZ\Downloads\Amulet-v0.6.2-windows\Amulet\amulet\world_interface\formats\anvil\anvil_format.py", line 59, in __init__
    offsets = numpy.fromfile(fp, dtype=">u4", count=1024).reshape(32, 32)
ValueError: cannot reshape array of size 0 into shape (32,32)
```

**Comment by gentlegiantJGC** [comment]
The error is due to some mca files with size less than 1024 bytes. I will get this fixed but a quick fix on your end is to delete all of the region files that have 0 size

**Comment by gentlegiantJGC** [comment]
Should be fixed in the next release.

https://github.com/Amulet-Team/Amulet-Core/commit/c9c664ffda5c79f6cc5b54b962434c0729850a52
