### ISSUE TITLE
Can not run on macOS Mojave

### ISSUE THREAD

**Issue by MikeDoes** [Amulet-Team/Amulet-Map-Editor#283]
First of all, thanks a lot for doing this project. 

**Has this bug already been reported? Please check if there is a bug report already open that matches this.**
No, it has not

**Describe the bug**
I just want to run amulet to try it out because it sounds promising but there is an error because it iterates through something that it shouldn't. See error at the end as well as pip list. 

**To Reproduce**
1. Create virtual environment env and activate it
2. pip3 install amulet-map-editor --upgrade
3. python3 -m amulet_map_editor

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - macOS Mojave

**Additional context**
```
/Users/michael/Pictures/tutorial-env/bin/python3: can't open file '/Users/michael/Pictures/amulet_map_editor': [Errno 2] No such file or directory
(tutorial-env) (base) Michaels-MacBook-Pro:Pictures michael$ python3 -m amulet_map_editor
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/michael/Pictures/tutorial-env/lib/python3.9/site-packages/amulet_map_editor/__init__.py", line 7, in <module>
    from amulet_map_editor.api import config as CONFIG, log, lang
  File "/Users/michael/Pictures/tutorial-env/lib/python3.9/site-packages/amulet_map_editor/api/lang.py", line 100, in <module>
    register_lang_directory(
  File "/Users/michael/Pictures/tutorial-env/lib/python3.9/site-packages/amulet_map_editor/api/lang.py", line 61, in register_lang_directory
    if "_" in _language:
TypeError: argument of type 'NoneType' is not iterable
```

Pip List:
Package                 Version
----------------------- -------
amulet-core             1.2.5
amulet-map-editor       0.8.4
amulet-nbt              1.0.3.8
Cython                  0.29.23
minecraft-resource-pack 1.2.1
numpy                   1.20.2
Pillow                  8.2.0
pip                     20.2.3
PyMCTranslate           1.0.2
PyOpenGL                3.1.5
setuptools              49.2.1
six                     1.16.0
wxPython                4.1.1

**Comment by gentlegiantJGC** [comment]
Looks like this is returning `None` on your system

https://docs.python.org/3/library/locale.html#locale.getdefaultlocale
