### ISSUE TITLE
Error - python -m pip install -r requirements.txt

### ISSUE THREAD

**Issue by THBTX** [Amulet-Team/Amulet-Map-Editor#29]
I've run the command:
python -m pip install -r requirements.txt

And received the following output:
Collecting git+git://github.com/Amulet-Team/Amulet-Core.git (from -r requirements.txt (line 4))
  Cloning git://github.com/Amulet-Team/Amulet-Core.git to c:\users\charley\appdata\local\temp\pip-req-build-yadjlrap
  Running command git clone -q git://github.com/Amulet-Team/Amulet-Core.git 'C:\Users\Charley\AppData\Local\Temp\pip-req-build-yadjlrap'

And then the following errors (long):
   ERROR: Command errored out with exit status 1:
     command: 'D:\Dev\Python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Charley\\AppData\\Local\\Temp\\pip-req-build-yadjlrap\\setup.py'"'"'; __file__='"'"'C:\\Users\\Charley\\AppData\\Local\\Temp\\pip-req-build-yadjlrap\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Charley\AppData\Local\Temp\pip-req-build-yadjlrap\pip-egg-info'
         cwd: C:\Users\Charley\AppData\Local\Temp\pip-req-build-yadjlrap\
    Complete output (95 lines):
    Processing numpy/random\_bounded_integers.pxd.in
    Processing numpy/random\mtrand.pyx
    Traceback (most recent call last):
      File "C:\Users\Charley\AppData\Local\Temp\easy_install-f6yavy6e\numpy-1.18.2\tools\cythonize.py", line 61, in process_pyx
        from Cython.Compiler.Version import version as cython_version
    ModuleNotFoundError: No module named 'Cython'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Charley\AppData\Local\Temp\easy_install-f6yavy6e\numpy-1.18.2\tools\cythonize.py", line 238, in <module>
        main()
      File "C:\Users\Charley\AppData\Local\Temp\easy_install-f6yavy6e\numpy-1.18.2\tools\cythonize.py", line 234, in main
        find_process_files(root_dir)
      File "C:\Users\Charley\AppData\Local\Temp\easy_install-f6yavy6e\numpy-1.18.2\tools\cythonize.py", line 225, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "C:\Users\Charley\AppData\Local\Temp\easy_install-f6yavy6e\numpy-1.18.2\tools\cythonize.py", line 191, in process
        processor_function(fromfile, tofile)
      File "C:\Users\Charley\AppData\Local\Temp\easy_install-f6yavy6e\numpy-1.18.2\tools\cythonize.py", line 66, in process_pyx
        raise OSError('Cython needs to be installed in Python as a module')
    OSError: Cython needs to be installed in Python as a module
    Running from numpy source directory.
    C:\Users\Charley\AppData\Local\Temp\easy_install-f6yavy6e\numpy-1.18.2\setup.py:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Traceback (most recent call last):
      File "D:\Dev\Python\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "D:\Dev\Python\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "D:\Dev\Python\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "D:\Dev\Python\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\Charley\AppData\Local\Temp\easy_install-f6yavy6e\numpy-1.18.2\setup.py", line 488, in <module>
      File "C:\Users\Charley\AppData\Local\Temp\easy_install-f6yavy6e\numpy-1.18.2\setup.py", line 469, in setup_package
      File "C:\Users\Charley\AppData\Local\Temp\easy_install-f6yavy6e\numpy-1.18.2\setup.py", line 275, in generate_cython
    RuntimeError: Running cythonize failed!

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Charley\AppData\Local\Temp\pip-req-build-yadjlrap\setup.py", line 70, in <module>
        setup(
      File "D:\Dev\Python\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "D:\Dev\Python\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "D:\Dev\Python\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "D:\Dev\Python\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "D:\Dev\Python\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "D:\Dev\Python\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "D:\Dev\Python\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "D:\Dev\Python\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "D:\Dev\Python\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "D:\Dev\Python\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "D:\Dev\Python\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "D:\Dev\Python\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "D:\Dev\Python\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "D:\Dev\Python\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "D:\Dev\Python\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "D:\Dev\Python\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "D:\Dev\Python\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "D:\Dev\Python\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "D:\Dev\Python\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "D:\Dev\Python\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "D:\Dev\Python\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "D:\Dev\Python\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "D:\Dev\Python\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\Charley\AppData\Local\Temp\easy_install-f6yavy6e\numpy-1.18.2\setup.py", line 488, in <module>
      File "C:\Users\Charley\AppData\Local\Temp\easy_install-f6yavy6e\numpy-1.18.2\setup.py", line 469, in setup_package
      File "C:\Users\Charley\AppData\Local\Temp\easy_install-f6yavy6e\numpy-1.18.2\setup.py", line 275, in generate_cython
    RuntimeError: Running cythonize failed!
    Cythonizing sources
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Podshot** [comment]
Looks like the dynamic cython installation for amulet_nbt is failing, try installing amulet_nbt from the pre-compiled releases found [here](https://github.com/Amulet-Team/Amulet-NBT/releases/tag/1.0.3) and then try running the command again

**Comment by THBTX** [comment]
OK, now I'm dumb.  D/L amulet_nbt-1.0.3-cp37-cp37m-win_amd64.whl.  Extracted it, but not seeing which file to try to install.

**Comment by Podshot** [comment]
Run `pip install amulet_nbt-1.0.3-cp37-cp37m-win_amd64.whl`

**Comment by THBTX** [comment]
Received the following error on my my Windows 10 Home (X64-based PC) attempt:

D:\Dev\Amulet-Map-Editor-0.6.2>pip install amulet_nbt-1.0.3-cp37-cp37m-win_amd64.whl
ERROR: amulet_nbt-1.0.3-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

**Comment by Podshot** [comment]
That's not the issue, amd64 means that it's for 64 bit machines, what version of python and pip do you have installed?

**Comment by THBTX** [comment]
> That's not the issue, `amd64` means that it's for 64 bit machines, what version of python and pip do you have installed?
Python 3.8.2
pip 20.0.2 from d:\dev\python\lib\site-packages\pip (python 3.8)

**Comment by Podshot** [comment]
We haven't tested amulet or any of the required modules with Python 3.8 so I would suggest downgrading your Python version to 3.7.6 and trying everything again. 

Another issue may be the python installation, so when you re-install Python, run the `python` command in Command Prompt and make sure it says that a 64 bit version of python has been installed

**Comment by THBTX** [comment]
Will downgrade and try again.  Running the 64-bit version of 3.8.2.

**Comment by THBTX** [comment]
Just three warnings now when running python -m pip install -r requirements.txt:

  WARNING: Missing build requirements in pyproject.toml for git+git://github.com/Amulet-Team/Amulet-NBT.git (from -r requirements.txt (line 5)).
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by Podshot** [comment]
Those errors can be ignored for the time being
