### ISSUE TITLE
macOS Big Sur (11.3.1): GLError Invalid Operation

### ISSUE THREAD

**Issue by Compsogbrickus** [Amulet-Team/Amulet-Map-Editor#293]
**Describe the bug**
Attempting to open any world in Amulet does not display the world and instead spams an error in the console. The error is:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 359, in _on_draw
    self._selection.draw()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/amulet_map_editor/programs/edit/api/behaviour/block_selection_behaviour.py", line 523, in draw
    super().draw()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/amulet_map_editor/programs/edit/api/behaviour/pointer_behaviour.py", line 106, in draw
    self._pointer.draw(self.canvas.camera.transformation_matrix)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/amulet_map_editor/api/opengl/mesh/selection/box/render_selection.py", line 257, in draw
    glPushAttrib(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glPushAttrib,
	cArguments = (8456,)
)
```

Note that the second to last line is sometimes instead `cArguments = (264,)`.

**To Reproduce**
1. Install Amulet on Mac.
2. Patch PyOpenGL as explained in #226.
3. Run Amulet with Python 3.8.
4. Open any world.
5. The world is not shown.

**Expected behavior**
The 3D editor renders the world.

**Screenshots**
<img width="1792" alt="Screen Shot 2021-05-13 at 12 35 12 PM" src="https://user-images.githubusercontent.com/17102273/118156878-dce8e580-b3e7-11eb-90f3-d1fa80ea98b2.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.3.1
 - Version 0.8.4

**Additional context**
This issue may be similar to #42.

**Comment by gentlegiantJGC** [comment]
This version should solve that issue.
https://pypi.org/project/amulet-map-editor/0.8.5b0.dev202105100717/

**Comment by Compsogbrickus** [comment]
That works perfectly. Issue resolved.
