### ISSUE TITLE
Bedrock to Java converstion 

### ISSUE THREAD

**Issue by Crimzon2638** [Amulet-Team/Amulet-Map-Editor#3]
When I tried to convert a world from 1.14.1 bedrock to java 1.14, it didn't convert well, even after trying to load the chunks, the logs sent this error. 
"NotImplementedError
2020-02-12 00:51:02,695 - amulet_core - ERROR - Error loading chunk 32 29
Traceback (most recent call last):
  File "lib\site-packages\amulet\world_interface\formats\__init__.py", line 161, in load_chunk
  File "lib\site-packages\amulet\world_interface\formats\__init__.py", line 196, in _load_chunk
  File "C:\Users\vip\Desktop\Amulet-Converter-V0.1\Amulet-Converter\amulet\world_interface\chunk\interfaces\leveldb\base_leveldb_interface.py", line 112, in decode
    chunk.blocks, palette = self._load_subchunks(subchunks)
  File "C:\Users\vip\Desktop\Amulet-Converter-V0.1\Amulet-Converter\amulet\world_interface\chunk\interfaces\leveldb\base_leveldb_interface.py", line 267, in _load_subchunks
    raise NotImplementedError
NotImplementedError" 

This is how the conversion looked like at the end, [https://cdn.discordapp.com/attachments/343783861609562113/676805470966644754/unknown.png](url)

**Comment by gentlegiantJGC** [comment]
The old numerical chunk format has not been implemented for Bedrock yet. I should add a better error until it is added.
