### ISSUE TITLE
Conversion from 1.16.5 to 1.13.2 fails

### ISSUE THREAD

**Issue by Podshot** [Amulet-Team/Amulet-Map-Editor#326]
**Describe the bug**
After converting a 1.16.5 world to 1.13.2, the conversion successfully completes and the converted world can be opened in both Amulet and NBTExplorer (to confirm the conversion worked successfully) and shows the new world. However, once opening the world in Minecraft 1.13.2, the world is reset to it's initial state before the conversion process.

**To Reproduce**
1. Download the world from ~~here~~ _(Pending permission to re-upload and host the world file)_
2. Convert the downloaded world to 1.13.2 (I use the default superflat world type as the destination world)
3. Open the 1.13.2 world in Minecraft
4. Minecraft logs errors about not being able to read chunks and the world regenerates to be a superflat world

**Expected behavior**
The converted world is properly opened in Minecraft with the converted data still in place

**Screenshots**
Source world before conversion (1.16.5):
![Before Conversion (1.16.5)](https://user-images.githubusercontent.com/4026610/121834023-b1ce0c00-cc9b-11eb-89ff-3d7f72a5610a.PNG)

Source world after conversion (1.13.2 in Amulet):
![bug_2](https://user-images.githubusercontent.com/4026610/121834041-c7433600-cc9b-11eb-8e16-dd6681493900.PNG)

Destination world opened in Minecraft 1.13.2:
![2021-06-13_23 03 38](https://user-images.githubusercontent.com/4026610/121834059-d2966180-cc9b-11eb-87c3-cb851345ae18.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 20H2
 - Amulet Version: v0.8.8

**Additional context**
My client log can be found [here](https://drive.google.com/file/d/1un94Cf4Ldb_aEmDK1HQAUUb-wwU0cm45/view)
The relevant portion is the following stacktrace:
```
[13:45:44] [Server thread/ERROR]: Couldn't load chunk
java.lang.IllegalArgumentException: The value 0 is not in the specified inclusive range of 1 to 32
	at org.apache.commons.lang3.Validate.inclusiveBetween(Validate.java:1032) ~[commons-lang3-3.5.jar:3.5]
	at xd.<init>(SourceFile:19) ~[1.13.2.jar:?]
	at bnq.a(SourceFile:177) ~[1.13.2.jar:?]
	at bnv.a(SourceFile:680) ~[1.13.2.jar:?]
	at bnv.a(SourceFile:496) ~[1.13.2.jar:?]
	at bnv.a(SourceFile:189) ~[1.13.2.jar:?]
	at bnv.a(SourceFile:141) ~[1.13.2.jar:?]
	at tc.a(SourceFile:102) [1.13.2.jar:?]
	at tc.a(SourceFile:146) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:429) [1.13.2.jar:?]
	at dgh.a(SourceFile:92) [1.13.2.jar:?]
	at dgh.d(SourceFile:108) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:566) [1.13.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

Another similar stacktrace happens later on in the log file:
```
[13:46:09] [WorldGen-Scheduler-1/ERROR]: Couldn't load protochunk
java.lang.IllegalArgumentException: The value 0 is not in the specified inclusive range of 1 to 32
	at org.apache.commons.lang3.Validate.inclusiveBetween(Validate.java:1032) ~[commons-lang3-3.5.jar:3.5]
	at xd.<init>(SourceFile:19) ~[1.13.2.jar:?]
	at bnq.a(SourceFile:177) ~[1.13.2.jar:?]
	at bnv.a(SourceFile:680) ~[1.13.2.jar:?]
	at bnv.a(SourceFile:496) ~[1.13.2.jar:?]
	at bnv.a(SourceFile:189) ~[1.13.2.jar:?]
	at bnv.b(SourceFile:208) ~[1.13.2.jar:?]
	at bnv.b(SourceFile:165) ~[1.13.2.jar:?]
	at tx.a(SourceFile:59) [1.13.2.jar:?]
	at tx$$Lambda$1571/1534326904.apply(Unknown Source) [1.13.2.jar:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.computeIfAbsent(Long2ObjectOpenHashMap.java:479) [fastutil-8.2.1.jar:?]
	at tx.a(SourceFile:54) [1.13.2.jar:?]
	at tx.a(SourceFile:25) [1.13.2.jar:?]
	at acu.b(SourceFile:80) [1.13.2.jar:?]
	at acu$a.a(SourceFile:143) [1.13.2.jar:?]
	at acu$a$$Lambda$1580/238605253.accept(Unknown Source) [1.13.2.jar:?]
	at bnd$1.a(SourceFile:46) [1.13.2.jar:?]
	at bnd$1.a(SourceFile:27) [1.13.2.jar:?]
	at acu$a.a(SourceFile:143) [1.13.2.jar:?]
	at acu$a$$Lambda$1579/1907483732.apply(Unknown Source) [1.13.2.jar:?]
	at java.util.Map.computeIfAbsent(Map.java:957) [?:1.8.0_51]
	at acu$a.a(SourceFile:137) [1.13.2.jar:?]
	at acu$a.a(SourceFile:143) [1.13.2.jar:?]
	at acu$a$$Lambda$1580/238605253.accept(Unknown Source) [1.13.2.jar:?]
	at bnd.a(SourceFile:105) [1.13.2.jar:?]
	at bnd.a(SourceFile:22) [1.13.2.jar:?]
	at acu$a.a(SourceFile:143) [1.13.2.jar:?]
	at acu$a$$Lambda$1579/1907483732.apply(Unknown Source) [1.13.2.jar:?]
	at java.util.Map.computeIfAbsent(Map.java:957) [?:1.8.0_51]
	at acu$a.a(SourceFile:137) [1.13.2.jar:?]
	at acu$a.a(SourceFile:143) [1.13.2.jar:?]
	at acu$a$$Lambda$1580/238605253.accept(Unknown Source) [1.13.2.jar:?]
	at bnd.a(SourceFile:105) [1.13.2.jar:?]
	at bnd.a(SourceFile:22) [1.13.2.jar:?]
	at acu$a.a(SourceFile:143) [1.13.2.jar:?]
	at acu$a$$Lambda$1579/1907483732.apply(Unknown Source) [1.13.2.jar:?]
	at java.util.Map.computeIfAbsent(Map.java:957) [?:1.8.0_51]
	at acu$a.a(SourceFile:137) [1.13.2.jar:?]
	at acu$a.a(SourceFile:143) [1.13.2.jar:?]
	at acu$a$$Lambda$1580/238605253.accept(Unknown Source) [1.13.2.jar:?]
	at bnd.a(SourceFile:105) [1.13.2.jar:?]
	at bnd.a(SourceFile:22) [1.13.2.jar:?]
	at acu$a.a(SourceFile:143) [1.13.2.jar:?]
	at acu$a$$Lambda$1579/1907483732.apply(Unknown Source) [1.13.2.jar:?]
	at java.util.Map.computeIfAbsent(Map.java:957) [?:1.8.0_51]
	at acu$a.a(SourceFile:137) [1.13.2.jar:?]
	at acu$a.a(SourceFile:115) [1.13.2.jar:?]
	at acu.a(SourceFile:61) [1.13.2.jar:?]
	at acu$$Lambda$1567/954628552.get(Unknown Source) [1.13.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by gentlegiantJGC** [comment]
can I get a copy of the world to play around with

**Comment by gentlegiantJGC** [comment]
Okay this does not look like an isolated issue. I have tried with one of my worlds and the game also throws those chunks

**Comment by gentlegiantJGC** [comment]
Sadly the obfuscation maps are not available this far back. I have worked a little bit out by comparing the sources to a newer version.
```
[13:45:44] [Server thread/ERROR]: Couldn't load chunk
java.lang.IllegalArgumentException: The value 0 is not in the specified inclusive range of 1 to 32
	at org.apache.commons.lang3.Validate.inclusiveBetween(Validate.java:1032) ~[commons-lang3-3.5.jar:3.5]
	at xd.<init>(SourceFile:19) ~[1.13.2.jar:?]
	at PalettedContainer.write(SourceFile:177) ~[1.13.2.jar:?]
	at ChunksSerializer.write(SourceFile:680) ~[1.13.2.jar:?]
	at bnv.a(SourceFile:496) ~[1.13.2.jar:?]
	at bnv.a(SourceFile:189) ~[1.13.2.jar:?]
	at bnv.a(SourceFile:141) ~[1.13.2.jar:?]
	at tc.a(SourceFile:102) [1.13.2.jar:?]
	at tc.a(SourceFile:146) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:429) [1.13.2.jar:?]
	at dgh.a(SourceFile:92) [1.13.2.jar:?]
	at dgh.d(SourceFile:108) [1.13.2.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:566) [1.13.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by gentlegiantJGC** [comment]
I think I may have found the issue.
The 1.16.5 code (which I am comparing it to) first checks if `"Palette"` and `"BlockStates"` exist in the chunk. If they do it then loads the chunk data.
The 1.13.2 code just assumes they exist. The get long array method in their NBT library will return an empty long array if one does not exist which is where the zero length array is coming from.
So I think all the data that we have written is perfectly fine. The issue is that we have some sections that do not contain an array.

**Comment by gentlegiantJGC** [comment]
I have written some code to remove the empty sections for the old versions and it looks like it opens in game.

**Comment by gentlegiantJGC** [comment]
![image](https://user-images.githubusercontent.com/11940194/122682202-fbfd4300-d1ef-11eb-8fac-5eff2bb5396a.png)
