### ISSUE TITLE
Unable to Handle Bukkit Datapack 

### ISSUE THREAD

**Issue by bman354** [Amulet-Team/Amulet-Map-Editor#333]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**
N

**Describe the bug**
Trying to open world_nether or world_the_end in a spigot server causes amulet to attempt to read the bukkit datapack and is unable to open the dimension.

**To Reproduce**
1. Go to amulet
2. Click on world_nether to load it
3. Amulet is unable to load the world due to an invalid path to /bukkit

**Expected behavior**
Amulet should open the nether dimension for editing

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
Additional Context and screenshots in discord

**Comment by gentlegiantJGC** [comment]
Can you add a link to the world files

**Comment by bman354** [comment]
[SkyblockEdit.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/6688266/SkyblockEdit.zip)

**Comment by neonerz** [comment]
Can confirm. If a world has a datapack associated to it, opening it up in Amulet throws an error. You either have to create the folder structure to match the datapack or open the world first with the client.

**Comment by Tsoccerguy3** [comment]
The given path G:\1.17 sanacraft\GoldenCity\datapacks\bukkit is not valid.
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\amulet_ui.py", line 168, in _open_world
  File "amulet_map_editor\api\framework\pages\world_page.py", line 80, in __init__
  File "amulet\level\load.py", line 30, in load_level
  File "amulet\api\level\world.py", line 14, in __init__
  File "amulet\api\level\base_level\base_level.py", line 57, in __init__
  File "amulet\api\wrapper\format_wrapper.py", line 328, in open
  File "amulet\level\formats\anvil_world\format.py", line 398, in _open
  File "amulet\level\formats\anvil_world\format.py", line 375, in _reload_world
  File "amulet\level\formats\anvil_world\format.py", line 247, in _register_dimension
  File "amulet\level\formats\anvil_world\format.py", line 171, in data_pack
  File "amulet\level\formats\anvil_world\data_pack\data_pack.py", line 157, in is_path_valid
  File "amulet\level\formats\anvil_world\data_pack\data_pack.py", line 133, in _open_wrapper
FileNotFoundError: The given path G:\1.17 sanacraft\GoldenCity\datapacks\bukkit is not valid.
