### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by UlmerPride** [Amulet-Team/Amulet-Map-Editor#357]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**
Upon clicking 3d editor, I get the followig error:
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 132, in _page_change
  File "amulet_map_editor\programs\edit\edit.py", line 50, in enable
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 92, in __init__
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 79, in __init__
PermissionError: [Errno 13] Permission denied: 'resource_packs/readme.txt'
I don't think there's even a resource_packs/readme.txt in the folder that I've selected, and afterward it never loads, all I get is the "world is loading" text

**To Reproduce**
honestly the editor seems to be working for most of you so...

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version:  20H2

**Comment by gentlegiantJGC** [comment]
The newest beta has a popup for this. Try moving Amulet to somewhere else on your computer.
#308
