### ISSUE TITLE
Double stone slab conversion error

### ISSUE THREAD

**Issue by tpaulet-web** [Amulet-Team/Amulet-Map-Editor#36]
I'm getting an error while loading a world.

```
2020-05-09 11:44:45,761 - pymctranslate - ERROR - Error converting block minecraft:double_stone_slab[block_data=13] to universal in PyMCTranslate.Version(java, (1, 12, 2)).
2020-05-09 11:44:45,761 - pymctranslate - ERROR - Error and traceback from the above "No output object given."
Traceback (most recent call last):
  File "PyMCTranslate\py3\versions\translation_database.py", line 46, in _translate
    pre_populate_defaults
  File "PyMCTranslate\py3\versions\translate.py", line 284, in translate
    raise Exception("No output object given.")
Exception: No output object given.
```

**Comment by gentlegiantJGC** [comment]
As far as I can see that isn't a valid block

**Comment by gentlegiantJGC** [comment]
Should be fixed in the next build
