### ISSUE TITLE
v0.8.9 - TypeError: __array__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by BenjaminHoegh** [Amulet-Team/Amulet-Map-Editor#363]
OS: Windows 10
Amulet version: 0.8.9

```
__array__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 155, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 51, in enable
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 101, in setup
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 99, in _setup
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 196, in _setup
  File "amulet_map_editor\api\opengl\resource_pack\resource_pack.py", line 134, in setup
TypeError: __array__() takes 1 positional argument but 2 were given
```

**Comment by gentlegiantJGC** [comment]
Thanks. This should be fixed by #364 
I have just put out 0.8.10 with the fix.
