### ISSUE TITLE
'LevelName' does not exist in level.dat

### ISSUE THREAD

**Issue by Londiuh** [Amulet-Team/Amulet-Map-Editor#37]
When I click the "Open World" button, nothing happens and this error shows in the console.
I have a dual python installation so maybe it's launching this with python 2 or something.
````
2020-05-10 22:03:57,871 - amulet_map_editor - INFO - Could not find a matching format for C:\Users\Dennis\AppData\Roaming\.minecraft\saves\lol
Traceback (most recent call last):
  File "amulet_map_editor\amulet_ui.py", line 218, in _show_world_select
    select_world = WorldSelectWindow(self, self._open_world_callback)
  File "amulet_map_editor\amulet_wx\world_select.py", line 301, in __init__
    self.world_select = WorldSelectAndRecentUI(self, self._run_callback)
  File "amulet_map_editor\amulet_wx\world_select.py", line 273, in __init__
    self.add_object(WorldSelectUI(self, self._update_recent), 2, wx.ALL | wx.EXPAND)
  File "amulet_map_editor\amulet_wx\world_select.py", line 207, in __init__
    self.content = ScrollableWorldsUI(self, open_world_callback)
  File "amulet_map_editor\amulet_wx\world_select.py", line 174, in __init__
    self.reload()
  File "amulet_map_editor\amulet_wx\world_select.py", line 184, in reload
    world_list = CollapseableWorldListUI(self, glob.glob(os.path.join(directory, '*')), group_name, self.open_world_callback)
  File "amulet_map_editor\amulet_wx\world_select.py", line 153, in __init__
    open_world_callback
  File "amulet_map_editor\amulet_wx\world_select.py", line 124, in __init__
    world_button = WorldUIButton(self, world_format, open_world_callback)
  File "amulet_map_editor\amulet_wx\world_select.py", line 95, in __init__
    world_format
  File "amulet_map_editor\amulet_wx\world_select.py", line 79, in __init__
    world_format.world_name,
  File "C:\Users\Dennis\Documents\Dennis\Programas\Amulet\amulet\world_interface\formats\anvil\anvil_format.py", line 389, in world_name
    return self.root_tag["Data"]["LevelName"].value
  File "amulet_nbt\amulet_cy_nbt.pyx", line 546, in amulet_nbt.amulet_cy_nbt._TAG_Compound.__getitem__
KeyError: 'LevelName'
````

**Comment by gentlegiantJGC** [comment]
I have had this error reported recently. It should be fixed in the next build

**Comment by Londiuh** [comment]
> I have had this error reported recently. It should be fixed in the next build

You know why it's happening or a temp-fix?

**Comment by gentlegiantJGC** [comment]
There is a world it is finding in your save folder that it doesn't like. I would like to know what format the world is but I don't know which world it is.

If you apply these changes on that file in your install it should fix it and let you know which world is at fault.

https://github.com/Amulet-Team/Amulet-Map-Editor/commit/150bb52299b3df0190363efa4295a14e3dc848f0

**Comment by gentlegiantJGC** [comment]
Please can you try out the new version and let me know what the console says. It should say an error about a world which will be what was causing it to crash before.

https://github.com/Amulet-Team/Amulet-Map-Editor/releases/tag/v0.6.6.1

**Comment by Londiuh** [comment]
It says this error:
```
2020-05-18 08:41:43,650 - amulet_map_editor - INFO - Could not find loader for C:\Users\Dennis\AppData\Roaming\.minecraft\saves\lol Could not find a matching format for C:\Users\Dennis\AppData\Roaming\.minecraft\saves\lol
2020-05-18 08:41:43,895 - amulet_core - INFO - Format.world_path is depreciated. Please used Format.pathTraceback (most recent call last):
  File "amulet_map_editor\amulet_wx\world_select.py", line 128, in __init__
    world_button = WorldUIButton(self, world_format, open_world_callback)
  File "amulet_map_editor\amulet_wx\world_select.py", line 95, in __init__
    world_format
  File "amulet_map_editor\amulet_wx\world_select.py", line 79, in __init__
    world_format.world_name,
  File "C:\Users\Dennis\Desktop\Amulet\amulet\world_interface\formats\anvil\anvil_format.py", line 389, in world_name
    return self.root_tag["Data"]["LevelName"].value
  File "amulet_nbt\amulet_cy_nbt.pyx", line 546, in amulet_nbt.amulet_cy_nbt._TAG_Compound.__getitem__
KeyError: 'LevelName'

2020-05-18 08:41:43,895 - amulet_map_editor - INFO - Failed to display world button for C:\Users\Dennis\AppData\Roaming\.minecraft\saves\World1 'LevelName'
```
Now the worlds window pop-ups, but the worlds that cause this error aren't in the world list.

**Comment by gentlegiantJGC** [comment]
That is expected. Send over the level.dat files for those worlds

**Comment by gentlegiantJGC** [comment]
@Londiuh can you send over the level.dat file for that world so I can investigate it

**Comment by gentlegiantJGC** [comment]
If you have a world example that produces the same issue please reopen this issue and send over the world so I can investigate
