### ISSUE TITLE
Program fails to run subsystem and closes tabs

### ISSUE THREAD

**Issue by Redkitt3n14** [Amulet-Team/Amulet-Map-Editor#402]
**Describe the bug**
Tried to convert world to bedrock and tabs shut themselves after 2 errors

**To Reproduce**
1. I selected java world and went to convert tab
2. selected bedrock world to convert to, did NOT press convert
3. go to 3d edit tab - currently says loading java textures
4. when the bar reaches the end received error 1 (below)
5. followed by error 2 (below)
6. 3d edit and convert tabs shut leaving only about tab

**Expected behavior**
I expected to be able to convert the world from java to bedrock

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows10home 21H1
 - Version: release 0.8.12

**Additional context**
I installed the program 20 min ago - first time user

The bug did not happen when run as administrator - managed to convert my world properly (unlike corrupt chunks with mcc tool chest :)

Error 1:
C++ assertion "IsShown()" failed at ..\..\src\common\glcmn.cpp(84) in wxGLCanvasBase::SetCurrent(): can't make hidden GL canvas current
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 155, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 84, in enable
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 123, in enable
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 229, in enable
wx._core.wxAssertionError: C++ assertion "IsShown()" failed at ..\..\src\common\glcmn.cpp(84) in wxGLCanvasBase::SetCurrent(): can't make hidden GL canvas current

Error 2:
wrapped C/C++ object of type Gauge has been deleted
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 155, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 53, in enable
RuntimeError: wrapped C/C++ object of type Gauge has been deleted

**Comment by ErrorBot1122** [comment]
Still a bug

**Comment by gentlegiantJGC** [comment]
The bug has been fixed in 0.10 but that version has not been released yet.

**Comment by ErrorBot1122** [comment]
oh, tnx
