### ISSUE TITLE
Resource packs decide they don't want to be downloaded or manually loaded/acknowledged in 3D View

### ISSUE THREAD

**Issue by jayhawker6** [Amulet-Team/Amulet-Map-Editor#419]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**
A few similar reports but not on this exact issue.
**Describe the bug**
Amulet 3D renderer is unable to download the latest Java texture pack. When opening worlds and attempting to use the 3d viewer it will pull that error. It will not display textures even when manually given a resource pack from 1.17.x in the resource packs folder under Amulet. The only things that render are pink and black (no texture) chests, banners, anvils and some hoppers that are covered on all sides by any blocks. It also does not acknowledge in any way that you gave it a compatible texture pack to load in the resource pack folder.
**To Reproduce**
1. Go to 'Amulet Map editor'
2. Click on '3D View'
3. Wait for it to try and get Java textures
5. groan in agony, and realize that it isn't trying to load the textures you put in the resource pack file as well.

**Expected behavior**
Rendering the 3D view

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Tried on [Windows Education(Equivalent to Server+Pro), Windows home, and Windows Pro]
 - Version [Varying. All on current update with most current drivers, all connected to internet, and all with proper libraries installed to function]

**Additional context**
- Same results when run as admin.
- Same result when compiled from source with all python libraries and visual C++ from visual studio or on pre-compiled version.

**Comment by jayhawker6** [comment]
![image](https://user-images.githubusercontent.com/75534911/133631149-cf436acb-828d-4d93-bc00-f099368b04ff.png)
**Log:**
``` Bash
2021-09-16 09:06:53,036 - amulet_core - INFO - Loading level C:\Users\344agg21\Downloads\Entropy
2021-09-16 09:06:58,754 - minecraft_model_reader - INFO - Downloading java launcher manifest file.
2021-09-16 09:06:58,864 - amulet_map_editor - ERROR - Check your internet connection and restart Amulet.
Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 160, in _setup
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 99, in get_java_vanilla_latest_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 63, in get_latest_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 56, in get_latest_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 25, in get_launcher_manifest
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 641, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
2021-09-16 09:07:06,074 - amulet_map_editor - INFO - Finished setting up texture atlas in OpenGL
2021-09-16 09:07:17,401 - pymctranslate - WARNING - Could not find translation information for block minecraft:chalkboard[__version__=17760256,direction=0] to universal in PyMCTranslate.Version(bedrock, (1, 14, 0)). If this is not a vanilla block ignore this message
2021-09-16 09:07:23,028 - pymctranslate - WARNING - Could not find translation information for block minecraft:chalkboard[__version__=17760256,direction=1] to universal in PyMCTranslate.Version(bedrock, (1, 14, 0)). If this is not a vanilla block ignore this message
2021-09-16 09:07:23,828 - pymctranslate - WARNING - Could not find translation information for block minecraft:chalkboard[__version__=17760256,direction=0] from universal in PyMCTranslate.Version(java, (1, 17, 0)). If this is not a vanilla block ignore this message
```

**Comment by gentlegiantJGC** [comment]
This has caused a number of issues in the past.
We should add better support for when the resource pack fails to download.
Perhaps we could bounce the user to the browser to download it there and then get the user to select the downloaded file.
Not ideal but there should be a workaround for this issue.

**Comment by jayhawker6** [comment]
Also manually gave it textures in an accessible and even local relative file path, still gave the exact same error. It appears as if it might be trying to download default textures before even checking to see if one is already set or given.

**Comment by andycode2009** [comment]
When I open the world and click the 3d editor, then it says failed to download  the latest java vanilla resource pack
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py", line 152, in thread_setup
    yield next(gen) * 0.4 + 0.1
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minecraft_model_reader/api/resource_pack/java/download_resources.py", line 101, in get_java_vanilla_latest_iter
    _java_vanilla_latest = yield from get_latest_iter()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minecraft_model_reader/api/resource_pack/java/download_resources.py", line 65, in get_latest_iter
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minecraft_model_reader/api/resource_pack/java/download_resources.py", line 58, in get_latest_iter
    new_version = get_launcher_manifest()["latest"]["release"]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/minecraft_model_reader/api/resource_pack/java/download_resources.py", line 24, in get_launcher_manifest
    with urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)>

it seems like a SSL error ,maybe bad network environment will cause it
or the certificate is outdated?
I use macOS 15.2 ,is there anyway to solve it?

**Comment by gentlegiantJGC** [comment]
Did you run the certeficates file in the python directory?

**Comment by andycode2009** [comment]
/Applications/Python\ 3.10/Install\ Certificates.command 
It works!Thankyou!
