### ISSUE TITLE
Mac OS OpenGL "invalid framebuffer operation"

### ISSUE THREAD

**Issue by Eilux** [Amulet-Team/Amulet-Map-Editor#42]
When selecting world conversion or the world editor all that is shown is a blank screen. The log shows nothing when selecting the editor and displays the following error when selecting conversion: 

```
Traceback (most recent call last):
  File "/Users/jack/amulet/Amulet-Map-Editor/amulet_map_editor/programs/edit/canvas/canvas.py", line 381, in _on_draw
    self.draw()
  File "/Users/jack/amulet/Amulet-Map-Editor/amulet_map_editor/programs/edit/canvas/canvas.py", line 385, in draw
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
  File "/Users/jack/amulet/Amulet-Map-Editor/venv/lib/python3.8/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
	err = 1286,
	description = b'invalid framebuffer operation',
	baseOperation = glClear,
	cArguments = (16640,)
)
```

**Comment by gentlegiantJGC** [comment]
Please confirm if this is still an issue in the latest release.
