### ISSUE TITLE
New build system does not bake the requirements

### ISSUE THREAD

**Issue by sajones** [Amulet-Team/Amulet-Map-Editor#429]
I am seeing the following error whenever Amulet attempts to load one of my worlds.

```
2021-09-24 01:49:01,917 - amulet_core - ERROR - Error loading chunk -11 65 minecraft:overworld
Traceback (most recent call last):
  File "/home/user/.virtualenvs/mcbeedit/lib/python3.7/site-packages/amulet/api/wrapper/format_wrapper.py", line 433, in _safe_load
    return meth(*args)
  File "/home/user/.virtualenvs/mcbeedit/lib/python3.7/site-packages/amulet/api/wrapper/format_wrapper.py", line 481, in _load_chunk
    interface, dimension, cx, cz, raw_chunk_data
  File "/home/user/.virtualenvs/mcbeedit/lib/python3.7/site-packages/amulet/level/formats/leveldb_world/format.py", line 242, in _decode
    return interface.decode(cx, cz, raw_chunk_data, (bounds[0][1], bounds[1][1]))
  File "/home/user/.virtualenvs/mcbeedit/lib/python3.7/site-packages/amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py", line 111, in decode
    chunk.blocks, chunk_palette = self._load_subchunks(subchunks)
  File "/home/user/.virtualenvs/mcbeedit/lib/python3.7/site-packages/amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py", line 397, in _load_subchunks
    raise Exception(f"sub-chunk version {data[0]} is not known.")
Exception: sub-chunk version 9 is not known.
```

The world save is from Bedrock Dedicated Server version 1.17.31.01
Amulet version: v0.8.13

The error is reported any time Amulet attempts to process a chunk that was altered since the world was upgraded from 1.17.11. In the Amulet UI, the affected chunks appear to be void chunks with a red overlay over them.

**Comment by gentlegiantJGC** [comment]
It looks like your version of Amulet-Core is out of date. I thought I changed something so that it always pulled the current version at release time.

**Comment by gentlegiantJGC** [comment]
Okay it looks like I did fix this but we recently switched to using a library called `build` to create the sdist and wheel releases which broke this.

**Comment by sajones** [comment]
Thank you, manually updating amulet-core did the trick and I was able to successfully open the world save in question. Should I leave the issue open to track the build issue that led to this?

**Comment by gentlegiantJGC** [comment]
Yes. I had a look into fixing it but haven't gotten it working yet.

**Comment by JonTabor** [comment]
I was seeing this issue too, and I can confirm that manually updating amulet-core (python -m pip install amulet-core) worked for me as well.
