### ISSUE TITLE
Fails to read some Bedrock chunks during conversion

### ISSUE THREAD

**Issue by Moilleadoir** [Amulet-Team/Amulet-Map-Editor#447]
**Description**
Converting a Bedrock 1.17.40.06 world to Java 1.17.1 leaves some chunks empty leading to a mix of Java and Bedrock generation.

**To Reproduce**
1. Open Bedrock world
2. Choose 1.17.1 world as target
3. Click _Convert_
4. Open world in Java MC to see mixed terrain

**Expected behavior**
The converted world should contain all of the source world’s chunks.

**Output**
Run from a terminal most of the chunks are OK but there are also a lot of chunk load errors that I didn’t see at first.  Unfortunately I didn’t redirect to a log file, but I think they’re all the same kind of thing.  I have no more time today to run this conversion again, but I can give you a full output if needed.
```
2021-10-27 18:23:45,107 - amulet_core - ERROR - Error loading chunk 83 -7 minecraft:overworld
Traceback (most recent call last):
  File "/home/sean/bin/amulet/.venv/lib/python3.9/site-packages/amulet/api/wrapper/format_wrapper.py", line 433, in _safe_load
    return meth(*args)
  File "/home/sean/bin/amulet/.venv/lib/python3.9/site-packages/amulet/api/wrapper/format_wrapper.py", line 480, in _load_chunk
    chunk, chunk_palette = self._decode(
  File "/home/sean/bin/amulet/.venv/lib/python3.9/site-packages/amulet/level/formats/leveldb_world/format.py", line 242, in _decode
    return interface.decode(cx, cz, raw_chunk_data, (bounds[0][1], bounds[1][1]))
  File "/home/sean/bin/amulet/.venv/lib/python3.9/site-packages/amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py", line 111, in decode
    chunk.blocks, chunk_palette = self._load_subchunks(subchunks)
  File "/home/sean/bin/amulet/.venv/lib/python3.9/site-packages/amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py", line 397, in _load_subchunks
    raise Exception(f"sub-chunk version {data[0]} is not known.")
Exception: sub-chunk version 9 is not known.
2021-10-27 18:23:45,107 - amulet_core - INFO - Error loading chunk 83 -7
Traceback (most recent call last):
  File "/home/sean/bin/amulet/.venv/lib/python3.9/site-packages/amulet/api/wrapper/format_wrapper.py", line 433, in _safe_load
    return meth(*args)
  File "/home/sean/bin/amulet/.venv/lib/python3.9/site-packages/amulet/api/wrapper/format_wrapper.py", line 480, in _load_chunk
    chunk, chunk_palette = self._decode(
  File "/home/sean/bin/amulet/.venv/lib/python3.9/site-packages/amulet/level/formats/leveldb_world/format.py", line 242, in _decode
    return interface.decode(cx, cz, raw_chunk_data, (bounds[0][1], bounds[1][1]))
  File "/home/sean/bin/amulet/.venv/lib/python3.9/site-packages/amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py", line 111, in decode
    chunk.blocks, chunk_palette = self._load_subchunks(subchunks)
  File "/home/sean/bin/amulet/.venv/lib/python3.9/site-packages/amulet/level/interfaces/chunk/leveldb/base_leveldb_interface.py", line 397, in _load_subchunks
    raise Exception(f"sub-chunk version {data[0]} is not known.")
Exception: sub-chunk version 9 is not known.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sean/bin/amulet/.venv/lib/python3.9/site-packages/amulet/api/level/base_level/base_level.py", line 460, in save_iter
    chunk = self.level_wrapper.load_chunk(cx, cz, dimension)
  File "/home/sean/bin/amulet/.venv/lib/python3.9/site-packages/amulet/api/wrapper/format_wrapper.py", line 452, in load_chunk
    return self._safe_load(
  File "/home/sean/bin/amulet/.venv/lib/python3.9/site-packages/amulet/api/wrapper/format_wrapper.py", line 438, in _safe_load
    raise load_error(e)
amulet.api.errors.ChunkLoadError: sub-chunk version 9 is not known.
2021-10-27 18:23:45,108 - amulet_core - INFO - Converting chunk minecraft:overworld -184, -351
```

**Screenshots**
![2021-10-27_17 22 28](https://user-images.githubusercontent.com/1229543/139013223-83ec7ec9-f590-49ed-9eee-aeff3094b91d.jpg)
I think the water in this image is what would generate in Java with the same (Bedrock) seed. I used that to create the target Java world.

Roughly the same view in Bedrock.
![2021-10-27 17-45-56 Bedrock](https://user-images.githubusercontent.com/1229543/139014258-6a28db06-57cf-47dd-af66-96b2a3ce6158.jpg)

Same position in newly generated Java world with same seed.
![2021-10-27_18 06 08](https://user-images.githubusercontent.com/1229543/139016939-05ae08d1-0269-4931-9f54-dca060166a23.jpg)

**Desktop:**
 - Manjaro Linux, Cinnamon desktop

**Comment by Moilleadoir** [comment]
Most of the important stuff converted, but Amulet still missed some chunks.
