### ISSUE TITLE
Unable to convert Java 1.18 to Bedrock 1.18

### ISSUE THREAD

**Issue by mikezimm** [Amulet-Team/Amulet-Map-Editor#474]
**Describe the bug**
I have a Java 1.17 world that I pruned using MCA.  Then reloaded in 1.18 Java and verified all works.
Then when I try to use Amulet to convert from Java to Bedrock, I get all errors.

## Here's an example of an error which repeats for every chunk:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "amulet\api\level\base_level\base_level.py", line 460, in save_iter
  File "amulet\api\wrapper\format_wrapper.py", line 457, in load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 438, in _safe_load
amulet.api.errors.ChunkLoadError: Could not find a matching interface for ('java', 2860)
2021-12-04 00:06:20,484 - amulet_core - INFO - Converting chunk minecraft:overworld 32, 1108
2021-12-04 00:06:20,485 - amulet_core - ERROR - Error loading chunk 32 1108 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 433, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 476, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 241, in _get_interface_and_translator
  File "amulet\api\wrapper\world_format_wrapper.py", line 67, in _get_interface
  File "amulet\level\loader.py", line 74, in get
  File "amulet\level\loader.py", line 85, in identify
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('java', 2860)
2021-12-04 00:06:20,485 - amulet_core - INFO - Error loading chunk 32 1108
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 433, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 476, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 241, in _get_interface_and_translator
  File "amulet\api\wrapper\world_format_wrapper.py", line 67, in _get_interface
  File "amulet\level\loader.py", line 74, in get
  File "amulet\level\loader.py", line 85, in identify
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('java', 2860)
```

**To Reproduce**
Prune Java 1.17 world with MCA Editor
Reload world in 1.18 Java and confirm it works.
Create 1.18 Bedrock world
Use Amulet to convert from my recently upgraded Java 1.17 world to Bedrock 1.18

**Expected behavior**
The docs say 1.17 and up so I would expect that includes 1.18

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/49648086/144698389-f70b78c3-a75c-4a1e-acd0-b292e593b3c5.png)

**Comment by gentlegiantJGC** [comment]
Only the experimental alpha supports 1.18. I assume you are using the old version.

**Comment by mikezimm** [comment]
@gentlegiantJGC , by chance do you know how long it might be before it makes it to stable release?  If not, what might the possible risks be?  Any possibility of long-term corruption or just errors preventing some chunks from getting converted?

Thanks again!

**Comment by gentlegiantJGC** [comment]
As long as it takes to fix the bugs.
I think Java is fairly stable. Bedrock has some issues
