### ISSUE TITLE
World not loading fully

### ISSUE THREAD

**Issue by Kobra299** [Amulet-Team/Amulet-Map-Editor#478]
when the world loads it show only some of the world some sections are not loaded and the console shows this when it finished loading the level here is screen shot in 2d and 3d view 

![Amulet Error 2d](https://user-images.githubusercontent.com/4283156/144726820-692b82c8-b6d5-47a2-8dc3-91093fd1f410.png)

![Amulet Error 3d](https://user-images.githubusercontent.com/4283156/144726818-42681f53-ef72-447c-934f-c34b8443bd2a.png)

so basically it not loading the chunks fully

2021-12-04 01:24:43,763 - amulet_map_editor - INFO - Could not find loader for C:\Users\User\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\pJnnYJZwAwA= Could not find a matching format for C:\Users\User\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\pJnnYJZwAwA=
2021-12-04 01:25:07,311 - amulet_core - INFO - Loading level C:\Users\User\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\CH29YIpgBwA=
2021-12-04 01:27:09,487 - minecraft_model_reader - INFO - Downloading java launcher manifest file.
2021-12-04 01:27:10,268 - minecraft_model_reader - INFO - Finished downloading java launcher manifest file.
2021-12-04 01:29:25,230 - amulet_map_editor - INFO - Finished setting up texture atlas in OpenGL
2021-12-04 01:29:29,062 - amulet_core - ERROR - Error loading chunk 51 -1 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 433, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 476, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 241, in _get_interface_and_translator
  File "amulet\api\wrapper\world_format_wrapper.py", line 67, in _get_interface
  File "amulet\level\loader.py", line 74, in get
  File "amulet\level\loader.py", line 85, in identify
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('bedrock', 39)
2021-12-04 01:29:29,062 - amulet_map_editor - INFO - Error loading chunk (51, -1)
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 433, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 476, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 241, in _get_interface_and_translator
  File "amulet\api\wrapper\world_format_wrapper.py", line 67, in _get_interface
  File "amulet\level\loader.py", line 74, in get
  File "amulet\level\loader.py", line 85, in identify
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('bedrock', 39)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 174, in create_geometry
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 89, in chunk
  File "amulet\api\level\base_level\base_level.py", line 567, in get_chunk
  File "amulet\api\level\base_level\chunk_manager.py", line 187, in get_chunk
  File "amulet\api\history\history_manager\database.py", line 158, in _get_entry
  File "amulet\api\history\history_manager\database.py", line 166, in _get_register_original_entry
  File "amulet\api\level\base_level\chunk_manager.py", line 191, in _raw_get_entry
  File "amulet\api\wrapper\format_wrapper.py", line 457, in load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 438, in _safe_load
amulet.api.errors.ChunkLoadError: Could not find a matching interface for ('bedrock', 39)
2021-12-04 01:29:29,140 - amulet_core - ERROR - Error loading chunk 52 -1 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 433, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 476, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 241, in _get_interface_and_translator
  File "amulet\api\wrapper\world_format_wrapper.py", line 67, in _get_interface
  File "amulet\level\loader.py", line 74, in get
  File "amulet\level\loader.py", line 85, in identify
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('bedrock', 39)
2021-12-04 01:29:29,140 - amulet_map_editor - INFO - Error loading chunk (52, -1)
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 433, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 476, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 241, in _get_interface_and_translator
  File "amulet\api\wrapper\world_format_wrapper.py", line 67, in _get_interface
  File "amulet\level\loader.py", line 74, in get
  File "amulet\level\loader.py", line 85, in identify
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('bedrock', 39)

**Comment by Black-Rock-Shooter** [comment]
This happens on my bedrock worlds too,  I'm not that technically inclined, but for my worlds, the loading failures seems to be pretty closely correlated with places players have been/traveled a lot recently

**Comment by gentlegiantJGC** [comment]
The version of Amulet you are using does not support 1.18 worlds.
The experimental alpha release of Amulet has support but it is buggy.
