### ISSUE TITLE
Unable to convert 1.18 Java to 1.18 Bedrock using:  v0.8.16b0

### ISSUE THREAD

**Issue by mikezimm** [Amulet-Team/Amulet-Map-Editor#480]
**Describe the bug**
Unable to convert brand new Java 1.18 world to Bedrock 1.18.
In my previous bug report, ( #474 ) I had not been using experimental alpha and was using a world with pruned 1.17 chunks.
Now I am now using:  Amulet-v0.8.16b0.dev202111170713-Windows-x64

**To Reproduce**
1. Created and saved brand new world in 1.18 Java
2. Created and saved brand new world in 1.18.0 Bedrock (PC).
3. Downloaded latest Amulet alpha version:  Amulet-v0.8.16b0.dev202111170713-Windows-x64
4. Attempted conversion

**Expected behavior**
Would expect it to be able to convert brand new 1.18 Java to Bedrock.

## Other comments:
In previous conversion attempts, I could easily convert pruned 1.17.1 Java chunks into Bedrock 1.18.  The problem only seems to arise when bringing in chunks loaded into or created by Java 1.18.

I'm not a python programmer but in typescript, we use "Interfaces" to define expected data structures.
Based on the error message below....
Is it possible that this alpha version just does not have a data structure defined for Java 1.18 yet?

_*"Could not find a matching interface for ('java', 2860)"*_

**Screenshots**
This is the error message that seems to get repeated for Every chunk....
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "amulet\api\level\base_level\base_level.py", line 460, in save_iter
  File "amulet\api\wrapper\format_wrapper.py", line 457, in load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 438, in _safe_load
amulet.api.errors.ChunkLoadError: Could not find a matching interface for ('java', 2860)
2021-12-04 19:51:32,998 - amulet_core - INFO - Converting chunk minecraft:overworld -10, -13
2021-12-04 19:51:32,999 - amulet_core - ERROR - Error loading chunk -10 -13 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 433, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 476, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 241, in _get_interface_and_translator
  File "amulet\api\wrapper\world_format_wrapper.py", line 67, in _get_interface
  File "amulet\level\loader.py", line 74, in get
  File "amulet\level\loader.py", line 85, in identify
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('java', 2860)
2021-12-04 19:51:32,999 - amulet_core - INFO - Error loading chunk -10 -13
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 433, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 476, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 241, in _get_interface_and_translator
  File "amulet\api\wrapper\world_format_wrapper.py", line 67, in _get_interface
  File "amulet\level\loader.py", line 74, in get
  File "amulet\level\loader.py", line 85, in identify
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('java', 2860)
```

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/49648086/144729530-41f242f6-154e-4956-864b-525710ceb158.png)

**Additional context**

**Comment by gentlegiantJGC** [comment]
I messed up the version numbers when building.
You need 0.8.16a4
The version you are using does not support 1.18
