### ISSUE TITLE
Conversion from Bedrock 1.18 to Java 1.18 failing

### ISSUE THREAD

**Issue by KJsRepo** [Amulet-Team/Amulet-Map-Editor#483]
Python 3.9
Amulet V0.8.15
Old world:  Bedrock 1.18.0.2.0
New world:  Java 1.18
Windows 10
Java:  1.8.0_271-b09

Installed from source via pip, using an Virtual Environment
The following error appears for every chunk:

```
2021-12-06 09:39:02,683 - amulet_core - INFO - Converting chunk minecraft:overworld 200, 272
2021-12-06 09:39:02,688 - amulet_core - ERROR - Error saving chunk Chunk(200, 272, UnboundedPartial3DArray(dtype=<class 'numpy.uint32'>, shape=(16, inf, 16)), EntityList([]), BlockEntityDict(
))
Traceback (most recent call last):
  File "C:\Users\Keith\amuletenv\lib\site-packages\amulet\api\wrapper\format_wrapper.py", line 556, in commit_chunk
    self._commit_chunk(copy.deepcopy(chunk), dimension)
  File "C:\Users\Keith\amuletenv\lib\site-packages\amulet\api\wrapper\format_wrapper.py", line 573, in _commit_chunk
    interface, translator, chunk_version = self._get_interface_and_translator()
  File "C:\Users\Keith\amuletenv\lib\site-packages\amulet\api\wrapper\format_wrapper.py", line 241, in _get_interface_and_translator
    interface = self._get_interface(raw_chunk_data)
  File "C:\Users\Keith\amuletenv\lib\site-packages\amulet\api\wrapper\world_format_wrapper.py", line 67, in _get_interface
    return Interfaces.get(key)
  File "C:\Users\Keith\amuletenv\lib\site-packages\amulet\level\loader.py", line 74, in get
    object_id = self.identify(identifier)
  File "C:\Users\Keith\amuletenv\lib\site-packages\amulet\level\loader.py", line 84, in identify
    raise LoaderNoneMatched(
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('java', 2860)
```

**Comment by gentlegiantJGC** [comment]
The version you have installed does not support 1.18. there is an experimental alpha release for 1.18 support
