### ISSUE TITLE
cant open a world using a paper server

### ISSUE THREAD

**Issue by josh-65** [Amulet-Team/Amulet-Map-Editor#502]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**
Not that i found

**Describe the bug**
I cant open a world that has been ran using paper server. due to the buckkit world data pack

```
The given path S:\Minecraft\1.18.1 Paper - ISO labs\wAlien\datapacks\bukkit is not valid.
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\amulet_ui.py", line 168, in _open_world
  File "amulet_map_editor\api\framework\pages\world_page.py", line 80, in __init__
  File "amulet\level\load.py", line 30, in load_level
  File "amulet\api\level\world.py", line 14, in __init__
  File "amulet\api\level\base_level\base_level.py", line 57, in __init__
  File "amulet\api\wrapper\format_wrapper.py", line 328, in open
  File "amulet\level\formats\anvil_world\format.py", line 389, in _open
  File "amulet\level\formats\anvil_world\format.py", line 366, in _reload_world
  File "amulet\level\formats\anvil_world\format.py", line 236, in _register_dimension
  File "amulet\level\formats\anvil_world\format.py", line 171, in data_pack
  File "amulet\level\formats\anvil_world\data_pack\data_pack.py", line 157, in is_path_valid
  File "amulet\level\formats\anvil_world\data_pack\data_pack.py", line 133, in _open_wrapper
FileNotFoundError: The given path S:\Minecraft\1.18.1 Paper - ISO labs\wAlien\datapacks\bukkit is not valid.
```

**Expected behavior**
It should ignore and not modify the data pack and open the world

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19043.1387
 - Version: 0.8.15

**Comment by josh-65** [comment]
Just found it was fixed in #333
