### ISSUE TITLE
C++ assertion "IsShown()" failed at ..\..\src\common\glcmn.cpp(84) in wxGLCanvasBase::SetCurrent(): can't make hidden GL canvas current

### ISSUE THREAD

**Issue by padriff** [Amulet-Team/Amulet-Map-Editor#514]
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**
Not that I can find

**Describe the bug**
Amulet fails to open Bedrock world in 3D Editor, issuing assertion failure and call stack to console.

**To Reproduce**
Download Amulet v0.8.15-Windows-x64.zip
Unzip archive
Run Amulet_app.exe from extracted files
Open saved Bedrock 1.18.1 world
Open 3D Editor tab
Alt-Tab to a different app and then switch back to Amulet before opening has completed.
Observe assertion error and stack spewed to console:

```
2021-12-23 13:28:35,429 - amulet_core - INFO - Loading level C:\Users\paddymcd\Desktop\scratch\minecraft\corryvreckan\worlds\Kieras World
2021-12-23 13:29:07,087 - minecraft_model_reader - INFO - Downloading java launcher manifest file.
2021-12-23 13:29:07,379 - minecraft_model_reader - INFO - Finished downloading java launcher manifest file.
2021-12-23 13:29:07,380 - minecraft_model_reader - INFO - Downloading Java resource pack for version 1.18.1
2021-12-23 13:29:25,009 - amulet_map_editor - CRITICAL - Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 155, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 84, in enable
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 123, in enable
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 229, in enable
wx._core.wxAssertionError: C++ assertion "IsShown()" failed at ..\..\src\common\glcmn.cpp(84) in wxGLCanvasBase::SetCurrent(): can't make hidden GL canvas current

2021-12-23 13:29:44,202 - amulet_map_editor - CRITICAL - Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 155, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 53, in enable
RuntimeError: wrapped C/C++ object of type Gauge has been deleted

```

Works OK on retry - didn't switch apps during load of the #D Editor tab

**Expected behavior**
No assertion and world opens in editor

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - Version: Insider Preview 10.0.22515.1001 (Microsoft internal Developer version rs_lkg branch build.22515.rs.lkg.211201-1657) 
 - Hardware: Microsoft Surface Book 2
 

**Additional context**

**Comment by gentlegiantJGC** [comment]
Duplicate of #402
