### ISSUE TITLE
Crash on 1.18 Bedrock Map Load

### ISSUE THREAD

**Issue by chadwick101** [Amulet-Team/Amulet-Map-Editor#536]
Describe the issue:  When loading a 1.18 Bedrock map, I get the following errors right as the 3D map loads.  The 3D portion freezes, and Amulet crashes.  This occurs for a few chunks, I included the last one.

2022-01-15 19:49:47,039 - amulet_map_editor - ERROR - Failed generating chunk geometry for chunk (-2, -1)
Traceback (most recent call last):
  File "amulet_map_editor\api\opengl\mesh\level\level.py", line 168, in thread_action
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 186, in create_geometry
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 122, in _sub_chunks
  File "amulet\api\level\base_level\base_level.py", line 567, in get_chunk
  File "amulet\api\level\base_level\chunk_manager.py", line 187, in get_chunk
  File "amulet\api\history\history_manager\database.py", line 158, in _get_entry
  File "amulet\api\history\history_manager\database.py", line 169, in _get_register_original_entry
  File "amulet\api\history\history_manager\database.py", line 175, in _register_original_entry
  File "amulet\api\level\base_level\chunk_manager.py", line 222, in _create_new_revision_manager
  File "amulet\api\level\base_level\chunk_manager.py", line 22, in __init__
  File "amulet\api\history\revision_manager\disk.py", line 16, in __init__
  File "amulet\api\history\base\revision_manager.py", line 23, in __init__
  File "amulet\api\history\revision_manager\disk.py", line 20, in _store_entry
  File "amulet\api\level\base_level\chunk_manager.py", line 34, in _serialise
  File "amulet\libs\leveldb\leveldb.py", line 296, in put
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

Windows 10 x64, using the pre compiled Nightly 0.8.17b1.dev202201130714 or 0.8.17b0

To reproduce: Load a v1.18 world to 3D map

**Comment by gentlegiantJGC** [comment]
Does this issue still happen in 0.9.2?
