### ISSUE TITLE
Assertion Error when running Amulet from outside the executable directory

### ISSUE THREAD

**Issue by vadim-goryunov** [Amulet-Team/Amulet-Map-Editor#543]
When I am trying to switch to 3D Editor after opening a map (auto-generated by Minecraft) - Amulet shows this error

Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 143, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 51, in enable
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 101, in setup
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 113, in _setup
  File "amulet_map_editor\programs\edit\api\ui\tool_manager.py", line 49, in __init__
  File "amulet_map_editor\programs\edit\api\ui\tool_manager.py", line 67, in register_tool
  File "amulet_map_editor\programs\edit\api\ui\tool\base_operation_choice.py", line 46, in __init__
  File "amulet_map_editor\programs\edit\api\operations\manager\operation_manager.py", line 31, in __init__
  File "amulet_map_editor\programs\edit\api\operations\manager\operation_manager.py", line 53, in reload
  File "amulet_map_editor\programs\edit\api\operations\manager\operation_manager.py", line 83, in _load_external_submodules
  File "amulet_map_editor\programs\edit\api\operations\manager\operation_manager.py", line 97, in _load_submodules
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgutil.py", line 59, in _pyi_pkgutil_iter_modules
AssertionError

and then 3D Editor disappears.

### Environment:
- OS: Windows10
- Minecraft Platform: Bedrock
- Minecraft Version: 1.18.2.3.0
- Amulet Version: 0.8.17

### Additional context
First time trying to use Amulet.
Please let me know if I am missing something obvious.

### Worlds
the world is the standard one auto-generated by Minecraft

**Comment by gentlegiantJGC** [comment]
Are you running from source or the compiled build?
I am trying to work out why I can't reproduce this.

**Comment by vadim-goryunov** [comment]
This is a precompiled version available on the website. I managed to launch it from sources now. However, the version from sources didn't work with python 3.10. I had to downgrade to python 3.9 to make it working

**Comment by gentlegiantJGC** [comment]
Are you running the exe through a shortcut or something? I think that is what is causing it. It looks like an issue with pyinstaller.

**Comment by vadim-goryunov** [comment]
yes, I was running executable directly. Will try via a shortcut

**Comment by gentlegiantJGC** [comment]
Running the executable directly should work.
I have reproduced the issue when running the executable from a different directory.

**Comment by gentlegiantJGC** [comment]
I have just submitted code to pyinstaller that will fix this issue but it will still be an issue until they accept the changes and release a new version with the changes and we do a release with that version.
https://github.com/pyinstaller/pyinstaller/pull/6529

**Comment by gentlegiantJGC** [comment]
Pyinstaller accepted the fixes so one of the next builds should fix this.
