### ISSUE TITLE
world loading not working only blank screen

### ISSUE THREAD

**Issue by Hema-Chandra06** [Amulet-Team/Amulet-Map-Editor#552]
https://user-images.githubusercontent.com/96871624/151352362-d9999781-bc99-4124-a989-a7d3e98ce2c7.mp4

Either Java worlds are loading nor bedrock

**Comment by Hema-Chandra06** [comment]
Plz help

**Comment by gentlegiantJGC** [comment]
Sometimes it takes a while to load

**Comment by Hema-Chandra06** [comment]
> Sometimes it takes a while to load

Its Not Loading even after 10min

**Comment by gentlegiantJGC** [comment]
How large is your world?
Sometimes it can take a really long time. I should add some kind of loading indicator for large worlds

**Comment by RealStrozy** [comment]
I am getting the same issue with the following error

```
Traceback (most recent call last):
  File "/home/***/miniconda3/lib/python3.9/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 356, in _on_draw
    self.canvas.renderer.draw_sky_box()
  File "/home/***/miniconda3/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/renderer.py", line 242, in draw_sky_box
    self.sky_box.draw(self.canvas.camera.transformation_matrix)
  File "/home/***/miniconda3/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/sky_box.py", line 64, in draw
    super().draw(
  File "/home/***/miniconda3/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/tri_mesh.py", line 153, in draw
    self._setup()
  File "/home/***/miniconda3/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/tri_mesh.py", line 82, in _setup
    self._shader = get_shader(self.context_identifier, self.shader_name)
  File "/home/***/miniconda3/lib/python3.9/site-packages/amulet_map_editor/api/opengl/shaders/__init__.py", line 28, in get_shader
    glGetString(GL_SHADING_LANGUAGE_VERSION).decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'decode'
```

System:
`Linux debian 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux`


I hope this can help.

**Comment by n0itLT** [comment]
This is happening to me as well. World is 1.72GB

**Comment by gentlegiantJGC** [comment]
@Hema-Chandra06 are there errors in the console window?
This looks similar to #496

**Comment by gentlegiantJGC** [comment]
This may be fixed by the changes in https://github.com/Amulet-Team/Amulet-Map-Editor/pull/678
