### ISSUE TITLE
[Bug Report] glGenTextures error

### ISSUE THREAD

**Issue by Zahichoy** [Amulet-Team/Amulet-Map-Editor#556]
![QQ截图20220203204006](https://user-images.githubusercontent.com/64466677/152344739-0e4ed57b-5155-419b-acdb-00edde035a5b.jpg)
![QQ截图20220203204115](https://user-images.githubusercontent.com/64466677/152344745-e423809b-851f-4cfb-9e6b-c0cdae040e79.jpg)
Here are the images. When I try to edit a map, I can't open the 3d editor successfully, did I lack something to run this program?

Program version: V0.8.17
Operate System: Win 10

**Comment by Zahichoy** [comment]
`GLError(
	err = 1282,
	description = b'\xce\xde\xd0\xa7\xb2\xd9\xd7\xf7',
	baseOperation = glGenTextures,
	pyArgs = (
		1,
		<object object at 0x000002841F1BF210>,
	),
	cArgs = (1, array([0], dtype=uint32)),
	cArguments = (1, array([0], dtype=uint32))
)
Traceback (most recent call last):
  File "OpenGL\latebind.py", line 43, in __call__
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 143, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 50, in enable
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 93, in __init__
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 58, in __init__
  File "amulet_map_editor\api\opengl\canvas\event_canvas.py", line 12, in __init__
  File "amulet_map_editor\api\opengl\canvas\canvas.py", line 47, in __init__
  File "OpenGL\latebind.py", line 47, in __call__
  File "OpenGL\wrapper.py", line 678, in wrapperCall
  File "OpenGL\wrapper.py", line 671, in wrapperCall
  File "OpenGL\platform\baseplatform.py", line 415, in __call__
  File "OpenGL\error.py", line 234, in glCheckError
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'\xce\xde\xd0\xa7\xb2\xd9\xd7\xf7',
	baseOperation = glGenTextures,
	pyArgs = (
		1,
		<object object at 0x000002841F1BF210>,
	),
	cArgs = (1, array([0], dtype=uint32)),
	cArguments = (1, array([0], dtype=uint32))
)
`
Here is the error log. Thanks for helping!

**Comment by gentlegiantJGC** [comment]
This may be fixed by the changes in #678
