### ISSUE TITLE
[Bug Report] Being able to move too far

### ISSUE THREAD

**Issue by Flonja** [Amulet-Team/Amulet-Map-Editor#557]
## Bug Report
I'm moving too far out the world and that produces these errors:
```
Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\api\behaviour\pointer_behaviour.py", line 83, in _pre_draw
  File "amulet_map_editor\programs\edit\api\behaviour\block_selection_behaviour.py", line 420, in _update_pointer
  File "amulet_map_editor\programs\edit\api\behaviour\raycast_behaviour.py", line 74, in closest_block_3d
  File "amulet_map_editor\programs\edit\api\behaviour\raycast_behaviour.py", line 221, in collision_locations
ValueError: arange: cannot compute length
```
```
Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\api\behaviour\pointer_behaviour.py", line 83, in _pre_draw
  File "amulet_map_editor\programs\edit\api\behaviour\block_selection_behaviour.py", line 412, in _update_pointer
  File "amulet_map_editor\programs\edit\api\behaviour\raycast_behaviour.py", line 175, in distance_block_3d
OverflowError: Python int too large to convert to C long
```
I'm clearly going too far out of any range (it being Minecraft limits and Python limits)

### Current Behaviour:
No movement limits: (seemingly infinite)
![image](https://user-images.githubusercontent.com/20887403/152645314-b45bfff7-e13c-4676-81f5-3c19a3fa46db.png)

### Expected behavior:

Well, I'd be expecting to be limited by Minecraft limits. (E.g. world border)
But that might not be desirable by everyone.

### Steps To Reproduce:
- Set your speed to something high, so you can move (too) fast.
- Move around a bit.
- Profit?

### Environment:
- OS: Windows
- Minecraft Platform: Java (this might not matter though)
- Minecraft Version: 1.18.1 (this might not matter though)
- Amulet Version: 0.8.17

**Comment by gentlegiantJGC** [comment]
This will be fixed in 0.10
