### ISSUE TITLE
[Bug Report] Windows Error 0xe06d7363

### ISSUE THREAD

**Issue by gentlegiantJGC** [Amulet-Team/Amulet-Map-Editor#563]
## Bug Report
Windows Error 0xe06d7363 when editing large worlds.
This error appears when trying to write to a large world.

```
[WinError -529697949] Windows Error 0xe06d7363
Traceback (most recent call last):
  File "amulet_map_editor\programs\convert\convert.py", line 157, in _convert_method
  File "amulet\api\level\base_level\base_level.py", line 412, in save
  File "amulet\api\level\base_level\base_level.py", line 467, in save_iter
  File "amulet\api\wrapper\format_wrapper.py", line 380, in save
  File "amulet\level\formats\leveldb_world\format.py", line 353, in _save
  File "amulet\level\formats\leveldb_world\dimension.py", line 56, in save
  File "amulet\libs\leveldb\leveldb.py", line 304, in putBatch
OSError: [WinError -529697949] Windows Error 0xe06d7363
```

This behaviour is normally reproduced when converting a very large input world.

This may be an issue with our leveldb wrapper or potentially an issue in the leveldb library itself though more likely with our wrapper.
This may be related to the world size or it might just just happen rarely and only appear in large conversions.

**Comment by gentlegiantJGC** [comment]
This might have been fixed by Amulet-Team/Amulet-Core#189
If anyone has this issue in a version of Amulet newer than 0.9.3b0 then let me know.

**Comment by gentlegiantJGC** [comment]
This hasn't been reported since I made those changes so I am going to close this.
