### ISSUE TITLE
[Bug Report] Your Title Here

### ISSUE THREAD

**Issue by PixusPanic** [Amulet-Team/Amulet-Map-Editor#575]
### Current Behaviour:
When [Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries) resource pack is trying to be loaded, the application refuses to enter into the 3D editor tab, giving the following error message:

```
Expecting property name enclosed in double quotes: line 6 column 5 (char 147)
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 165, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 51, in enable
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 101, in setup
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 106, in _setup
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 190, in _setup
  File "minecraft_model_reader\api\resource_pack\base\resource_pack_manager.py", line 49, in reload
  File "minecraft_model_reader\api\resource_pack\java\resource_pack_manager.py", line 183, in _load_iter
  File "json\__init__.py", line 296, in load
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 6 column 5 (char 147)
```

### Expected behavior:

The app loads into the 3D editor.

### Steps To Reproduce:
1. Put Supplementaries' included resource pack inside a test resource pack folder
2. Start up Amulet, load a world, go to 3D editor
3. See error

### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java
- Minecraft Version: 1.18.1
- Amulet Version: V0.9.0a1

**Comment by gentlegiantJGC** [comment]
There are 4 files in the pack where the json is invalid and as such loading fails.
I will add some code to skip over files that cannot be loaded.
