### ISSUE TITLE
[Bug Report] Can't Launch Program (Arch Linux

### ISSUE THREAD

**Issue by Dogeislove** [Amulet-Team/Amulet-Map-Editor#584]
Gauge.SetValue(): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "/home/shiba/.local/lib/python3.10/site-packages/amulet_map_editor/api/framework/pages/world_page.py", line 143, in _enable_active
    self._extensions[self.GetSelection()].enable()
  File "/home/shiba/.local/lib/python3.10/site-packages/amulet_map_editor/programs/edit/edit.py", line 59, in enable
    self._temp_loading_bar.SetValue(min(arg[0], 1) * 10000)
TypeError: Gauge.SetValue(): argument 1 has unexpected type 'float'

(Second Error)
list index out of range
Traceback (most recent call last):
  File "/home/shiba/.local/lib/python3.10/site-packages/amulet_map_editor/api/framework/pages/world_page.py", line 143, in _enable_active
    self._extensions[self.GetSelection()].enable()
IndexError: list index out of range

When launching the world (by using their directory as said) it crashes the editor. I don't know how else to explain it.

- OS:linux
- Minecraft Platform: Java |
- Minecraft Version: 1.18, any actually
- Amulet Version: 0.8.19

**Comment by Dogeislove** [comment]
There is small issue, i have no idea if its my linux distro (what i've done, installed, ect) which makes things worse

**Comment by SolidTux** [comment]
Switching to Python 3.7 fixes this issue for me.
