### ISSUE TITLE
Shader Error after reload

### ISSUE THREAD

**Issue by gentlegiantJGC** [Amulet-Team/Amulet-Map-Editor#6]
Open a world, open the 3D view, close the 3D view and close the world, repeat

This error appears when opening the renderer a second time

```
Traceback (most recent call last):
  File "D:\Data\GitHub\Amulet-Map-Editor\amulet_map_editor\amulet_wx\world_manager\__init__.py", line 65, in _page_change
    self._extensions[self.GetSelection()].enable()
  File "D:\Data\GitHub\Amulet-Map-Editor\amulet_map_editor\amulet_wx\world_manager\extensions\amulet_renderer\renderer_wx.py", line 172, in enable
    self._canvas = World3dCanvas(self, self._world)
  File "D:\Data\GitHub\Amulet-Map-Editor\amulet_map_editor\amulet_wx\world_manager\extensions\amulet_renderer\renderer_wx.py", line 47, in __init__
    self._render_world = RenderWorld(world, resource_pack)
  File "D:\Data\GitHub\Amulet-Map-Editor\amulet_map_editor\amulet_wx\world_manager\extensions\amulet_renderer\render_world.py", line 68, in __init__
    self._create_atlas()
  File "D:\Data\GitHub\Amulet-Map-Editor\amulet_map_editor\amulet_wx\world_manager\extensions\amulet_renderer\render_world.py", line 96, in _create_atlas
    glUseProgram(shader)
  File "D:\Data\GitHub\Amulet-Core\venv\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'invalid value',
	baseOperation = glUseProgram,
	cArguments = (3,)
)
```

**Comment by gentlegiantJGC** [comment]
Fixed in 1e9c732bdf9bcf52029d627c1c271b4eb82e53ed
