### ISSUE TITLE
[Bug Report] SSL Verification Failed

### ISSUE THREAD

**Issue by Owgla** [Amulet-Team/Amulet-Map-Editor#623]
## Error
Traceback (most recent call last):
  File "urllib\request.py", line 1350, in do_open
  File "http\client.py", line 1277, in request
  File "http\client.py", line 1323, in _send_request
  File "http\client.py", line 1272, in endheaders
  File "http\client.py", line 1032, in _send_output
  File "http\client.py", line 972, in send
  File "http\client.py", line 1447, in connect
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 160, in _setup
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 99, in get_java_vanilla_latest_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 63, in get_latest_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 56, in get_latest_iter
  File "minecraft_model_reader\api\resource_pack\java\download_resources.py", line 25, in get_launcher_manifest
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 543, in _open
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 1393, in https_open
  File "urllib\request.py", line 1352, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1091)>

### Current Behaviour:
All textures are missing and majority of the world is invisible when trying to open up the 3D Editor

### Expected behavior:
I mean I kind of just expected it to work

### Steps To Reproduce:
1. Open Amulet
2. Load a world
3. Switch over to 3D Editor

### Environment:
- OS: Windows 10 pro version 21H2
- Minecraft Platform: Java 
- Minecraft Version: 1.9.x / 1.12.x / 1.14.x / 1.15.x / 1.16.x / 1.17.x / 1.18.x
- Amulet Version: 0.8.21 64bit / 0.9.0b0 64bit

### Additional context
I also tried manually loading a resource pack, when doing so the world mostly stops being invisible but instead all of the textures are missing and appear as pink and black.
I already searched for the issue and a fix has been discovered but unfortunately said fix only mentions mac OS and as such I haven't been able to fix this issue on my side.

### Screenshot
![alt text](https://i.imgur.com/MDs7z4s.png)

**Comment by gentlegiantJGC** [comment]
Please use the search tool before opening new reports.
There should have also been a popup giving you more info.
See #596

**Comment by gentlegiantJGC** [comment]
Actually I have never seen this on windows before.

**Comment by gentlegiantJGC** [comment]
I don't know why this is happening but I am going to continue tracking this in #419
