### ISSUE TITLE
[Bug Report] Converting 1.13+ to 1.12.2 causes ChunkNibbleArrays error

### ISSUE THREAD

**Issue by Paul19988** [Amulet-Team/Amulet-Map-Editor#661]
### Current Behaviour:
ChunkNibbleArrays are 0 rather than 2048 bytes.

### Expected behavior:
World should work without issue.

### Steps To Reproduce:

1. Convert a 1.13+ world to 1.12.2
2. Attempt to go to the location containing modified chunks
3. Game crashes with the following error:
```
java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
    at net.minecraft.world.chunk.NibbleArray.<init>(SourceFile:16)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:450)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:129)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:93)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
    at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
    at net.minecraft.world.World.func_72964_e(World.java:310)
    at net.minecraft.world.World.func_72838_d(World.java:1211)
    at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
    at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:377)
    at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
```

### Environment:
- OS: Windows & Linux
- Minecraft Platform: Java
- Minecraft Version: 1.16.5/1.17.1 -> 1.12.2
- Amulet Version: v0.9.3b0.dev202204280713

### Worlds
World Attached.
[TRYellow.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/8630969/TRYellow.zip)

**Comment by Paul19988** [comment]
This is also occurs when modifying a world in 1.12.2.

This issue does not occur when using Amulet v0.8.21

**Comment by gentlegiantJGC** [comment]
Thanks for reporting this.
I did write code to handle this but I put it in the wrong place so it was running when the chunk was loaded rather than saving.
