### ISSUE TITLE
[Bug Report] Black screen error OpenGL.error.GLError

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#722]
### Current Behaviour:
- Amulet freezes while loading a world and then switching to another world tab and the screen became black and stopped responding.

### Expected behavior:
- I expected there not to be a black screen and to properly render my world.

### Steps To Reproduce:
- Was not able to reproduce the error, I have attached the console log below.

### Environment:

- OS: Windows 10 Pro
- Minecraft Platform: Bedrock
- Minecraft Version: 1.19.0
- Amulet Version: 0.9.6

### Additional context
- I was switching between two world tabs really quickly nothing was special about them they were both created in bedrock 1.19.0 and were normal flat worlds with some pasted structures from .scheme files from java 1.16.5.

- Reloading Amulet resolved the issue and the issue did not persist even when loading both worlds in Amulet again.

- I have also shared with you two screenshots of the issue when it happened.

```bat
2022-06-25 12:43:33,122 - minecraft_model_reader - INFO - Downloading java launcher manifest file.
2022-06-25 12:43:33,218 - minecraft_model_reader - INFO - Finished downloading java launcher manifest file.
2022-06-25 12:43:50,056 - amulet_map_editor - INFO - Creating texture atlas
2022-06-25 12:43:50,479 - amulet_map_editor - INFO - Trying to pack textures into image of size 4096x4096
2022-06-25 12:43:51,096 - amulet_map_editor - INFO - Successfully packed textures into an image of size 4096x4096
2022-06-25 12:43:51,125 - amulet_map_editor - INFO - Finished creating texture atlas
2022-06-25 12:43:52,286 - amulet_map_editor - INFO - Finished setting up texture atlas in OpenGL
2022-06-25 12:44:08,185 - amulet_core - INFO - Loading level C:\Users\USERNAME\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\saC2YmNOEAA=
2022-06-25 12:44:12,626 - amulet_map_editor - INFO - Finished setting up texture atlas in OpenGL
Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\plugins\tools\select.py", line 356, in _on_draw
  File "amulet_map_editor\programs\edit\api\renderer.py", line 242, in draw_sky_box
  File "amulet_map_editor\api\opengl\mesh\sky_box.py", line 66, in draw
  File "amulet_map_editor\api\opengl\mesh\tri_mesh.py", line 154, in draw
  File "amulet_map_editor\api\opengl\mesh\tri_mesh.py", line 157, in _draw
  File "OpenGL\error.py", line 234, in glCheckError
OpenGL.error.GLError: GLError(
        err = 1281,
        description = b'invalid value',
        baseOperation = glUseProgram,
        cArguments = (3,)
)
```

## Attachments
N/A:

### Screenshots
![image](https://user-images.githubusercontent.com/17806994/175783162-19c6ff34-2491-4bea-ba68-de7a1281d95e.png)
![image](https://user-images.githubusercontent.com/17806994/175783179-e469c28d-f528-4226-a416-dba1705b28fd.png)

### Worlds
N/A:
I can not share the world sadly.

**Comment by StealthyExpertX** [comment]
I remember something else, I also closed a world when this happened.

**Comment by gentlegiantJGC** [comment]
I have reworked the window and opengl handling in 0.10 which might fix this.

**Comment by StealthyExpertX** [comment]
Thanks for getting to this quickly, I appreciate it.

**Comment by gentlegiantJGC** [comment]
This was implemented a little while ago I just haven't gotten around to releasing 0.10

**Comment by gentlegiantJGC** [comment]
@StealthyExpertX is this still an issue?

**Comment by StealthyExpertX** [comment]
I haven't seen this in a while but, I'll try some tests later today and see if I can recreate it.
