### ISSUE TITLE
[Bug Report] Caught Exception

### ISSUE THREAD

**Issue by Dracconis** [Amulet-Team/Amulet-Map-Editor#736]
## Bug Report
After using Amulet on a fresh 1.19 world, deleting roughly 3 regions from build height (319) to bedrock (-64) and loading back into MC and opening the world I am greeted by an error message.
`Caught exception in thread Thread[Worker-Main-12,5,main]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2804.method_12139(int, int, int)" because "$$2" is null
    at net.minecraft.class_3560.method_15537(class_3560.java:96)
    at net.minecraft.class_3558.method_15480(class_3558.java:143)
    at net.minecraft.class_3554.method_15478(class_3554.java:137)
    at net.minecraft.class_3552.method_15514(class_3552.java:129)
    at net.minecraft.class_3568.method_15514(class_3568.java:45)
    at net.minecraft.class_3227.method_14275(class_3227.java:146)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
    at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
    at net.minecraft.class_3227.method_17312(class_3227.java:146)
    at net.minecraft.class_3227.method_14277(class_3227.java:182)
    at net.minecraft.class_3227.method_19505(class_3227.java:167)
    at net.minecraft.class_3846.method_16907(class_3846.java:91)
    at net.minecraft.class_3846.method_16900(class_3846.java:146)
    at net.minecraft.class_3846.run(class_3846.java:102)
    at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)`

### Current Behaviour:
Load the world, error occurs, world stops generating blocks.

### Expected behavior:
I expected the program not to cause errors or corrupt the world.

### Environment:
- OS: Windows
- Minecraft Platform: Java 
- Minecraft Version: 1.19
- Amulet Version: 0.10.0a1

More than willing to provide more information for which I may not have the answers for right this minute while writing out this report.

**Comment by gentlegiantJGC** [comment]
> deleting roughly 3 regions

Are you deleting all chunks in the region or just the blocks?

Is this a vanilla Minecraft client or modded?
The class names in the error log do not match the class names in the vanilla jar so I can't do much with the error log.

Can you provide a world that this error happens in so I can debug further.

**Comment by Dracconis** [comment]
I was attempting to delete a full region file and when I ran into that error I changed it to deleting just a few chunks, but still ran into the same error. That is when I came back here to report the error. It was fabric profile. I did notice though the error occurred only when whole villages or partial villages were deleted.
