### ISSUE TITLE
'-u build.py build' failed

### ISSUE THREAD

**Issue by morganofthefairies** [Amulet-Team/Amulet-Map-Editor#739]
### Current Behaviour:
When attempting to install through source terminal cannot run 'setup.py install' correctly
(I'm sorry about this huge chunk of code, this is quite literally all of the error message)
```
      /Users/morgan/env/lib/python3.10/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
      warnings.warn(
      /Users/morgan/env/lib/python3.10/site-packages/setuptools/dist.py:294: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running install
      running build
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "/Users/morgan/env/bin/python" -u build.py build
      /private/var/folders/l7/73gc7t710rd_stny41nfq_pm0000gn/T/pip-install-19fj6ib9/wxpython_0398fd3ac1d34bae9d6c90400f81ae6e/build.py:41: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
        from distutils.dep_util import newer, newer_group
      Will build using: "/Users/morgan/env/bin/python"
      3.10.5 (v3.10.5:f377153967, Jun  6 2022, 12:36:10) [Clang 13.0.0 (clang-1300.0.29.30)]
      Python's architecture is 64bit
      cfg.VERSION: 4.1.1
      
      Running command: build
      Running command: build_wx
      wxWidgets build options: ['--wxpython', '--unicode', '--osx_cocoa']
      Configure options: ['--enable-unicode', '--with-osx_cocoa', '--enable-sound', '--enable-graphics_ctx', '--enable-display', '--enable-geometry', '--enable-debug_flag', '--enable-optimise', '--disable-debugreport', '--enable-uiactionsim', '--enable-autoidman', '--with-macosx-version-min=10.10']
      /private/var/folders/l7/73gc7t710rd_stny41nfq_pm0000gn/T/pip-install-19fj6ib9/wxpython_0398fd3ac1d34bae9d6c90400f81ae6e/ext/wxWidgets/configure --enable-unicode --with-osx_cocoa --enable-sound --enable-graphics_ctx --enable-display --enable-geometry --enable-debug_flag --enable-optimise --disable-debugreport --enable-uiactionsim --enable-autoidman --with-macosx-version-min=10.10
      checking build system type... x86_64-apple-darwin21.5.0
      checking host system type... x86_64-apple-darwin21.5.0
      checking for toolkit... osx_cocoa
      checking for gcc... gcc
      checking whether the C compiler works... no
      configure: error: in `/private/var/folders/l7/73gc7t710rd_stny41nfq_pm0000gn/T/pip-install-19fj6ib9/wxpython_0398fd3ac1d34bae9d6c90400f81ae6e/build/wxbld':
      configure: error: C compiler cannot create executables
      See `config.log' for more details
      Error running configure
      ERROR: failed building wxWidgets
      Traceback (most recent call last):
        File "/private/var/folders/l7/73gc7t710rd_stny41nfq_pm0000gn/T/pip-install-19fj6ib9/wxpython_0398fd3ac1d34bae9d6c90400f81ae6e/build.py", line 1510, in cmd_build_wx
          wxbuild.main(wxDir(), build_options)
        File "/private/var/folders/l7/73gc7t710rd_stny41nfq_pm0000gn/T/pip-install-19fj6ib9/wxpython_0398fd3ac1d34bae9d6c90400f81ae6e/buildtools/build_wxwidgets.py", line 372, in main
          exitIfError(wxBuilder.configure(dir=wxRootDir, options=configure_opts),
        File "/private/var/folders/l7/73gc7t710rd_stny41nfq_pm0000gn/T/pip-install-19fj6ib9/wxpython_0398fd3ac1d34bae9d6c90400f81ae6e/buildtools/build_wxwidgets.py", line 85, in exitIfError
          raise builder.BuildError(msg)
      buildtools.builder.BuildError: Error running configure
      Finished command: build_wx (0.986s)
      Finished command: build (0.987s)
      Command '"/Users/morgan/env/bin/python" -u build.py build' failed with exit code 1.
```

### Expected behavior:
Expected the program to install

### Steps To Reproduce:
Install  

### Environment:

- OS: OSX
- Minecraft Platform: not even installed
- Minecraft Version: not even installed
- Amulet Version: 0.9.6

**Comment by gentlegiantJGC** [comment]
This is an issue building wx from source.
This is a third party library we are using so build issues are out of our hands.
The usual fix for this is to use python 3.7-3.9 which have compiled builds on pypi so you don't need to build from source.
