### ISSUE TITLE
Error when transitioning from 3D to Chunk view

### ISSUE THREAD

**Issue by batesjonathan** [Amulet-Team/Amulet-Map-Editor#755]
When transitioning from 3D view to 2D (Chunk) view via clicking the Chunk tab, the icon spins and never resolves. The screen does not transition to 2D view.

The following error is generated:

2022-07-20 13:34:26,357 - amulet_core - INFO - Loading level C:\Users\jonat\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\4jvYYv2-AwA=
Name conflict with blockshape chest
Duplicate class name Chest
Name conflict with blockshape piston
Duplicate class name Piston
Name conflict with blockshape ladder
Duplicate class name Ladder
Name conflict with blockshape door6
Duplicate class name Door6
Name conflict with blockshape double_plant
Duplicate class name DoublePlant
Name conflict with blockshape repeater
Duplicate class name Repeater
Name conflict with blockshape bubble_column
Duplicate class name BubbleColumn
Name conflict with blockshape door
Duplicate class name Door
Name conflict with blockshape vine
Duplicate class name Vine
Name conflict with blockshape door5
Duplicate class name Door5
Name conflict with blockshape slab
Duplicate class name Slab
Name conflict with blockshape slab_double
Duplicate class name SlabDouble
Name conflict with blockshape cross_texture0
Duplicate class name Cross0
Name conflict with blockshape piston_arm
Duplicate class name PistonArm
Name conflict with blockshape red_dust
Duplicate class name RedDust
Name conflict with blockshape comparator
Duplicate class name Comparator
Name conflict with blockshape pumpkin_lit
Duplicate class name PumpkinLit
Name conflict with blockshape furnace
Duplicate class name Furnace
Name conflict with blockshape cross_texture
Duplicate class name Cross
Name conflict with blockshape tree
Duplicate class name Tree
Name conflict with blockshape air
Duplicate class name Air
Name conflict with blockshape lilypad
Duplicate class name LilyPad
Name conflict with blockshape portal_frame
Duplicate class name PortalFrame
Name conflict with blockshape pumpkin_carved
Duplicate class name PumpkinCarved
Name conflict with blockshape door2
Duplicate class name Door2
Name conflict with blockshape farmland
Duplicate class name FarmLand
Name conflict with blockshape cake
Duplicate class name Cake
Name conflict with blockshape turtle_egg
Duplicate class name TurtleEgg
Name conflict with blockshape pressure_plate
Duplicate class name PressurePlate
Name conflict with blockshape enchanting_table
Duplicate class name EnchantingTable
Name conflict with blockshape cross_texture_green
Duplicate class name CrossGreen
Name conflict with blockshape door4
Duplicate class name Door4
Name conflict with blockshape pumpkin
Duplicate class name Pumpkin
Name conflict with blockshape cube
Duplicate class name Cube
Name conflict with blockshape door3
Duplicate class name Door3
Name conflict with blockshape fence
Duplicate class name Fence
Name conflict with blockshape water
Duplicate class name Water
Name conflict with blockshape greencube
Duplicate class name GreenCube
Name conflict with blockshape wall
Duplicate class name Wall
Name conflict with blockshape door1
Duplicate class name Door1
Name conflict with blockshape furnace_lit
Duplicate class name FurnaceLit
2022-07-20 13:37:33,992 - minecraft_model_reader - INFO - Downloading java launcher manifest file.
2022-07-20 13:37:34,168 - minecraft_model_reader - INFO - Finished downloading java launcher manifest file.
2022-07-20 13:37:51,027 - amulet_map_editor - INFO - Finished setting up texture atlas in OpenGL
Extra components found {}
2022-07-20 13:37:54,610 - pymctranslate - ERROR - Error converting block minecraft:chest[__version__=17959425,facing_direction=2] to universal in PyMCTranslate.Version(bedrock, (1, 19, 0)).
Traceback (most recent call last):
  File "PyMCTranslate\py3\api\version\translators\base.py", line 82, in _translate
  File "PyMCTranslate\py3\api\version\translate.py", line 337, in translate
  File "PyMCTranslate\py3\api\version\translate.py", line 942, in _translate
  File "PyMCTranslate\py3\api\version\translate.py", line 973, in objectify_nbt
  File "PyMCTranslate\py3\api\version\translate.py", line 980, in _objectify_nbt
  File "PyMCTranslate\py3\api\version\translate.py", line 980, in <dictcomp>
  File "PyMCTranslate\py3\api\version\translate.py", line 982, in _objectify_nbt
  File "PyMCTranslate\py3\api\version\translate.py", line 982, in <listcomp>
  File "PyMCTranslate\py3\api\version\translate.py", line 980, in _objectify_nbt
  File "PyMCTranslate\py3\api\version\translate.py", line 980, in <dictcomp>
  File "PyMCTranslate\py3\api\version\translate.py", line 980, in _objectify_nbt
  File "PyMCTranslate\py3\api\version\translate.py", line 980, in <dictcomp>
  File "PyMCTranslate\py3\api\version\translate.py", line 980, in _objectify_nbt
  File "PyMCTranslate\py3\api\version\translate.py", line 980, in <dictcomp>
  File "PyMCTranslate\py3\api\version\translate.py", line 980, in _objectify_nbt
  File "PyMCTranslate\py3\api\version\translate.py", line 980, in <dictcomp>
  File "PyMCTranslate\py3\api\version\translate.py", line 978, in _objectify_nbt
  File "amulet_nbt\amulet_cy_nbt.pyx", line 759, in amulet_nbt.amulet_cy_nbt.TAG_String.value.__get__
  File "amulet_nbt\amulet_cy_nbt.pyx", line 763, in amulet_nbt.amulet_cy_nbt.TAG_String.py_str.__get__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 3: invalid continuation byte
Extra components found {}
2022-07-20 13:37:57,372 - pymctranslate - WARNING - Could not find translation information for block minecraft:chest[__version__=17959425,facing_direction=2] from universal in PyMCTranslate.Version(java, (1, 19, 0)). If this is not a vanilla block ignore this message
Extra components found {}

The world size is currently 2.1 GB if that may be relevant.

**Comment by gentlegiantJGC** [comment]
Which version of Amulet are you using?

**Comment by batesjonathan** [comment]
Windows 0.9.6

**Comment by gentlegiantJGC** [comment]
The error log does not contain any errors that would explain why the program would hang.
Does this happen every time you switch to 2D view?
