### ISSUE TITLE
[Bug Report] Worlds don't fully load...

### ISSUE THREAD

**Issue by Diaa333** [Amulet-Team/Amulet-Map-Editor#775]
### Steps To Reproduce:
1. Open amulet_app
2. Click Open World
3. Drop down Bedrock saves list
4. Click on one of the saves
5. Click on 3D Editor
6. See screenshots below of resulting error (no error message, just worlds not fully loading)

### Environment:
- OS: Windows 10
- Minecraft Platform:  Bedrock 
- Minecraft Version: 1.19.21
- Amulet Version: 0.9.6

### Screenshots:
![Screenshot 2022-08-27 015430](https://user-images.githubusercontent.com/112234803/187017243-64bad567-3154-43a4-bd4a-31d2a2cec965.png)
![Screenshot 2022-08-27 015139](https://user-images.githubusercontent.com/112234803/187017245-d6fdb763-9fe3-498f-96b2-d1f60fdebda1.png)
![Screenshot 2022-08-27 014954](https://user-images.githubusercontent.com/112234803/187017246-3463e1c8-affc-4d5b-8b88-27f623130852.png)
![Screenshot 2022-08-27 014658](https://user-images.githubusercontent.com/112234803/187017247-92d286ab-ad7f-45e4-a4d7-844933852306.png)

**Comment by gentlegiantJGC** [comment]
Is this a marketplace world? If so we don't support these worlds.

**Comment by Diaa333** [comment]
Good evening,

Each screenshot is of a different world at load. One of them is a
Marketplace world, yes, but one of them is definitely not as it's one that
I started and made (the Blackstone roofed building with the cobblestone
path in front and the two towers on either side). As for the others, I'm
not sure but I doubt it as I downloaded them from links on the forums.

**Comment by ITikhonov** [comment]
With BlueTopia level

https://drive.google.com/drive/folders/0B6UY8ZW2V18SaDVFV2wyaHVtdE0?resourcekey=0-IQgUOiZZF-PG9az31dvt7g

unzipped into folder "dist/BlueTopia"

and amulet installed through

conda install amulet-map-editor

I run this script:
```
import amulet

level = amulet.level.load_level('dist/BlueTopia')
chunks = level.chunks
overworld = chunks.all_chunk_coords("minecraft:overworld")

all_chunks = list(overworld)

for i,(cx,cz) in enumerate(sorted(all_chunks)):
        chunk = chunks.get_chunk("minecraft:overworld", cx,cz)
```

It loads most of chunks but after some time it pops:

```
$ python report.py 
2022-08-29 10:23:13,249 - amulet_core - INFO - Loading level dist/BlueTopia
2022-08-29 10:23:27,681 - amulet_core - ERROR - Error loading chunk -303 7 minecraft:overworld
Traceback (most recent call last):
  File "/.../python3.9/site-packages/amulet/api/wrapper/format_wrapper.py", line 433, in _safe_load
    return meth(*args)
  File "/.../python3.9/site-packages/amulet/api/wrapper/format_wrapper.py", line 480, in _load_chunk
    chunk, block_palette = self._decode(
  File "/.../python3.9/site-packages/amulet/level/formats/leveldb_world/format.py", line 266, in _decode
    return interface.decode(cx, cz, raw_chunk_data, (bounds[0][1], bounds[1][1]))
  File "/.../python3.9/site-packages/amulet/level/formats/leveldb_world/interface/chunk/base_leveldb_interface.py", line 163, in decode
    state = chunk_data.pop(b"\x36", None)
AttributeError: 'bytes' object has no attribute 'pop'
Traceback (most recent call last):
  File "/.../python3.9/site-packages/amulet/api/wrapper/format_wrapper.py", line 433, in _safe_load
    return meth(*args)
  File "/.../python3.9/site-packages/amulet/api/wrapper/format_wrapper.py", line 480, in _load_chunk
    chunk, block_palette = self._decode(
  File "/.../python3.9/site-packages/amulet/level/formats/leveldb_world/format.py", line 266, in _decode
    return interface.decode(cx, cz, raw_chunk_data, (bounds[0][1], bounds[1][1]))
  File "/.../python3.9/site-packages/amulet/level/formats/leveldb_world/interface/chunk/base_leveldb_interface.py", line 163, in decode
    state = chunk_data.pop(b"\x36", None)
AttributeError: 'bytes' object has no attribute 'pop'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.../report.py", line 10, in <module>
    chunk = chunks.get_chunk("minecraft:overworld", cx,cz)
  File "/.../python3.9/site-packages/amulet/api/level/base_level/chunk_manager.py", line 187, in get_chunk
    return self._get_entry((dimension, cx, cz))
  File "/.../python3.9/site-packages/amulet/api/history/history_manager/database.py", line 158, in _get_entry
    ] = self._get_register_original_entry(key)
  File "/.../python3.9/site-packages/amulet/api/history/history_manager/database.py", line 166, in _get_register_original_entry
    entry = self._raw_get_entry(key)
  File "/.../python3.9/site-packages/amulet/api/level/base_level/chunk_manager.py", line 191, in _raw_get_entry
    chunk = self.level.level_wrapper.load_chunk(cx, cz, dimension)
  File "/.../python3.9/site-packages/amulet/api/wrapper/format_wrapper.py", line 452, in load_chunk
    return self._safe_load(
  File "/.../python3.9/site-packages/amulet/api/wrapper/format_wrapper.py", line 438, in _safe_load
    raise load_error(e) from e
amulet.api.errors.ChunkLoadError: 'bytes' object has no attribute 'pop'
2022-08-29 10:23:27,701 - amulet_core - INFO - Removing cache.
```

**Comment by ITikhonov** [comment]
```
$ conda list|grep amulet
amulet-core               1.8.1                    pypi_0    pypi
amulet-map-editor         0.9.6                    pypi_0    pypi
amulet-nbt                1.2.1                    pypi_0    pypi
```

**Comment by gentlegiantJGC** [comment]
@ITikhonov your issue looks like a different issue. Please open a new issue.

**Comment by gentlegiantJGC** [comment]
> As for the others, I'm not sure but I doubt it as I downloaded them from links on the forums.

Please can you provide links to the forum pages that you downloaded them from so that I can try and debug what the issue is.

**Comment by Diaa333** [comment]
One of them can be found here: https://www.planetminecraft.com/project/medieval-castle-bedrock/

Another here: https://www.planetminecraft.com/project/lakewell-kingdom/

The other 2 are the Marketplace world and my world that I started and made.

**Comment by Diaa333** [comment]
The one I started and made was having the random-chunks-not-loading issue before I even started building on it... Seed is -1937342845 and coords are -1880 125 700

**Comment by prismschism** [comment]
> The one I started and made was having the random-chunks-not-loading issue before I even started building on it... Seed is -1937342845 and coords are -1880 125 700

I am using a self made world on a seed custom seed that starts with a "-" as well. Could that have a negative effect? Other worlds seem unaffected except that one world I made

**Comment by Diaa333** [comment]
> > The one I started and made was having the random-chunks-not-loading issue before I even started building on it... Seed is -1937342845 and coords are -1880 125 700
> 
> I am using a self made world on a seed custom seed that starts with a "-" as well. Could that have a negative effect? Other worlds seem unaffected except that one world I made

Not the case; I just made another world that doesn't have the " - " in its seed - and completely flat at that so there wasn't exactly much to load - and I'm still having the same problem. It seems to be an issue with every world I try to open with this app. 

Although, there is something else I need to try... I need to try making one without Resource Packs applied, as I believe all the other ones I've tried have them applied, so I'm wondering if that could maybe be the issue?

I'll try this tomorrow and report my findings.

**Comment by gentlegiantJGC** [comment]
> One of them can be found here: https://www.planetminecraft.com/project/medieval-castle-bedrock/

This world loads as expected in Amulet. There was one error chunk which I have fixed in https://github.com/Amulet-Team/Amulet-Core/pull/218 but other than that it was fine.

> Another here: https://www.planetminecraft.com/project/lakewell-kingdom/

I can't find any issues loading this level either.

These two worlds are different worlds to the ones you have provided images for so the errors may be in a different location that I cannot find.

Please can you try reproducing your issues in the 0.10 beta version to see if the issue you are having still exists there.

**Comment by gabessdsp** [comment]
I am having an identical issue with a world generated in 1.19.22. Random chunks just won't load, at first I thought Amulet was just having issues generating chunks so I flew around a bit with a 16 chunk render distance to no avail. I am on V0.10.0b4

**Comment by gentlegiantJGC** [comment]
You must modify a chunk in Bedrock for the game to save it.
This bug ticket has user generated structures in the area that does not load so it is a different issue.

**Comment by Diaa333** [comment]
I'm sorry I didn't get to test the Resource Pack thing last night like I'd planned. Something came up. I will test it tomorrow night as well as getting you the coords for the screenshots I took, and also the part you mentioned about modifying the chunks to see if that might be the cause, since I downloaded those 2 worlds I wonder if it's reading them as not modified since I didn't do anything to them myself.

**Comment by gentlegiantJGC** [comment]
> I'm sorry I didn't get to test the Resource Pack thing last night like I'd planned. Something came up. I will test it tomorrow night as well as getting you the coords for the screenshots I took, and also the part you mentioned about modifying the chunks to see if that might be the cause, since I downloaded those 2 worlds I wonder if it's reading them as not modified since I didn't do anything to them myself.

All I need from you is links to worlds that are not marketplace worlds that look like your original post when opened in Amulet with screenshots of Amulet in each of the worlds.

Three of the original ones you linked are marketplace worlds which we do not support.

**Comment by Diaa333** [comment]
> > I'm sorry I didn't get to test the Resource Pack thing last night like I'd planned. Something came up. I will test it tomorrow night as well as getting you the coords for the screenshots I took, and also the part you mentioned about modifying the chunks to see if that might be the cause, since I downloaded those 2 worlds I wonder if it's reading them as not modified since I didn't do anything to them myself.
> 
> All I need from you is links to worlds that are not marketplace worlds that look like your original post when opened in Amulet with screenshots of Amulet in each of the worlds.
> 
> Three of the original ones you linked are marketplace worlds which we do not support.

I only linked 2, and I'm pretty sure neither are Marketplace worlds. You even said in your last reply that they were working as intended... but I was going to get you the exact coordinates of where I was since you said they may be different locations. So I'm confused that you're now changing your story...

Also, sorry for the lack of activity as well as delayed responses; I've been sick.

**Comment by gentlegiantJGC** [comment]
I meant the images in your original post. You sent 4 images of different worlds and three of them are marketplace worlds.

**Comment by Diaa333** [comment]
How can you say they are, when I sent you links to them, and you then said
they're not?

The links are of two of the same things I screenshotted.

I said one of the acreenshots is Marketplace, and one is my own creation,
but the other two, that I linked, are not.

And the two I linked, you said are working as intended. So I'm still
confused.

Once I clock out of work in a couple more hours, I'll screenshot everything
to show you...

**Comment by gentlegiantJGC** [comment]
Here are the three that you sent images of in your first post that I think are marketplace worlds based on the world names.

https://www.minecraft.net/en-us/marketplace/pdp?id=a17ed164-50d8-4152-9937-8b825eafaa4f
https://www.minecraft.net/en-us/marketplace/pdp?id=5a699847-e493-4968-9efe-9298706192fa
https://www.minecraft.net/en-us/marketplace/pdp?id=11b8af30-4bc9-4b4a-8d6c-4945efe642cc

The two planet minecraft links you sent had different world names to the images you sent.

We have released 0.10 which should notify you if a world is a marketplace world and that it cannot be opened.

**Comment by Diaa333** [comment]
Ok, the latter two are accurate - I didn't know that since I found them on
the forums. The first one, however, I don't think is the same, but I'll
have to check later when I'm off work. I'll also update the app and see if
that helps. Thanks, and I apologize again.

**Comment by Diaa333** [comment]
Sorry again for the late reply - I've been sick, still, and wound up in the ER over it...

Just checked the first link and it's not the same. 

I'm updating the app now.

**Comment by Diaa333** [comment]
Updated and tried to open a world I hadn't screenshotted (another one I got off the forums) and it didn't give me an error about it being a Marketplace world, but still has missing chunks...

![image](https://user-images.githubusercontent.com/112234803/191282119-2dbd9c55-16ea-4467-95da-e3cf387290e0.png)

**Comment by Diaa333** [comment]
It also let me open Gendry's Tavern without a warning but same issue.

**Comment by Diaa333** [comment]
Also, no change to the world I started myself:

![image](https://user-images.githubusercontent.com/112234803/191282970-7e92ecf5-b29b-4462-9a16-57591c3befdf.png)

**Comment by gentlegiantJGC** [comment]
No worries.
Can you send the links for both of those so I can look into them.
I think you have sent the latter one before but I can't see it

**Comment by Diaa333** [comment]
Both of those? 

The second one I spoke of, but without a screenshot, is "Gendry's Tavern", which you linked and said was a Marketplace world. I was just telling you that it didn't tell me it was a Marketplace world like you said it should. I don't know if that's because I got it through the forums rather than the Marketplace or what. 

The third one I spoke of, which is the second screenshot I posted, was one I said I started. There is no link. It is a new world I started through "New World" and created myself. I did not download it.

First one, Stonehill Castle: https://www.planetminecraft.com/project/stonehill-castle-4407920/
