### ISSUE TITLE
[Bug Report] Can't load 3D World

### ISSUE THREAD

**Issue by WoMspace** [Amulet-Team/Amulet-Map-Editor#778]
### Current Behaviour:

Error pops up showing "Couldn't create OpenGL context" when selecting "3D Editor" tab
### Expected behavior:

The 3D editor loads
### Steps To Reproduce:

1. Load world
2. Select 3D Editor
3. Error

### Environment:

- OS: Windows 11
- Minecraft Platform: Java
- Minecraft Version: tested 1.17.1 to 1.19
- Amulet Version: V0.9.6
- GPU: Radeon RX 5700XT
- GPU Driver: 22.8.2

### Additional context

Error log:
```
GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGenTextures,
	pyArgs = (
		1,
		<object object at 0x0000027F8DCC4520>,
	),
	cArgs = (1, array([0], dtype=uint32)),
	cArguments = (1, array([0], dtype=uint32))
)
Traceback (most recent call last):
  File "OpenGL\latebind.py", line 43, in __call__
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 157, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 50, in enable
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 93, in __init__
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 58, in __init__
  File "amulet_map_editor\api\opengl\canvas\event_canvas.py", line 12, in __init__
  File "amulet_map_editor\api\opengl\canvas\canvas.py", line 47, in __init__
  File "OpenGL\latebind.py", line 47, in __call__
  File "OpenGL\wrapper.py", line 678, in wrapperCall
  File "OpenGL\wrapper.py", line 671, in wrapperCall
  File "OpenGL\platform\baseplatform.py", line 415, in __call__
  File "OpenGL\error.py", line 234, in glCheckError
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGenTextures,
	pyArgs = (
		1,
		<object object at 0x0000027F8DCC4520>,
	),
	cArgs = (1, array([0], dtype=uint32)),
	cArguments = (1, array([0], dtype=uint32))
)
```
### Screenshots

![image](https://user-images.githubusercontent.com/22845656/188243827-002b3c51-a981-468b-91b9-1a3399b5ef94.png)
![image](https://user-images.githubusercontent.com/22845656/188243838-c17285b9-4e40-44a2-8158-6cf98505750a.png)

**Comment by gentlegiantJGC** [comment]
This is fixed in the latest 0.10 beta
