### ISSUE TITLE
[Feature Request] Does it support linux arm64?

### ISSUE THREAD

**Issue by xc1984759471** [Amulet-Team/Amulet-Map-Editor#784]
### The Problem
  When will it be able to adapt to arm64 linux?
### Feature Description
I'm using debian based on arm64, although it can be successfully installed with pip, I got the following error when running:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/amulet_map_editor/__main__.py", line 14, in <module>
    from amulet_map_editor.api.framework import AmuletApp
  File "/usr/local/lib/python3.10/dist-packages/amulet_map_editor/api/framework/__init__.py", line 1, in <module>
    from .amulet_ui import AmuletUI
  File "/usr/local/lib/python3.10/dist-packages/amulet_map_editor/api/framework/amulet_ui.py", line 6, in <module>
    from amulet.api.errors import LoaderNoneMatched
  File "/usr/local/lib/python3.10/dist-packages/amulet/__init__.py", line 15, in <module>
    from amulet.level.load import load_level, load_format
  File "/usr/local/lib/python3.10/dist-packages/amulet/level/__init__.py", line 1, in <module>
    from .load import load_format, load_level
  File "/usr/local/lib/python3.10/dist-packages/amulet/level/load.py", line 6, in <module>
    from amulet.api.level import World, Structure
  File "/usr/local/lib/python3.10/dist-packages/amulet/api/level/__init__.py", line 1, in <module>
    from .base_level import BaseLevel
  File "/usr/local/lib/python3.10/dist-packages/amulet/api/level/base_level/__init__.py", line 1, in <module>
    from .base_level import BaseLevel
  File "/usr/local/lib/python3.10/dist-packages/amulet/api/level/base_level/base_level.py", line 30, in <module>
    from .chunk_manager import ChunkManager
  File "/usr/local/lib/python3.10/dist-packages/amulet/api/level/base_level/chunk_manager.py", line 12, in <module>
    from amulet.api.cache import get_cache_db
  File "/usr/local/lib/python3.10/dist-packages/amulet/api/cache.py", line 7, in <module>
    from amulet.libs.leveldb import LevelDB
  File "/usr/local/lib/python3.10/dist-packages/amulet/libs/leveldb/__init__.py", line 1, in <module>
    from .leveldb import LevelDB, LevelDBException
  File "/usr/local/lib/python3.10/dist-packages/amulet/libs/leveldb/leveldb.py", line 22, in <module>
    ldb = ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.10/dist-packages/amulet/libs/leveldb/leveldb_mcpe_linux_x86_64.so: cannot open shared object file: No such file or directory
Failed to import requirements. Check that you extracted correctly.
/usr/local/lib/python3.10/dist-packages/amulet/libs/leveldb/leveldb_mcpe_linux_x86_64.so: cannot open shared object file: No such file or directory
It can be seen that it is looking for x86_64 libraries, but arm64 does not support it. Are there any plans to adapt to other architectures?

**Comment by gentlegiantJGC** [comment]
I have recently refactored the leveldb code which should fix this but I have not integrated it yet.
In the future if there are no compatible pre-built versions it will compile it on your computer.

Until then you can try compiling it yourself
https://github.com/Amulet-Team/leveldb-mcpe

**Comment by xc1984759471** [comment]
OK. After recompiling leveldb and replacing the original x86_64 library, it can be run.
However, I still hope to be able to enter the master branch as soon as possible.
![截图_2022-09-12_18-14-10](https://user-images.githubusercontent.com/53083866/189629739-7628635a-3322-4073-9e0b-4abc1181e6bb.png)
![截图_2022-09-12_18-07-08](https://user-images.githubusercontent.com/53083866/189629769-f0dac24b-8be9-4920-b7a4-2b40a4b2c5e5.png)

**Comment by gentlegiantJGC** [comment]
I think this issue should be fixed in 0.10.2b3 now that I have integrated the new LevelDB library.
If your platform does not have a pre-built version it will compile all of the LevelDB code on your computer.
