### ISSUE TITLE
[Bug Report] Cannot launch UI on ARM-based systems

### ISSUE THREAD

**Issue by partywarp** [Amulet-Team/Amulet-Map-Editor#813]
## Bug Report
Amulet is not compatible with M1
### Current Behaviour:
Cannot launch Amulet Map Editor

### Expected behavior:
Launches Amulet Map Editor

### Steps To Reproduce:
1. Obtain an ARM-based device
2. Follow setup instructions on [amuletmc.com](amuletmc.com/installing-from-source)
3. run `python3 -m amulet_map_editor`
3. see error (in short `(mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))`)

### Environment:

- OS: macOS Monterey 12.6
- Minecraft Platform: Java
- Minecraft Version: 1.19
- Amulet Version: Latest release

### Additional context
iMac (24-inch, M1, 2021)
Chip Apple M1
Memory 8GB
Startup Disk Macintosh HD
Serial Number ############

### Screenshots

```
(amulet-env) #########@######-imac ~ % python3 -m amulet_map_editor
Traceback (most recent call last):
  File "/Users/#########/amulet-env/lib/python3.10/site-packages/amulet_map_editor/__main__.py", line 14, in <module>
    from amulet_map_editor.api.framework import AmuletApp
  File "/Users/#########/amulet-env/lib/python3.10/site-packages/amulet_map_editor/api/framework/__init__.py", line 1, in <module>
    from .amulet_ui import AmuletUI
  File "/Users/#########/amulet-env/lib/python3.10/site-packages/amulet_map_editor/api/framework/amulet_ui.py", line 6, in <module>
    from amulet.api.errors import LoaderNoneMatched
  File "/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/__init__.py", line 15, in <module>
    from amulet.level.load import load_level, load_format
  File "/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/level/__init__.py", line 1, in <module>
    from .load import load_format, load_level
  File "/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/level/load.py", line 6, in <module>
    from amulet.api.level import World, Structure
  File "/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/api/level/__init__.py", line 1, in <module>
    from .base_level import BaseLevel
  File "/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/api/level/base_level/__init__.py", line 1, in <module>
    from .base_level import BaseLevel
  File "/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/api/level/base_level/base_level.py", line 30, in <module>
    from .chunk_manager import ChunkManager
  File "/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/api/level/base_level/chunk_manager.py", line 12, in <module>
    from amulet.api.cache import get_cache_db
  File "/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/api/cache.py", line 7, in <module>
    from amulet.libs.leveldb import LevelDB
  File "/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/libs/leveldb/__init__.py", line 1, in <module>
    from .leveldb import LevelDB, LevelDBException
  File "/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/libs/leveldb/leveldb.py", line 22, in <module>
    ldb = ctypes.cdll.LoadLibrary(lib_path)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/libs/leveldb/leveldb_mcpe_macosx_10_9_x86_64.dylib, 0x0006): tried: '/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/libs/leveldb/leveldb_mcpe_macosx_10_9_x86_64.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
Failed to import requirements. Check that you extracted correctly.
dlopen(/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/libs/leveldb/leveldb_mcpe_macosx_10_9_x86_64.dylib, 0x0006): tried: '/Users/#########/amulet-env/lib/python3.10/site-packages/amulet/libs/leveldb/leveldb_mcpe_macosx_10_9_x86_64.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
Press ENTER to continue.
(amulet-env) #########@######-imac ~ %
```

**Comment by gentlegiantJGC** [comment]
Please try the latest beta. This issue should be fixed there.

**Comment by ViRb3** [comment]
Also you are using Python 3.10, you need `Python <3.10, >=3.6`.
