### ISSUE TITLE
[Bug Report] My Own Map is Supposed to Come From the Marketplace

### ISSUE THREAD

**Issue by awaAlpha** [Amulet-Team/Amulet-Map-Editor#818]
Current Behaviour:
The maps are supposede to come from the marketplace, but it is my own map. I make by myself.

Environment:
OS: Windows 10
Minecraft Platform: Bedrock
Minecraft Version: 1.18.1.0.0 and 1.18.2.0.0 
Amulet Version: 0.10.3

And it  pops up a issue:

SCREENSHOT:
![image](https://user-images.githubusercontent.com/77965901/198835138-43375088-62ec-45ac-9413-394457bec322.png)

FULL DETAILS:
It looks like this world is from the marketplace.
These worlds are encrypted and cannot be edited.
Traceback (most recent call last):
  File "amulet\level\formats\leveldb_world\format.py", line 345, in _reload_world
  File "src\\leveldb\\_leveldb.pyx", line 214, in leveldb._leveldb.LevelDB.__init__
leveldb._leveldb.LevelDBEncrypted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "amulet_map_editor\api\framework\amulet_ui.py", line 183, in open_level
  File "amulet_map_editor\api\framework\pages\world_page.py", line 71, in __init__
  File "amulet\level\load.py", line 32, in load_level
  File "amulet\api\level\world.py", line 14, in __init__
  File "amulet\api\level\base_level\base_level.py", line 63, in __init__
  File "amulet\api\wrapper\format_wrapper.py", line 337, in open
  File "amulet\level\formats\leveldb_world\format.py", line 397, in _open
  File "amulet\level\formats\leveldb_world\format.py", line 382, in _reload_world
leveldb._leveldb.LevelDBException: It looks like this world is from the marketplace.
These worlds are encrypted and cannot be edited.

**Comment by gentlegiantJGC** [comment]
Please can you share the world with me so that I can look into it.

**Comment by awaAlpha** [comment]
No longer need, my friend. I solve this problem. I'm sorry, the map cannot open normally cause the CURRENT log has been enciphered. Sorry to bother you guys.
However, it's interesting, it can open the real map from the marketplace such as spongebob DLC😉
