### ISSUE TITLE
[Bug Report] error when trying to launch Amulet in Termux

### ISSUE THREAD

**Issue by Max-RM** [Amulet-Team/Amulet-Map-Editor#822]
https://github.com/termux/termux-app Termux an application that allows users to run Linux on an Android device.

for a long time there was a problem related to the build Wheel. now that it has been fixed a new bug has appeared: 
![Screenshot_2022-11-01-00-52-03-070_com termux](https://user-images.githubusercontent.com/81485476/199169436-c55c8a6f-dd2b-4e5f-828a-1d1ffc693034.jpg)

the entire installation/update of Amulet Map Editor was completed without any problems this time. but when using the command: 
`python3 -m amulet_map_editor` to run Amulet,
an error has occurred:

`Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.9/dist-packages/amulet_map_editor/__init__.py", line 10, in <module>
    from amulet_map_editor.api.framework.app import open_level, close_level
  File "/usr/local/lib/python3.9/dist-packages/amulet_map_editor/api/framework/__init__.py", line 1, in <module>
    from .app import AmuletApp
  File "/usr/local/lib/python3.9/dist-packages/amulet_map_editor/api/framework/app.py", line 2, in <module>
    from . import amulet_ui
  File "/usr/local/lib/python3.9/dist-packages/amulet_map_editor/api/framework/amulet_ui.py", line 8, in <module>
    from amulet.api.errors import LoaderNoneMatched
  File "/usr/local/lib/python3.9/dist-packages/amulet/__init__.py", line 14, in <module>
    from .api import *
  File "/usr/local/lib/python3.9/dist-packages/amulet/api/__init__.py", line 1, in <module>
    from .block import *
  File "/usr/local/lib/python3.9/dist-packages/amulet/api/block.py", line 6, in <module>
    from amulet_nbt import ByteTag, ShortTag, IntTag, LongTag, StringTag, from_snbt
  File "/usr/local/lib/python3.9/dist-packages/amulet_nbt/__init__.py", line 36, in <module>
    from ._array import (
  File "amulet_nbt/_array.pyx", line 1, in init amulet_nbt._array
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).`

**Comment by Max-RM** [comment]
Was fixed after use `pip install -U numpy`

![Screenshot_2022-11-01-14-35-32-229_com termux](https://user-images.githubusercontent.com/81485476/199209327-88e7a081-0b13-4ebd-8096-a6f170d4ac50.jpg)
![Screenshot_2022-11-01-14-36-33-148_com realvnc viewer android](https://user-images.githubusercontent.com/81485476/199209332-b151ee41-1a91-4a06-96b5-1ee71d9f1185.jpg)
![Screenshot_2022-11-01-14-38-29-678_com realvnc viewer android](https://user-images.githubusercontent.com/81485476/199209336-0a7f651f-82b8-415b-852c-cfb967a975b1.jpg)

**Comment by Max-RM** [comment]
New error while open world
![Screenshot_2022-11-01-14-53-43-697_com realvnc viewer android](https://user-images.githubusercontent.com/81485476/199209470-8b9117d5-9414-4238-991c-cd6992a66c4d.jpg)
![Screenshot_2022-11-01-15-00-22-569_com realvnc viewer android](https://user-images.githubusercontent.com/81485476/199209478-2f4f6a5c-fd60-4ea4-be81-f9e4039048ed.jpg)

**Comment by gentlegiantJGC** [comment]
I will fix the numpy bug. It looks like the latter photos are a different issue.
