### ISSUE TITLE
[Bug Report] macOS issue loading 3D editor in 0.10.5

### ISSUE THREAD

**Issue by DBarned** [Amulet-Team/Amulet-Map-Editor#832]
## Bug Report
I can open 0.10.5, but after opening a world and clicking to view the 3D editor view, it is showing a new window with: 

```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/programs/edit/edit.py", line 108, in _thread_setup
    self._update_loading(self._canvas.thread_setup())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/programs/edit/edit.py", line 78, in _update_loading
    for arg in it:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py", line 199, in thread_setup
    for i in self._opengl_resource_pack.setup():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/resource_pack/resource_pack.py", line 144, in setup
    self._image = numpy.asarray(atlas, numpy.uint8).ravel()
TypeError: __array__() takes 1 positional argument but 2 were given
```

After dismissing this, the app crashes shortly after.

The world is from Minecraft version 1.19.41 (Bedrock). 

### Current Behaviour:

Can’t open 3D editor after opening world. 

### Expected behavior:

Being able to open 3D editor. 

### Steps To Reproduce:

1. Open Amulet on intel based Mac with macOS 12. 
2. Open a 1.19.41 (Bedrock) world. 
3. Try to view 3D editor tab. 

### Environment:

- OS: OSX
- Minecraft Platform: Bedrock
- Minecraft Version:  1.19.41 (Bedrock)
- Amulet Version:  0.10.5

**Comment by gentlegiantJGC** [comment]
I think this is a bug in the Pillow library which handles images.
Can you run the following command and reply with the output.
`python3 -m pip list`

**Comment by gentlegiantJGC** [comment]
I have added some code that I think should work around that bug.
Would still be useful to know the version of Pillow you have installed.

**Comment by DBarned** [comment]
Thanks for looking in to it! This is my output: 

``` 
Package                 Version
----------------------- ---------
amulet-core             1.9.10
amulet-leveldb          1.0.0b4
amulet-map-editor       0.10.5
amulet-nbt              2.0.2
certifi                 2021.5.30
minecraft-resource-pack 1.3.2
mutf8                   1.0.6
numpy                   1.23.4
packaging               21.3
pi                      0.1.2
Pillow                  8.3.0
pip                     22.3.1
portalocker             2.4.0
PyMCTranslate           1.2.8
PyOpenGL                3.1.5
PyOpenGL-accelerate     3.1.5
pyparsing               3.0.9
setuptools              56.0.0
six                     1.16.0
wheel                   0.36.2
wxPython                4.1.1
```

**Comment by gentlegiantJGC** [comment]
Updating your version of pillow should fix it.
`python3 -m pip install Pillow --upgrade`

**Comment by DBarned** [comment]
Thanks. I've tried that, and there's progress. It doesn't open the new windows and show me an error, and it does load in the tab contents, but it doesn't render in the world. See attached image. 


![Screenshot 2022-11-15 at 18 08 42](https://user-images.githubusercontent.com/8189774/201994484-6623b1f5-eda1-44d3-b2b9-afc4dda9974e.png)


I've tried on a 1.19.41 world and the above 1.19.31 world.



Terminal shows the following:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 329, in _on_draw
    self.canvas.renderer.draw_level()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/renderer.py", line 228, in draw_level
    self.render_world.draw(self.canvas.camera.transformation_matrix)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/level/level.py", line 273, in draw
    self._chunk_manager.draw(camera_matrix, self.camera_location)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/level/region.py", line 96, in draw
    region.draw(camera_matrix, cam_cx, cam_cz)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/level/region.py", line 272, in draw
    self._create_geometry()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/level/region.py", line 252, in _create_geometry
    self._setup()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/tri_mesh.py", line 90, in _setup
    self._shader = get_shader(self.context_identifier, self.shader_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/shaders/__init__.py", line 60, in get_shader
    shader = compile_shader()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/shaders/__init__.py", line 49, in compile_shader
    _load_shader(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/shaders/__init__.py", line 73, in _load_shader
    return OpenGL.GL.shaders.compileShader(shader, shader_type)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/OpenGL/GL/shaders.py", line 235, in compileShader
    raise ShaderCompilationError(
OpenGL.GL.shaders.ShaderCompilationError: ('Shader compile failure (0): b"WARNING: 0:2: extension \'GL_ARB_explicit_attrib_location\' is not supported\\nERROR: 0:4: \'layout\' : syntax error: syntax error\\n"', [b'#version 120\r\n#extension GL_ARB_explicit_attrib_location : enable\r\n\r\nlayout(location = 0) in vec3 positions;\r\nlayout(location = 1) in vec2 vTexCoord;\r\nlayout(location = 2) in vec4 vTexOffset;\r\nlayout(location = 3) in vec3 vTint;\r\n\r\nvarying vec2 fTexCoord;\r\nvarying vec4 fTexOffset;\r\nvarying vec3 fTint;\r\n\r\nuniform mat4 transformation_matrix;\r\n\r\nvoid main(){\r\n    gl_Position = transformation_matrix * vec4(positions, 1.0);\r\n    fTexCoord = vTexCoord;\r\n    fTexOffset = vTexOffset;\r\n    fTint = vTint;\r\n}'], GL_VERTEX_SHADER)
```

**Comment by gentlegiantJGC** [comment]
I am tracking that issue in #597

**Comment by RustyKnight** [comment]
I'm having a simular issue when running on non-M1 Macs - don't know if it's related

MacOS Monterey (12.6) MacBook Pro (16", 2019); 2.6GHz 6-Core Intel Core i7
MacOS Ventura (13.1 Beta) MacBook Pro (16", 2017); 3.1 GHz Quad-Core Intel Core i7

Minecraft Java 1.19 world

```
❯ python3 -m amulet_map_editor                                                                                                                                                                                     
INFO - PyMCTranslate Version 205
INFO - Could not find loader for /Users/shane.whitehead/Downloads/Minecraft/test/worlds Could not find a matching format for /Users/shane.whitehead/Downloads/Minecraft/test/worlds
INFO - Could not find loader for /Users/shane.whitehead/Downloads/Minecraft/test/worlds Could not find a matching format for /Users/shane.whitehead/Downloads/Minecraft/test/worlds
INFO - Could not find loader for /Users/shane.whitehead/Downloads/Minecraft/test/worlds Could not find a matching format for /Users/shane.whitehead/Downloads/Minecraft/test/worlds
INFO - Could not find loader for /Users/shane.whitehead/Downloads/Minecraft/test/worlds Could not find a matching format for /Users/shane.whitehead/Downloads/Minecraft/test/worlds
INFO - Loading level /Users/shane.whitehead/Downloads/KidsCraft
INFO - Loading level /Users/shane.whitehead/Downloads/KidsCraft
INFO - OpenGL_accelerate module loaded
INFO - OpenGL_accelerate module loaded
INFO - Using accelerated ArrayDatatype
INFO - Using accelerated ArrayDatatype
INFO - Downloading java launcher manifest file.
INFO - Downloading java launcher manifest file.
INFO - Finished downloading java launcher manifest file.
INFO - Finished downloading java launcher manifest file.
INFO - Creating texture atlas
INFO - Creating texture atlas
INFO - Trying to pack textures into image of size 4096x4096
INFO - Trying to pack textures into image of size 4096x4096
INFO - Successfully packed textures into an image of size 4096x4096
INFO - Successfully packed textures into an image of size 4096x4096
INFO - Finished creating texture atlas
INFO - Finished creating texture atlas
INFO - OpenGL Version 2.1 ATI-4.8.101
INFO - OpenGL Version 2.1 ATI-4.8.101
INFO - Finished setting up texture atlas in OpenGL
INFO - Finished setting up texture atlas in OpenGL
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 327, in _on_draw
    self.canvas.renderer.draw_sky_box()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/renderer.py", line 224, in draw_sky_box
    self.sky_box.draw(self.canvas.camera.transformation_matrix)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/sky_box.py", line 63, in draw
    super().draw(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/tri_mesh.py", line 161, in draw
    self._setup()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/mesh/tri_mesh.py", line 90, in _setup
    self._shader = get_shader(self.context_identifier, self.shader_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/shaders/__init__.py", line 60, in get_shader
    shader = compile_shader()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/shaders/__init__.py", line 49, in compile_shader
    _load_shader(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/amulet_map_editor/api/opengl/shaders/__init__.py", line 73, in _load_shader
    return OpenGL.GL.shaders.compileShader(shader, shader_type)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/OpenGL/GL/shaders.py", line 235, in compileShader
    raise ShaderCompilationError(
OpenGL.GL.shaders.ShaderCompilationError: ('Shader compile failure (0): b"WARNING: 0:2: extension \'GL_ARB_explicit_attrib_location\' is not supported\\nERROR: 0:4: \'layout\' : syntax error: syntax error\\n"', [b'#version 120\r\n#extension GL_ARB_explicit_attrib_location : enable\r\n\r\nlayout(location = 0) in vec3 positions;\r\nlayout(location = 1) in vec2 vTexCoord;\r\nlayout(location = 2) in vec4 vTexOffset;\r\nlayout(location = 3) in vec3 vTint;\r\n\r\nvarying vec2 fTexCoord;\r\nvarying vec4 fTexOffset;\r\nvarying vec3 fTint;\r\n\r\nuniform mat4 transformation_matrix;\r\n\r\nvoid main(){\r\n    gl_Position = transformation_matrix * vec4(positions, 1.0);\r\n    fTexCoord = vTexCoord;\r\n    fTexOffset = vTexOffset;\r\n    fTint = vTint;\r\n}'], GL_VERTEX_SHADER)
```
