### ISSUE TITLE
Importing sponge schem gives the following error

### ISSUE THREAD

**Issue by zaPure** [Amulet-Team/Amulet-Map-Editor#841]
**BlockEntities must be a ListTag of compound tags.**
Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\plugins\tools\import_tool.py", line 68, in _on_open_file
  File "amulet\level\load.py", line 34, in load_level
  File "amulet\api\level\structure.py", line 17, in __init__
  File "amulet\api\level\base_level\base_level.py", line 63, in __init__
  File "amulet\api\wrapper\format_wrapper.py", line 337, in open
  File "amulet\api\wrapper\structure_format_wrapper.py", line 88, in _open
  File "amulet\level\formats\sponge_schem\format_wrapper.py", line 209, in open_from
amulet.level.formats.sponge_schem.format_wrapper.SpongeSchemReadError: BlockEntities must be a ListTag of compound tags.

trying to import file generated by https://beta.cubical.xyz/

**Comment by gentlegiantJGC** [comment]
Thanks for reporting it. I had forgotten because they didn't open a report here.

**Comment by gentlegiantJGC** [comment]
It looks like they are exporting empty lists with a null type. I will add a fix for it.
