### ISSUE TITLE
3D Editor Not Responding

### ISSUE THREAD

**Issue by RicPlayzGamez** [Amulet-Team/Amulet-Map-Editor#846]
## Bug Report
 When I Was Starting To Edit My World On 3D Editor, Always Not Responding, I Format My Laptop Still Not Working
### Expected behavior:
 Should Be Loading And i should have edited my world

### Environment:

- OS: Windows
- Minecraft Platform: Bedrock
- Minecraft Version: 1.19.5002.0
- Amulet Version: V0.16.0
![Screenshot (2)](https://user-images.githubusercontent.com/108918425/206881186-308e11ce-dbab-4f2d-b3aa-93c1a525c6cf.png)

**Comment by RicPlayzGamez** [comment]
https://user-images.githubusercontent.com/108918425/206886840-4b653200-49b1-401c-ad1e-e8ea7adbb9c4.mp4

here's the truth bug issue for the 3d editor

**Comment by gentlegiantJGC** [comment]
Are there any errors in the console?

**Comment by KnechteVino** [comment]
> Are there any errors in the console?
Same problem here:

`INFO - Creating texture atlas
INFO - Trying to pack textures into image of size 4096x4096
INFO - Successfully packed textures into an image of size 4096x4096
INFO - Finished creating texture atlas
INFO - OpenGL Version 4.4.0 - Build 21.20.16.4727
ERROR - Error loading chunk 2 -5 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
INFO - Error loading chunk (2, -5)
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 174, in create_geometry
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 91, in chunk
  File "amulet\api\level\base_level\base_level.py", line 582, in get_chunk
  File "amulet\api\level\base_level\chunk_manager.py", line 192, in get_chunk
  File "amulet\api\history\history_manager\database.py", line 158, in _get_entry
  File "amulet\api\history\history_manager\database.py", line 166, in _get_register_original_entry
  File "amulet\api\level\base_level\chunk_manager.py", line 196, in _raw_get_entry
  File "amulet\api\wrapper\format_wrapper.py", line 466, in load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 447, in _safe_load
amulet.api.errors.ChunkLoadError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 2 -5 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 3 -5 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
INFO - Error loading chunk (3, -5)
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 174, in create_geometry
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 91, in chunk
  File "amulet\api\level\base_level\base_level.py", line 582, in get_chunk
  File "amulet\api\level\base_level\chunk_manager.py", line 192, in get_chunk
  File "amulet\api\history\history_manager\database.py", line 158, in _get_entry
  File "amulet\api\history\history_manager\database.py", line 166, in _get_register_original_entry
  File "amulet\api\level\base_level\chunk_manager.py", line 196, in _raw_get_entry
  File "amulet\api\wrapper\format_wrapper.py", line 466, in load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 447, in _safe_load
amulet.api.errors.ChunkLoadError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 2 -4 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 92
INFO - Finished setting up texture atlas in OpenGL
ERROR - Error loading chunk 2 -4 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 92
ERROR - Error loading chunk 3 -5 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 2 -4 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 92
INFO - Error loading chunk (2, -4)
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 92

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 174, in create_geometry
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 91, in chunk
  File "amulet\api\level\base_level\base_level.py", line 582, in get_chunk
  File "amulet\api\level\base_level\chunk_manager.py", line 192, in get_chunk
  File "amulet\api\history\history_manager\database.py", line 158, in _get_entry
  File "amulet\api\history\history_manager\database.py", line 166, in _get_register_original_entry
  File "amulet\api\level\base_level\chunk_manager.py", line 196, in _raw_get_entry
  File "amulet\api\wrapper\format_wrapper.py", line 466, in load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 447, in _safe_load
amulet.api.errors.ChunkLoadError: Invalid compression type 92
ERROR - Error loading chunk 0 -4 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 61
ERROR - Error loading chunk 2 -4 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 92
ERROR - Error loading chunk 2 -5 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 2 -7 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 2 -5 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 4 -6 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 3 -5 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 4 -6 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
INFO - Error loading chunk (4, -6)
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 174, in create_geometry
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 91, in chunk
  File "amulet\api\level\base_level\base_level.py", line 582, in get_chunk
  File "amulet\api\level\base_level\chunk_manager.py", line 192, in get_chunk
  File "amulet\api\history\history_manager\database.py", line 158, in _get_entry
  File "amulet\api\history\history_manager\database.py", line 166, in _get_register_original_entry
  File "amulet\api\level\base_level\chunk_manager.py", line 196, in _raw_get_entry
  File "amulet\api\wrapper\format_wrapper.py", line 466, in load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 447, in _safe_load
amulet.api.errors.ChunkLoadError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 3 -5 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 4 -6 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 4 -2 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 2 -4 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 92
ERROR - Error loading chunk 0 -4 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 61
ERROR - Error loading chunk 0 -4 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 61
INFO - Error loading chunk (0, -4)
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 61

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 174, in create_geometry
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 91, in chunk
  File "amulet\api\level\base_level\base_level.py", line 582, in get_chunk
  File "amulet\api\level\base_level\chunk_manager.py", line 192, in get_chunk
  File "amulet\api\history\history_manager\database.py", line 158, in _get_entry
  File "amulet\api\history\history_manager\database.py", line 166, in _get_register_original_entry
  File "amulet\api\level\base_level\chunk_manager.py", line 196, in _raw_get_entry
  File "amulet\api\wrapper\format_wrapper.py", line 466, in load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 447, in _safe_load
amulet.api.errors.ChunkLoadError: Invalid compression type 61
ERROR - Error loading chunk 0 -4 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 61
ERROR - Error loading chunk 2 -7 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 2 -7 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
INFO - Error loading chunk (2, -7)
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 174, in create_geometry
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 91, in chunk
  File "amulet\api\level\base_level\base_level.py", line 582, in get_chunk
  File "amulet\api\level\base_level\chunk_manager.py", line 192, in get_chunk
  File "amulet\api\history\history_manager\database.py", line 158, in _get_entry
  File "amulet\api\history\history_manager\database.py", line 166, in _get_register_original_entry
  File "amulet\api\level\base_level\chunk_manager.py", line 196, in _raw_get_entry
  File "amulet\api\wrapper\format_wrapper.py", line 466, in load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 447, in _safe_load
amulet.api.errors.ChunkLoadError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 2 -7 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 4 -6 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 5 -6 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 88
ERROR - Error loading chunk 5 -6 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 88
INFO - Error loading chunk (5, -6)
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 88

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 174, in create_geometry
  File "amulet_map_editor\api\opengl\mesh\level\chunk\chunk.py", line 91, in chunk
  File "amulet\api\level\base_level\base_level.py", line 582, in get_chunk
  File "amulet\api\level\base_level\chunk_manager.py", line 192, in get_chunk
  File "amulet\api\history\history_manager\database.py", line 158, in _get_entry
  File "amulet\api\history\history_manager\database.py", line 166, in _get_register_original_entry
  File "amulet\api\level\base_level\chunk_manager.py", line 196, in _raw_get_entry
  File "amulet\api\wrapper\format_wrapper.py", line 466, in load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 447, in _safe_load
amulet.api.errors.ChunkLoadError: Invalid compression type 88
ERROR - Error loading chunk 5 -6 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 88
ERROR - Error loading chunk 2 -5 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 2 -4 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 92
ERROR - Error loading chunk 6 -4 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 2 -5 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 2 -4 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 92
ERROR - Error loading chunk 6 -3 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 54
ERROR - Error loading chunk 4 -2 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 2 -5 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 485, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 252, in _get_interface_and_translator
  File "amulet\level\interfaces\chunk\anvil\base_anvil_interface.py", line 163, in get_translator
AttributeError: 'dict' object has no attribute 'compound'
ERROR - Error loading chunk 2 -4 minecraft:overworld`

This goes on for a while..

**Comment by gentlegiantJGC** [comment]
Please can you run `python -m pip list` and send the output.

**Comment by KnechteVino** [comment]
I'm afraid I can't do that, since I'm using the windows package (Amulet-v0.10.9-Windows-x64)

I also seem to have a slight different problem, because the Editor is now rendering stuff, but has mixed up every chunk's position. The errors in the log are still the same though, no idea why it didn't render at all yesterday..

My worlds are also java, not bedrock, should probably open my own ticket..

**Comment by gentlegiantJGC** [comment]
I thought you were OP. Please open a new issue.
