### ISSUE TITLE
[Bug Report] 3D World Editor returns "Couldn't create OpenGL context"

### ISSUE THREAD

**Issue by CopperWhopper67** [Amulet-Team/Amulet-Map-Editor#856]
### Current Behaviour:

Opening world from server running Paper 1.19.3. When selecting 3D Editor the program returns the following text:

**Failed setting up context
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 178, in _enable_page
  File "amulet_map_editor\programs\edit\edit.py", line 70, in enable
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 150, in __init__
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 62, in __init__
  File "amulet_map_editor\api\opengl\canvas\event_canvas.py", line 15, in __init__
  File "amulet_map_editor\api\opengl\canvas\canvas.py", line 63, in __init__
Exception: Failed setting up context**

### Expected behavior:

Was hoping to open world in 3D Editor successfully 
### Steps To Reproduce:

1. Select world folder
2. Select "3D Editor"

### Environment:

- OS: Windows 10 x64 19045
- Minecraft Platform: Java
- Minecraft Version: 1.19.3
- Amulet Version: 0.10.7

### Additional context
Running as admin does not fix the issue

### Worlds

https://mega.nz/file/799lXSpB#br_5R3I0pcRTKtgEdsl0CKcoD4rJTUU8ZaOkajgC5BM

**Comment by CAOGGL** [comment]
Another error code：
Failed setting up context
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 178, in _enable_page
  File "amulet_map_editor\programs\edit\edit.py", line 70, in enable
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 150, in __init__
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 62, in __init__
  File "amulet_map_editor\api\opengl\canvas\event_canvas.py", line 15, in __init__
  File "amulet_map_editor\api\opengl\canvas\canvas.py", line 63, in __init__
Exception: Failed setting up context

**Comment by NGGCGG2** [comment]
same bug in v0.10.7

**Comment by jjaycc** [comment]
Same bug in Windows 11 Version 10.0.22621.963 with Java Version 8 Update 351 (build 1.8.0_351-b10) (Amulet V0.10.7)

**Comment by yqs112358** [comment]
same bug in v0.10.7

```
Failed setting up context
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\amulet_map_editor\api\framework\pages\world_page.py", line 178, in _enable_page
    self.GetPage(page).enable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\amulet_map_editor\programs\edit\edit.py", line 70, in enable
    self._canvas = EditCanvas(self, self._world)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 150, in __init__
    super().__init__(parent, world)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 62, in __init__
    super().__init__(parent)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\amulet_map_editor\api\opengl\canvas\event_canvas.py", line 15, in __init__
    super().__init__(parent)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\amulet_map_editor\api\opengl\canvas\canvas.py", line 63, in __init__
    raise Exception(f"Failed setting up context")
Exception: Failed setting up context
```

Only occurs on my tencent cloud server
On my local laptop this version works well

**Comment by yqs112358** [comment]
I have installed 0.10.6 and the problem is not exist

**Comment by revelcw** [comment]
Getting the same bug too.

**Comment by imnotjackie** [comment]
Same bug on 0.10.7 Windows 11 Pro
Running the previous non-beta (0.10.6) works fine for me.
