### ISSUE TITLE
[Feature Request] Schematics add parser to for try-excepts for Sponge Schem format

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#872]
### The Problem

I see these types of errors often in the community.

```bat
When I keep trying to import these certain Schematics, I keep getting this Error for both
This file is not a legacy schematic file.
Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\plugins\tools\import_tool.py", line 68, in _on_open_file
  File "amulet\level\load.py", line 34, in load_level
  File "amulet\api\level\structure.py", line 17, in init
  File "amulet\api\level\base_level\base_level.py", line 63, in init
  File "amulet\api\wrapper\format_wrapper.py", line 337, in open
  File "amulet\api\wrapper\structure_format_wrapper.py", line 88, in _open
  File "amulet\level\formats\schematic\format_wrapper.py", line 96, in open_from
amulet.api.errors.ObjectReadError: This file is not a legacy schematic file.
How do I fix this Error?
```

### Feature Description
Is it possible to change the code that parses .schematic files specifically to have a try-except so that if it fails it would attempt to parse it as a sponge schematic when importing if that fails then it can error out because at least in most cases like this, in theory, it would catch them on importing the file even if the extension was incorrectly renamed or exported by a third party tool?

### Alternatives
N/A

### Additional context
Here are the bad schematics that a community member shared with us on the Amulet Discord Server.
[bad_schematics.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/10688298/bad_schematics.zip)

**Comment by gentlegiantJGC** [comment]
That should fix the issue
