### ISSUE TITLE
[Bug Report] Randomized chunk positions

### ISSUE THREAD

**Issue by KnechteVino** [Amulet-Team/Amulet-Map-Editor#885]
### Current Behaviour:
Chunk positions are mixed up (see screenshots)

### Steps To Reproduce:
Start Amulet, open world, open editor

### Environment:

- OS: Windows10
- Minecraft Platform: Java
- Minecraft Version: 1.19.3 and 1.19.4
- Amulet Version: Amulet-v0.10.9-Windows-x64

## Attachments
Logfiles:
[amulet_6804.log](https://github.com/Amulet-Team/Amulet-Map-Editor/files/11042752/amulet_6804.log)
[amulet_8576.log](https://github.com/Amulet-Team/Amulet-Map-Editor/files/11042753/amulet_8576.log)
[amulet_6876.log](https://github.com/Amulet-Team/Amulet-Map-Editor/files/11042754/amulet_6876.log)
### Screenshots
Java 1.19.3 world:
![Screenshot 2023-03-22 164837](https://user-images.githubusercontent.com/66302186/226979677-f0c07482-7de1-4cb0-9555-1a3796ea723c.png)

Java 1.19.4 world:
![Screenshot 2023-03-22 165215](https://user-images.githubusercontent.com/66302186/226979726-310be28d-dd6a-4d1d-9539-f9fc6da4876f.png)

**Comment by gentlegiantJGC** [comment]
Please can you share the world or a world that has the same issue

**Comment by KnechteVino** [comment]
Yes, [it was too large for github](https://we.tl/t-t2mg6etmWw)

**Comment by gentlegiantJGC** [comment]
I can't reproduce this issue with the world you have sent me.
I think there may be a deeper issue.
I have fixed the `'dict' object has no attribute 'compound'` issue

**Comment by gentlegiantJGC** [comment]
I think the actual error is due to this. Not sure why that would happen.
```
2023-03-22 16:45:08,056 - amulet.api.wrapper.format_wrapper - ERROR - Error loading chunk 2 -4 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 442, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 483, in _load_chunk
  File "amulet\level\formats\anvil_world\format.py", line 643, in _get_raw_chunk_data
  File "amulet\level\formats\anvil_world\dimension.py", line 66, in get_chunk_data_layers
  File "amulet\level\formats\anvil_world\dimension.py", line 161, in get_chunk_data
  File "amulet\level\formats\anvil_world\region.py", line 236, in get_data
  File "amulet\level\formats\anvil_world\region.py", line 59, in _decompress
amulet.api.errors.ChunkLoadError: Invalid compression type 92
```
