### ISSUE TITLE
[Bug Report] Error when modifying and saving the same chunk twice

### ISSUE THREAD

**Issue by ashtanmistal** [Amulet-Team/Amulet-Map-Editor#904]
### Current Behaviour:
Unable to save changes on a chunk that had been already modified and saved in the same `level` instance. Only the blocks modified in the first call to `level.save()` were successfully saved in the world. 

### Expected behavior:
Not an error to be thrown, and both sets of changes to be saved. 

### Steps To Reproduce:
- Modify a chunk, either using the `level.set_version_block()` method *or* setting the blocks directly using similar methods as the "Complex Set Block Example" in the documentation. 
- Call `level.save()`. 
- Modify that same chunk again with another set of blocks to be placed.
- Call `level.save()`. Error below is thrown as a result.

This error does *not* occur when `level.close()` (and then `load_level`) is called in between the two sets of changes. 

### Environment:

- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.19.4
- Amulet Version: 1.9.13

### Additional context
Traceback included below:

```
ERROR - Error saving chunk Chunk(104, 56, UnboundedPartial3DArray(dtype=<class 'numpy.uint32'>, shape=(16, inf, 16)), EntityList([]), BlockEntityDict(
))
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\amulet\api\wrapper\format_wrapper.py", line 565, in commit_chunk
    self._commit_chunk(copy.deepcopy(chunk), dimension)
  File "C:\Python310\lib\site-packages\amulet\api\wrapper\format_wrapper.py", line 588, in _commit_chunk
    self._put_raw_chunk_data(cx, cz, raw_chunk_data, dimension)
  File "C:\Python310\lib\site-packages\amulet\level\formats\anvil_world\format.py", line 602, in _put_raw_chunk_data
    self._get_dimension(dimension).put_chunk_data_layers(cx, cz, data)
  File "C:\Python310\lib\site-packages\amulet\level\formats\anvil_world\dimension.py", line 91, in put_chunk_data_layers
    self.__layers[layer_name].put_chunk_data(cx, cz, data)
  File "C:\Python310\lib\site-packages\amulet\level\formats\anvil_world\dimension.py", line 167, in put_chunk_data
    ).write_data(cx & 0x1F, cz & 0x1F, data)
  File "C:\Python310\lib\site-packages\amulet\level\formats\anvil_world\region.py", line 298, in write_data
    self._write_data(cx, cz, bytes_data)
  File "C:\Python310\lib\site-packages\amulet\level\formats\anvil_world\region.py", line 266, in _write_data
    self._sector_manager.free(old_sector)
  File "C:\Python310\lib\site-packages\amulet\level\formats\anvil_world\_sector_manager.py", line 265, in free
    self._reserved.remove(sector)
KeyError: Sector(start=942080, stop=946176)
```

## Attachments

No attachments necessary but I can include more details if needed. 
### Screenshots

![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/70030490/f6133343-9aac-447c-ac0a-122caa276249)

The data to the bottom left of the line was placed before the first call to `level.save()`, and the data to the upper right of the line was the second call to `level.save()` in the same level instance. Note that the chunks that span the line are the same chunks that threw the error, as those had already been modified and saved in the first instance and so any data from the top right that was trying to be saved was not. 

### Worlds

A basic, fresh superflat world with no structures (at least until blocks are written to it). The blocks that I'm writing are from LiDAR data but the process is the same.

**Comment by ashtanmistal** [comment]
Issue closed as this is intended for Amulet-Core. I will repost it there.

**Comment by ashtanmistal** [comment]
Re-opening as it looks like bug reports should be here instead based on Discord serer information? Not sure where the best place for this report is, but I'm happy to move it as needed :)
