### ISSUE TITLE
Older integrated GPUs not well-handled.

### ISSUE THREAD

**Issue by segin** [Amulet-Team/Amulet-Map-Editor#905]
## Bug Report

Older integrated GPUs (e.g. Intel HD 2000) are not handled well.

### Current Behaviour:
Visually identical to the video attached to #552 but strictly speaking, this isn't a duplicate of #552

### Expected behavior:
The editor to either fall back to the most basic OpenGL graphics possible to get something to render, or to give the user a dialog box that their GPU is woefully incapable of running the program

### Steps To Reproduce:
1. Have a sufficiently old Intel CPU with integrated graphics (my case, Intel Core i5-2320 with Intel HD 2000 Graphics)
2. Attempt to use the 3D renderer UI in any capacity.

### Environment:
- OS: Microsoft Windows 11 Pro Insider Preview build 25375.1
- Minecraft Platform: Bedrock
- Minecraft Version: 1.19.83
- Amulet Version: V0.10.10 (but really, I'd imagine all versions are impacted.) 

### Additional context
This integrated GPU is really old and doesn't support a lot of newer OpenGL functions. The reason I can confidently say that this isn't just a duplicate of #552 is that: 
1. The console error log clearly mentions the failure is related to attempting to deduce supported GLSL versions; and
2. I'm aware that Intel's support for OpenGL on this hardware is... abysmal. It's OpenGL 3.1 and not a feature more. 

You get this dumped to the console:
```
Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\plugins\tools\select.py", line 329, in _on_draw
  File "amulet_map_editor\programs\edit\api\renderer.py", line 224, in draw_sky_box
  File "amulet_map_editor\api\opengl\mesh\sky_box.py", line 65, in draw
  File "amulet_map_editor\api\opengl\mesh\tri_mesh.py", line 161, in draw
  File "amulet_map_editor\api\opengl\mesh\tri_mesh.py", line 90, in _setup
  File "amulet_map_editor\api\opengl\shaders\__init__.py", line 35, in get_shader
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1280,
        description = b'invalid enumerant',
        baseOperation = glGetString,
        cArguments = (GL_SHADING_LANGUAGE_VERSION,)
)
```
...multiple times per second... 

![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/480709/971d8dbc-5f70-4926-a47f-a805ccd17226)

The ideal solution is to have some sort of toggle setting to limit the renderer to OpenGL 3.1 (what Intel's drivers support) without any GLSL shaders, a "poor man's graphics" mode, if you will. 

### Screenshots
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/480709/b16426a2-0a64-4dae-9e9b-0d019cf27eeb)

You can also use the video attached to #552, it demonstrates the same behavior as the end user would be aware of it.

### Worlds
Not applicable as it's an OpenGL API issue.

**Comment by segin** [comment]
And in case it helps, here's the output of [gkv311/wglinfo](https://github.com/gkv311/wglinfo):

```
[WGL] WGL extensions:
    WGL_EXT_depth_float, WGL_ARB_buffer_region, WGL_ARB_extensions_string,
    WGL_ARB_make_current_read, WGL_ARB_pixel_format, WGL_ARB_pbuffer,
    WGL_EXT_extensions_string, WGL_EXT_swap_control, WGL_EXT_swap_control_tear,
    WGL_ARB_multisample, WGL_ARB_pixel_format_float, WGL_ARB_framebuffer_sRGB,
    WGL_ARB_create_context, WGL_EXT_pixel_format_packed_float.

[WGL] OpenGL vendor string: Intel
[WGL] OpenGL renderer string: Intel(R) HD Graphics 2000
[WGL] OpenGL version string: 3.1.0 - Build 9.17.10.4459
[WGL] OpenGL shading language version string: 1.40 - Intel Build 9.17.10.4459
[WGL] OpenGL extensions:
    GL_EXT_blend_minmax, GL_EXT_blend_subtract, GL_EXT_blend_color, GL_EXT_abgr,
    GL_EXT_texture3D, GL_EXT_clip_volume_hint, GL_EXT_compiled_vertex_array,
    GL_SGIS_texture_edge_clamp, GL_SGIS_generate_mipmap,
    GL_EXT_draw_range_elements, GL_SGIS_texture_lod, GL_EXT_rescale_normal,
    GL_EXT_packed_pixels, GL_EXT_texture_edge_clamp,
    GL_EXT_separate_specular_color, GL_ARB_multitexture,
    GL_EXT_texture_env_combine, GL_EXT_bgra, GL_EXT_blend_func_separate,
    GL_EXT_secondary_color, GL_EXT_fog_coord, GL_EXT_texture_env_add,
    GL_ARB_texture_cube_map, GL_ARB_transpose_matrix, GL_ARB_texture_env_add,
    GL_IBM_texture_mirrored_repeat, GL_EXT_multi_draw_arrays,
    GL_NV_blend_square, GL_ARB_texture_compression,
    GL_3DFX_texture_compression_FXT1, GL_EXT_texture_filter_anisotropic,
    GL_ARB_texture_border_clamp, GL_ARB_point_parameters,
    GL_ARB_texture_env_combine, GL_ARB_texture_env_dot3,
    GL_ARB_texture_env_crossbar, GL_EXT_texture_compression_s3tc, GL_ARB_shadow,
    GL_ARB_window_pos, GL_EXT_shadow_funcs, GL_EXT_stencil_wrap,
    GL_ARB_vertex_program, GL_EXT_texture_rectangle, GL_ARB_fragment_program,
    GL_EXT_stencil_two_side, GL_ATI_separate_stencil,
    GL_ARB_vertex_buffer_object, GL_EXT_texture_lod_bias,
    GL_ARB_occlusion_query, GL_ARB_fragment_shader, GL_ARB_shader_objects,
    GL_ARB_shading_language_100, GL_ARB_texture_non_power_of_two,
    GL_ARB_vertex_shader, GL_NV_texgen_reflection, GL_ARB_point_sprite,
    GL_ARB_fragment_program_shadow, GL_EXT_blend_equation_separate,
    GL_ARB_depth_texture, GL_ARB_texture_rectangle, GL_ARB_draw_buffers,
    GL_ARB_color_buffer_float, GL_ARB_half_float_pixel, GL_ARB_texture_float,
    GL_ARB_pixel_buffer_object, GL_EXT_framebuffer_object,
    GL_ARB_draw_instanced, GL_ARB_half_float_vertex, GL_ARB_occlusion_query2,
    GL_EXT_draw_buffers2, GL_WIN_swap_hint, GL_EXT_texture_sRGB,
    GL_ARB_multisample, GL_EXT_packed_float, GL_EXT_texture_shared_exponent,
    GL_ARB_texture_rg, GL_ARB_texture_compression_rgtc,
    GL_NV_conditional_render, GL_EXT_texture_swizzle, GL_ARB_sync,
    GL_ARB_framebuffer_sRGB, GL_EXT_packed_depth_stencil,
    GL_ARB_depth_buffer_float, GL_EXT_transform_feedback,
    GL_EXT_framebuffer_blit, GL_EXT_framebuffer_multisample,
    GL_ARB_framebuffer_object, GL_EXT_texture_array, GL_EXT_texture_integer,
    GL_ARB_map_buffer_range, GL_EXT_texture_snorm, GL_INTEL_performance_queries,
    GL_ARB_copy_buffer, GL_ARB_sampler_objects, GL_NV_primitive_restart,
    GL_ARB_seamless_cube_map, GL_ARB_uniform_buffer_object, GL_ARB_depth_clamp,
    GL_ARB_vertex_array_bgra, GL_ARB_shader_bit_encoding,
    GL_ARB_draw_buffers_blend, GL_ARB_texture_query_lod,
    GL_ARB_explicit_attrib_location, GL_ARB_draw_elements_base_vertex,
    GL_ARB_instanced_arrays, GL_ARB_fragment_coord_conventions,
    GL_EXT_gpu_program_parameters, GL_ARB_texture_buffer_object_rgb32,
    GL_ARB_compatibility, GL_ARB_texture_rgb10_a2ui,
    GL_ARB_vertex_type_2_10_10_10_rev, GL_ARB_timer_query, GL_INTEL_map_texture,
    GL_ARB_vertex_array_object, GL_ARB_provoking_vertex.

[WGL] OpenGL (software) vendor string: Microsoft Corporation
[WGL] OpenGL (software) renderer string: GDI Generic
[WGL] OpenGL (software) version string: 1.1.0
[WGL] OpenGL (software) extensions:
    GL_WIN_swap_hint, GL_EXT_bgra, GL_EXT_paletted_texture.


[WGL] 51 WGL Visuals
    visual  x  bf lv rg d st  r  g  b a  ax dp st accum buffs  ms 
  id dep cl sp sz l  ci b ro sz sz sz sz bf th cl  r  g  b  a ns b
------------------------------------------------------------------
0x001 32 wn  . 32  .  r .  .  8  8  8  8  .  .  .  .  .  .  .  . .
0x002 32 wn  . 32  .  r y  .  8  8  8  8  .  .  . 16 16 16 16  . .
0x003 32 wn  . 32  .  r .  .  8  8  8  8  . 24  8  .  .  .  .  . .
0x004 32 wn  . 32  .  r y  .  8  8  8  8  . 24  8 16 16 16 16  . .
0x005 32 wn  . 32  .  r .  .  8  8  8  8  . 16  .  .  .  .  .  . .
0x006 32 wn  . 32  .  r y  .  8  8  8  8  . 16  . 16 16 16 16  . .
0x007 32 wn  . 32  .  r y  .  8  8  8  8  .  .  . 16 16 16 16  . .
0x008 32 wn  . 32  .  r y  .  8  8  8  8  . 16  . 16 16 16 16  . .
0x009 32 wn  . 32  .  r y  .  8  8  8  8  . 24  8 16 16 16 16  . .
0x010 32 wn  . 32  .  r .  .  8  8  8  .  . 32  8 16 16 16  .  . .
0x011 32 wn  . 32  .  r .  .  8  8  8  .  . 16  8 16 16 16  .  . .
0x012 32 wn  . 32  .  r y  .  8  8  8  .  . 32  8 16 16 16  .  . .
0x013 32 wn  . 32  .  r y  .  8  8  8  .  . 16  8 16 16 16  .  . .
0x014 32 wn  . 32  .  r .  .  8  8  8  8  . 32  8 16 16 16 16  . .
0x015 32 wn  . 32  .  r .  .  8  8  8  8  . 16  8 16 16 16 16  . .
0x016 32 wn  . 32  .  r y  .  8  8  8  8  . 32  8 16 16 16 16  . .
0x017 32 wn  . 32  .  r y  .  8  8  8  8  . 16  8 16 16 16 16  . .
0x018 32 wn  . 32  .  c .  .  .  .  .  .  . 32  8  .  .  .  .  . .
0x019 32 wn  . 32  .  c .  .  .  .  .  .  . 16  8  .  .  .  .  . .
0x01a 32 wn  . 32  .  c y  .  .  .  .  .  . 32  8  .  .  .  .  . .
0x01b 32 wn  . 32  .  c y  .  .  .  .  .  . 16  8  .  .  .  .  . .
0x01c 24 bm  . 24  .  r .  .  8  8  8  .  . 32  8 16 16 16  .  . .
0x01d 24 bm  . 24  .  r .  .  8  8  8  .  . 16  8 16 16 16  .  . .
0x01e 24 bm  . 24  .  r .  .  8  8  8  8  . 32  8 16 16 16 16  . .
0x01f 24 bm  . 24  .  r .  .  8  8  8  8  . 16  8 16 16 16 16  . .
0x020 24 bm  . 24  .  c .  .  .  .  .  .  . 32  8  .  .  .  .  . .
0x021 24 bm  . 24  .  c .  .  .  .  .  .  . 16  8  .  .  .  .  . .
0x022 16 bm  . 16  .  r .  .  5  5  5  .  . 32  8 11 11 10  .  . .
0x023 16 bm  . 16  .  r .  .  5  5  5  .  . 16  8 11 11 10  .  . .
0x024 16 bm  . 16  .  r .  .  5  5  5  8  . 32  8  8  8  8  8  . .
0x025 16 bm  . 16  .  r .  .  5  5  5  8  . 16  8  8  8  8  8  . .
0x026 16 bm  . 16  .  c .  .  .  .  .  .  . 32  8  .  .  .  .  . .
0x027 16 bm  . 16  .  c .  .  .  .  .  .  . 16  8  .  .  .  .  . .
0x028  8 bm  .  8  .  r .  .  3  3  2  .  . 32  8 11 11 10  .  . .
0x029  8 bm  .  8  .  r .  .  3  3  2  .  . 16  8 11 11 10  .  . .
0x02a  8 bm  .  8  .  r .  .  3  3  2  8  . 32  8  8  8  8  8  . .
0x02b  8 bm  .  8  .  r .  .  3  3  2  8  . 16  8  8  8  8  8  . .
0x02c  8 bm  .  8  .  c .  .  .  .  .  .  . 32  8  .  .  .  .  . .
0x02d  8 bm  .  8  .  c .  .  .  .  .  .  . 16  8  .  .  .  .  . .
0x02e  4 bm  .  4  .  r .  .  1  1  1  .  . 32  8  5  6  5  .  . .
0x02f  4 bm  .  4  .  r .  .  1  1  1  .  . 16  8  5  6  5  .  . .
0x030  4 bm  .  4  .  r .  .  1  1  1  8  . 32  8  4  4  4  4  . .
0x031  4 bm  .  4  .  r .  .  1  1  1  8  . 16  8  4  4  4  4  . .
0x032  4 bm  .  4  .  c .  .  .  .  .  .  . 32  8  .  .  .  .  . .
0x033  4 bm  .  4  .  c .  .  .  .  .  .  . 16  8  .  .  .  .  . .
------------------------------------------------------------------
    visual  x  bf lv rg d st  r  g  b a  ax dp st accum buffs  ms 
  id dep cl sp sz l  ci b ro sz sz sz sz bf th cl  r  g  b  a ns b
------------------------------------------------------------------

```
