### ISSUE TITLE
0.10.11 Fails to Launch

### ISSUE THREAD

**Issue by GT90V12** [Amulet-Team/Amulet-Map-Editor#909]
### Current Behaviour:

Version 0.10.11 fails to launch after unzipping files, overwriting previous version.
### Expected behavior:

Software would launch without issue.
### Steps To Reproduce:

Double clicking desktop icon would launch software.
### Environment:

Device name	(Redacted)
Processor	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz
Installed RAM	4.00 GB (3.87 GB usable)
Device ID	4AA8F6A0-A1D2-40A1-9ACE-500606ABC875
Product ID	00325-81126-88003-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points
Edition	Windows 11 Home
Version	22H2
Installed on	‎5/‎14/‎2022
OS build	22631.1830
Experience	Windows Feature Experience Pack 1000.22642.1000.0

- Minecraft Platform: Bedrock
- Minecraft Version: 1.20.0.01
- Amulet Version: 0.10.11

## CMD Verbose
C:\MCBES\Amulet>amulet_app
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 40, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "win32com\__init__.py", line 9, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
[7664] Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception!

**Comment by gentlegiantJGC** [comment]
Have you tried deleting the whole directory and extracting again?

**Comment by Benholio** [comment]
FWIW, I have a similar error. I unzipped Amulet into a clean directory. Also - 0.10.10 opens OK.

Windows 10, Intel, x64
Windows version: 10.0.19045
Amulet version: 0.10.11

Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 40, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "win32com\__init__.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "pythoncom.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "pywintypes.py", line 126, in <module>
  File "pywintypes.py", line 48, in __import_pywin32_system_module__
ImportError: Module 'pywintypes' isn't in frozen sys.path ['C:\\Users\\benco\\Downloads\\Amulet\\Amulet\\base_library.zip', 'C:\\Users\\benco\\Downloads\\Amulet\\Amulet\\lib-dynload', 'C:\\Users\\benco\\Downloads\\Amulet\\Amulet', 'C:\\Users\\benco\\Downloads\\Amulet\\Amulet\\pywin32_system32']
[28368] Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception!

**Comment by gentlegiantJGC** [comment]
Can you verify that this file exists in the Amulet directory
`pywin32_system32\pythoncom37.dll`
