### ISSUE TITLE
[Bug Report] 3d editor failing to load on legacy graphics cards

### ISSUE THREAD

**Issue by juozaspo** [Amulet-Team/Amulet-Map-Editor#915]
### Current Behaviour:

After opening a world 3d editor fails to load. It throws error `undefined symbol: eglCreatePlatformWindowSurface` when trying to import module `amulet_map_editor.programs.edit`
### Expected behavior:

3d editor loads w/o error, it should work w/o error with most of video drivers and/or cards including legacy ones.
### Steps To Reproduce:
1. Compile amulet on linux from source and run it
2. Load a world
3. Notice 3d editor tab unavailable
4. Find error in console

### Environment:

- OS: Ubuntu Linux 22.04 LTS
- Minecraft Platform: Java
- Minecraft Version: 1.13
- Amulet Version: 0.10.11

### Additional context
Video: NVidia GeForce 210
Driver: NVidia binary driver version 340 (340.108), from Ubuntu PPA (`ppa:kelebek333/nvidia-legacy`, https://launchpad.net/~kelebek333/+archive/ubuntu/nvidia-legacy) as on Ubuntu 22.04 LTS this driver is no longer in repositories
Driver Opengl version 3.3.0
Relevant console output
```
WARNING - Failed to import amulet_map_editor.programs.edit.
Traceback (most recent call last):
  File "/home/juozas/ENV/lib/python3.9/site-packages/amulet_map_editor/api/framework/pages/world_page.py", line 49, in load_extension
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/juozas/ENV/lib/python3.9/site-packages/amulet_map_editor/programs/edit/__init__.py", line 6, in <module>
    from amulet_map_editor.programs.edit.edit import EditExtension
  File "/home/juozas/ENV/lib/python3.9/site-packages/amulet_map_editor/programs/edit/edit.py", line 19, in <module>
    from amulet_map_editor.programs.edit.api.canvas.edit_canvas import EditCanvas
  File "/home/juozas/ENV/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/__init__.py", line 1, in <module>
    from .edit_canvas_container import EditCanvasContainer
  File "/home/juozas/ENV/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/edit_canvas_container.py", line 2, in <module>
    from amulet_map_editor.api.opengl.canvas_container import CanvasContainer
  File "/home/juozas/ENV/lib/python3.9/site-packages/amulet_map_editor/api/opengl/canvas_container.py", line 2, in <module>
    from wx.glcanvas import GLCanvas
  File "/home/juozas/ENV/lib/python3.9/site-packages/wx/glcanvas.py", line 10, in <module>
    from ._glcanvas import *
ImportError: /home/juozas/ENV/lib/python3.9/site-packages/wx/libwx_gtk3u_gl-3.1.so.5: undefined symbol: eglCreatePlatformWindowSurface
```

## Attachments

[glxinfo output](https://github.com/Amulet-Team/Amulet-Map-Editor/files/11715108/glxinfo.txt)

### Screenshots

![Ekrano kopija_2023-06-11_19-08-31](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/6626242/b2eaafc3-78ae-4aed-ac22-30aa82665d44)

### Worlds

(removed)

**Comment by gentlegiantJGC** [comment]
This is an issue in the window library or your system. This isn't something we can fix.
Here are the first few results from google that may help
https://forums.wxwidgets.org/viewtopic.php?f=23&p=215699
https://bbs.archlinux.org/viewtopic.php?id=286442

We are in the process of switching to Qt which may have better hardware support.
