### ISSUE TITLE
[Bug Report] Your Title Here

### ISSUE THREAD

**Issue by tsavpyn** [Amulet-Team/Amulet-Map-Editor#933]
## Bug Report

Can't load level
### Current Behaviour:

Seems doesn't work with maps from Minecraft BE v1.20.1

### Environment:

- OS: Windows
- Minecraft Platform: Bedrock Edition
- Minecraft Version: v1.20.1
- Amulet Version: v0.10.13

### Additional context
Error text:
```
Unsupported level.dat version 3997439
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\amulet_ui.py", line 183, in open_level
  File "amulet_map_editor\api\framework\pages\world_page.py", line 71, in __init__
  File "amulet\level\load.py", line 30, in load_level
  File "amulet\level\load.py", line 59, in load_format
  File "amulet\level\formats\leveldb_world\format.py", line 174, in __init__
  File "amulet\level\formats\leveldb_world\format.py", line 88, in from_file
  File "amulet\level\formats\leveldb_world\format.py", line 111, in _read_from
amulet.api.errors.ObjectReadError: Unsupported level.dat version 3997439

```

## Attachments

The level file I used (Google Drive, 57MB):
https://drive.google.com/file/d/1inxenhN1PcjLApKuK3Tv0287H-0c4rjP/view?usp=sharing

### Screenshots
Here's the photo version of error text:
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/104400206/f2e9e2b7-2077-45b7-b00e-58d0bee58426)

### Worlds
See attachments

**Comment by gentlegiantJGC** [comment]
The level.dat file is corrupted.
The `level.dat` contains xml data and your `level.dat_old` is a png image

There isn't much Amulet can do since it isn't a valid world.
