### ISSUE TITLE
amulet_app.exe not executing

### ISSUE THREAD

**Issue by imvickykumar999** [Amulet-Team/Amulet-Map-Editor#956]
### Current Behaviour: 
`On clicking the amulet_app.exe file, it opens for less than a second and closes suddenly.`

### Expected behavior: 
I checked on https://www.amuletmc.com/faq
How do I download Amulet?

It says:
For windows you can download the version for your operating system from amuletmc.com and extract the zip file to your computer. Once it is extracted find `amulet_app.exe` and run it.

`It should open a window to edit the world, just like mcedit software opens.`

### Environment:

- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.20.1 
- Amulet Version: latest 

### Screenshots
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/50515418/86e7326f-7a0a-48a5-a477-f7cc2e7e0982)

**Comment by gentlegiantJGC** [comment]
Please can you try the following and report back the output.

In the file explorer window in the Amulet directory shift + right click in empty space.
Click `Open Powershell window here` from the list.
In the blue box that appears type `./amulet_app.exe` and press enter.
There will hopefully be some output. Screenshot it and send it.

**Comment by imvickykumar999** [comment]
> Please can you try the following and report back the output.
> 
> In the file explorer window in the Amulet directory shift + right click in empty space. Click `Open Powershell window here` from the list. In the blue box that appears type `./amulet_app.exe` and press enter. There will hopefully be some output. Screenshot it and send it.

![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/50515418/81b247e1-0802-4bc3-ae13-2384a708007e)

**Comment by gentlegiantJGC** [comment]
PyInstaller has made some changes to this code since I made this build which may have fixed the problem.
I will try making another build. Let me know if it fixes it.

**Comment by samuelh2005** [comment]
Same bug in 0.10.19

**Comment by gentlegiantJGC** [comment]
Please can you copy the console crash

**Comment by samuelh2005** [comment]
@gentlegiantJGC Here it is
```
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 46, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 25, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "win32com\__init__.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pythoncom.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pywintypes.py", line 126, in <module>
  File "pywintypes.py", line 47, in __import_pywin32_system_module__
ImportError: Module 'pywintypes' isn't in frozen sys.path ['D:\\Amulet\\base_library.zip', 'D:\\Amulet\\lib-dynload', 'D:\\Amulet']
[18288] Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception!
```

**Comment by TheDragonFire91** [comment]
I am experiencing the same problem how can I fix it? It's only showing 

![Image](https://github.com/user-attachments/assets/69c1b4d8-c17d-4045-968f-60effe9a3459)

**Comment by gentlegiantJGC** [comment]
> I am experiencing the same problem

That is not the same problem.

**Comment by gentlegiantJGC** [comment]
I haven't had any reports of this for a long time so I suspect this has been fixed. Let me know if you still have this issue.
