### ISSUE TITLE
[Bug Report] Selection box size not updating

### ISSUE THREAD

**Issue by Scroogeee** [Amulet-Team/Amulet-Map-Editor#961]
### Current Behaviour:

After selecting a box in the editor, the shown number values are not updated.
Related error message:
```
Traceback (most recent call last):
  File "/Users/myUsername/opt/anaconda3/envs/amulet/lib/python3.11/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 277, in _on_selection_change
    self._pull_selection()
  File "/Users/myUsername/opt/anaconda3/envs/amulet/lib/python3.11/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 281, in _pull_selection
    self._update_selection_inputs(*self._selection.active_block_positions)
  File "/Users/myUsername/opt/anaconda3/envs/amulet/lib/python3.11/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py", line 288, in _update_selection_inputs
    self._x1.SetValue(x1)
TypeError: SpinCtrl.SetValue(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'float'
```

### Expected behavior:

The values in the number fields should match the size of the box.

### Steps To Reproduce:

1. Open a world in Amulet
2. Select some area by left clicking
3. See that every value in the number fields is 0.

### Environment:

- OS: OSX Ventura 13.4.1 on Apple Silicon (M1 Pro Chip)
- Minecraft Platform: Java
- Minecraft Version:  1.20.1
- Amulet Version:  0.10.19

### Screenshots

<img width="755" alt="Bildschirmfoto 2023-09-02 um 15 06 38" src="https://github.com/Amulet-Team/Amulet-Map-Editor/assets/30441849/79127730-2aa1-4bd8-82d3-c45eea424ca2">

### Worlds

Seems to happen in any world.

**Comment by Scroogeee** [comment]
Fix by editing the `_update_selection_inputs` method of `/Users/myUsername/opt/anaconda3/envs/amulet/lib/python3.11/site-packages/amulet_map_editor/programs/edit/plugins/tools/select.py` like this:
```
    def _update_selection_inputs(
        self, point1: BlockCoordinates, point2: BlockCoordinates
    ):
        (x1, y1, z1), (x2, y2, z2) = point1, point2

        # Add this line vv
        x1, y1, z1, x2, y2, z2 = map(int, [x1, y1, z1, x2, y2, z2])

        self._x1.SetValue(x1)
        self._y1.SetValue(y1)
        self._z1.SetValue(z1)
        self._x2.SetValue(x2)
        self._y2.SetValue(y2)
        self._z2.SetValue(z2)

        # Remove integer casting here, as it would then be obsolete vv
        xdim = abs(x2 - x1)
        ydim = abs(y2 - y1)
        zdim = abs(z2 - z1)

        self._box_size_selector_text.SetLabel(
            self._box_size_selector_fstring.format(
                x=xdim,
                y=ydim,
                z=zdim,
            )
        )
        self._box_volume_text.SetLabel(
            f"{xdim + 1}x{ydim + 1}x{zdim + 1}={(xdim + 1)*(ydim + 1)*(zdim + 1):,}"
        )
        self.Layout()

```
